import{rand}from'./signal.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const css=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const C=()=>({accent:css('--accent')||'#087f70',danger:css('--danger')||'#b53e35',violet:css('--violet')||'#6656d9',warn:css('--warn')||'#c47b18',muted:css('--muted')||'#66777d',line:css('--line')||'#d9e0e2',well:css('--well')||'#fff'});
const rnd=(a,b)=>a+Math.random()*(b-a);
const head=(title,desc,label)=>`<div class="head"><div><div class="eyebrow">${label}</div><h1>${title}</h1><p>${desc}</p></div></div>`;

const LOBES={
 frontal:{name:'Płat czołowy',fun:'funkcje wykonawcze, planowanie, hamowanie reakcji, kontrola uwagi, przygotowanie ruchu i mowa ekspresyjna',bands:['Theta czołowa — kontrola poznawcza i monitorowanie','Beta — aktywacja i przygotowanie ruchowe','Gamma — lokalne przetwarzanie; silnie podatna na EMG'],note:'Nie istnieje jedna „częstotliwość płata czołowego”. Znaczenie pasma zależy od zadania, sieci i generatorów.'},
 parietal:{name:'Płat ciemieniowy',fun:'integracja somatosensoryczna, uwaga przestrzenna, reprezentacja ciała i integracja wielozmysłowa',bands:['Alfa — modulacja uwagowa i hamowanie funkcjonalne','Beta — sieci sensomotoryczne','P300 — często maksimum ciemieniowe, ale ERP nie jest pasmem'],note:'P300 nad Pz jest potencjałem wywołanym, a nie „falą płata ciemieniowego”.'},
 temporal:{name:'Płat skroniowy',fun:'przetwarzanie słuchowe, pamięć, język, rozpoznawanie obiektów i twarzy',bands:['Theta — pamięć i dynamika hipokampalno-korowa','Alfa/beta — zależne od zadania słuchowego i językowego','Gamma — lokalne kodowanie; ostrożnie z EMG skroniowym'],note:'Elektroda T7/T8 nie mierzy wyłącznie płata skroniowego; sygnał skalpowy jest mieszaniną wielu generatorów.'},
 occipital:{name:'Płat potyliczny',fun:'wczesne i złożone przetwarzanie wzrokowe',bands:['Alfa 8–13 Hz — silna potylicznie przy zamkniętych oczach','SSVEP — odpowiedź na okresową stymulację wzrokową','Gamma — szybkie przetwarzanie wzrokowe, trudniejsze w EEG skalpowym'],note:'Klasyczny rytm potyliczny alfa jest dobrym przykładem zależności stan–lokalizacja–pasmo.'}
};
function buildLobes(){const m=document.createElement('section');m.id='mlobes';m.className='module';m.innerHTML=head('Płat–funkcja–pasmo','Interaktywna mapa pokazuje typowe zależności między anatomią, funkcją i aktywnością oscylacyjną. Są to zależności sieciowe i statystyczne — pasmo nie jest przypisane na stałe do jednego płata.','PŁAT–FUNKCJA–PASMO')+`<div class="lobe-layout"><div class="lobe-map"><button class="lobe-shape lobe-frontal active" data-lobe="frontal">czołowy</button><button class="lobe-shape lobe-parietal" data-lobe="parietal">ciemieniowy</button><button class="lobe-shape lobe-temporal" data-lobe="temporal">skroniowy</button><button class="lobe-shape lobe-occipital" data-lobe="occipital">potyliczny</button></div><div><div class="panel" id="lobe-detail"></div><div class="panel"><h2><span class="dot"></span>Najważniejsza zasada</h2><div class="callout">EEG mierzone z powierzchni głowy nie daje relacji „elektroda = płat = funkcja”. Potencjały wynikają z sumowania pól wielu generatorów i przewodzenia objętościowego. Lokalizacja elektrody pomaga interpretować topografię, ale nie zastępuje modelowania źródeł.</div></div></div></div>`;$('#main').appendChild(m);$$('[data-lobe]',m).forEach(b=>b.onclick=()=>{$$('[data-lobe]',m).forEach(x=>x.classList.toggle('active',x===b));renderLobe(b.dataset.lobe)});renderLobe('frontal')}
function renderLobe(k){const m=$('#mlobes'),d=LOBES[k];if(!m)return;$('#lobe-detail',m).innerHTML=`<h2><span class="dot"></span>${d.name}</h2><p><b>Funkcje:</b> ${d.fun}.</p><h3>Najczęściej omawiane zależności</h3><div class="band-tags">${d.bands.map(x=>`<span class="band-tag">${x}</span>`).join('')}</div><div class="readout" style="margin-top:12px">${d.note}</div>`}

const CLIN={
 epilepsy:{name:'Padaczka',metric:'Wyładowania padaczkokształtne',left:'Przykład bez wyładowań padaczkokształtnych',right:'Przykład z wyładowaniami spike / spike-wave',summary:'EEG jest ważnym narzędziem pomocniczym w diagnostyce i klasyfikacji padaczek. Wyładowania międzynapadowe mogą wspierać rozpoznanie, ale ich brak w rutynowym badaniu nie wyklucza padaczki.',features:['ogniskowe spike/sharp-wave','uogólnione spike-and-wave','sen i procedury aktywacyjne mogą zwiększać ujawnianie wyładowań','prawidłowy rutynowy EEG nie wyklucza padaczki'],kind:'spike'},
 encephalopathy:{name:'Encefalopatie metaboliczne',metric:'Uogólnione spowolnienie i wyładowania okresowe',left:'Przykład czuwania: szybsze tło z rytmem alfa',right:'Przykład encefalopatii: rozlane delta/theta i fale o morfologii trójfazowej',summary:'W encefalopatiach metabolicznych i toksycznych EEG często pokazuje uogólnione spowolnienie. Fale o morfologii trójfazowej mogą występować, ale nie wskazują jednej konkretnej etiologii.',features:['rozlane spowolnienie theta/delta','utrata lub zwolnienie prawidłowego rytmu dominującego','możliwe uogólnione wyładowania okresowe z morfologią trójfazową','EEG pomaga ocenić ciężkość zaburzeń czynności mózgu i wykluczać stan padaczkowy'],kind:'enceph'},
 cjd:{name:'Choroba Creutzfeldta-Jakoba',metric:'Okresowe kompleksy ostrych fal',left:'Przykład bez zmian okresowych',right:'Przykład okresowych kompleksów ostrych fal na zwolnionym tle',summary:'W sporadycznej chorobie Creutzfeldta-Jakoba mogą pojawiać się okresowe kompleksy ostrych fal, zwykle wraz ze spowolnieniem tła. Czułość zależy od stadium choroby i wariantu klinicznego.',features:['okresowe kompleksy ostrych fal około 1 Hz mogą pojawić się w przebiegu choroby','częste jest postępujące spowolnienie czynności podstawowej','EEG jest elementem diagnostyki wspierającej, obok obrazu klinicznego, MRI i biomarkerów płynowych','brak typowego wzorca nie wyklucza CJD'],kind:'cjd'},
 nmda:{name:'Zapalenie mózgu anti-NMDAR',metric:'Delta rytmiczna / extreme delta brush',left:'Przykład bez charakterystycznego wzorca',right:'Przykład extreme delta brush: wolna delta z nałożoną szybką aktywnością',summary:'W zapaleniu mózgu z przeciwciałami przeciw receptorowi NMDA EEG jest często nieprawidłowy. Extreme delta brush jest charakterystycznym wzorcem opisywanym u części pacjentów, ale nie występuje we wszystkich przypadkach i nie zastępuje diagnostyki immunologicznej.',features:['częste uogólnione lub rozlane spowolnienie','możliwa rytmiczna aktywność delta','extreme delta brush: delta z nałożoną szybką aktywnością beta','częste napady i możliwość stanu padaczkowego wymagają monitorowania cEEG'],kind:'nmda'},
 hsv:{name:'Zapalenie mózgu HSV',metric:'Zmiany skroniowe i wyładowania okresowe',left:'Przykład bez ogniskowych zmian skroniowych',right:'Przykład ogniskowego spowolnienia z okresowymi ostrymi wyładowaniami',summary:'W opryszczkowym zapaleniu mózgu EEG może wykazywać ogniskowe lub lateralizowane spowolnienie i okresowe wyładowania, często w okolicach skroniowych. Wzorzec wspiera ocenę kliniczną, ale nie zastępuje PCR i obrazowania.',features:['ogniskowe spowolnienie, często skroniowe','lateralized periodic discharges mogą pojawiać się w ostrej fazie','napady padaczkowe są częste i mogą być elektroograficzne','EEG jest szczególnie przydatny przy zaburzeniach świadomości i podejrzeniu napadów niekonwulsyjnych'],kind:'hsv'},
 dementia:{name:'Otępienia / AD',metric:'Rytm dominujący i względna moc wolnych pasm',left:'Przykład bez otępienia: wyraźniejszy tylny rytm alfa',right:'Przykład korelatu: spowolnienie, większy udział theta/delta',summary:'W chorobie Alzheimera i części innych zespołów otępiennych często obserwuje się spowolnienie aktywności spoczynkowej oraz zmiany łączności. Wzorzec zależy od etiologii i stadium.',features:['spowolnienie częstotliwości dominującej','wzrost theta/delta i osłabienie tylnego alfa w wielu kohortach','zmiany łączności w pasmach','wynik zależy m.in. od stadium, leków i stanu czuwania'],kind:'slow'},
 schizophrenia:{name:'Schizofrenia',metric:'ERP P300 — amplituda i latencja',left:'Przykład kontrolny: większa amplituda P300',right:'Przykład korelatu grupowego: mniejsza amplituda i późniejszy P300',summary:'Badania opisują różnice w mocy widmowej, synchronizacji i ERP, ale nie ma pojedynczego wzorca EEG pozwalającego rozpoznać schizofrenię u konkretnej osoby.',features:['w części badań wzrost wolnej aktywności delta/theta','zmiany alfa i beta zależne od kohorty oraz leczenia','badane są nieprawidłowości gamma i synchronizacji','często analizowane są P300 i mismatch negativity'],kind:'p300'},
 adhd:{name:'ADHD',metric:'Stosunek mocy theta do beta (TBR)',left:'Przykład kontrolny: niższy TBR',right:'Przykład historycznie badanego korelatu: wyższy TBR',summary:'Historycznie badano zwiększony stosunek theta/beta, jednak wyniki są heterogeniczne. TBR nie powinien potwierdzać rozpoznania ADHD ani zastępować standardowej oceny klinicznej.',features:['TBR ma ograniczoną swoistość','duża heterogeniczność rozwojowa i osobnicza','EEG/qEEG może być narzędziem badawczym, nie samodzielnym testem diagnostycznym','wiek i indywidualna częstotliwość alfa wpływają na interpretację'],kind:'tbr'}
};
function axes(ctx,w,h,label=''){const c=C();ctx.clearRect(0,0,w,h);ctx.fillStyle=c.well;ctx.fillRect(0,0,w,h);ctx.strokeStyle=c.line;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(36,i*h/4);ctx.lineTo(w-8,i*h/4);ctx.stroke()}ctx.fillStyle=c.muted;ctx.font='10px IBM Plex Mono';if(label)ctx.fillText(label,w-72,h-7)}
function line(ctx,a,min,max,color){const w=ctx.canvas.width,h=ctx.canvas.height,x0=38,y0=12,pw=w-50,ph=h-38;ctx.strokeStyle=color;ctx.lineWidth=1.7;ctx.beginPath();a.forEach((v,i)=>{const x=x0+i/Math.max(1,a.length-1)*pw,y=y0+ph-(v-min)/(max-min)*ph;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function wave(kind,affected=false){const fs=250,n=1000,a=[];for(let i=0;i<n;i++){const t=i/fs;let v=rnd(-2.5,2.5);if(kind==='spike'){v+=6*Math.sin(2*Math.PI*10*t);if(affected)for(const c of[1.05,2.05,3.1]){const d=t-c;v+=72*Math.exp(-(d*d)/.00012)-25*Math.exp(-((d-.05)**2)/.001)}}else if(kind==='p300'){const ms=t*1000-200,vp=(affected?5.5:11)*Math.exp(-((ms-(affected?390:335))**2)/(2*55**2));v+=2*Math.sin(2*Math.PI*7*t)+vp}else if(kind==='slow'){v+=(affected?16:4)*Math.sin(2*Math.PI*(affected?5.5:5)*t)+(affected?5:18)*Math.sin(2*Math.PI*(affected?9:10)*t)}else if(kind==='tbr'){v+=(affected?15:7)*Math.sin(2*Math.PI*6*t)+(affected?6:12)*Math.sin(2*Math.PI*19*t)}else if(kind==='enceph'){v+=(affected?18:4)*Math.sin(2*Math.PI*(affected?2.6:6)*t)+(affected?7:17)*Math.sin(2*Math.PI*(affected?5:10)*t);if(affected)for(let c=.55;c<4;c+=1.0){const d=t-c;v+=18*Math.exp(-(d*d)/.006)-11*Math.exp(-((d-.09)**2)/.012)+6*Math.exp(-((d-.19)**2)/.018)}}else if(kind==='cjd'){v+=(affected?10:3)*Math.sin(2*Math.PI*(affected?4.5:10)*t);if(affected)for(let c=.35;c<4;c+=.92){const d=t-c;v+=46*Math.exp(-(d*d)/.0008)-18*Math.exp(-((d-.045)**2)/.003)}}else if(kind==='nmda'){v+=(affected?20:4)*Math.sin(2*Math.PI*(affected?2.2:7)*t)+(affected?0:15)*Math.sin(2*Math.PI*10*t);if(affected)v+=7*(.5+.5*Math.sin(2*Math.PI*2.2*t))*Math.sin(2*Math.PI*27*t)}else if(kind==='hsv'){v+=(affected?15:4)*Math.sin(2*Math.PI*(affected?3.2:8)*t)+(affected?3:14)*Math.sin(2*Math.PI*10*t);if(affected)for(let c=.45;c<4;c+=.72){const d=t-c;v+=35*Math.exp(-(d*d)/.0015)-13*Math.exp(-((d-.055)**2)/.004)}}a.push(v)}return a}
function drawPair(key){const m=$('#mclinical'),d=CLIN[key];if(!m||!d)return;for(const [cv,affected] of [[$('#clinNormal',m),false],[$('#clinAffected',m),true]]){if(!cv)continue;const ctx=cv.getContext('2d');axes(ctx,cv.width,cv.height,d.kind==='p300'?'czas / ERP':'4 s');const wide=['spike','cjd'].includes(d.kind);line(ctx,wave(d.kind,affected),wide?-90:-45,wide?90:45,affected?C().danger:C().accent)}$('#clinCompareTitle',m).textContent=d.metric;$('#clinLeftLabel',m).textContent=d.left;$('#clinRightLabel',m).textContent=d.right;$('#clinCompareNote',m).innerHTML=`<b>Interpretacja:</b> ${d.summary}`;$('#clintext',m).innerHTML=`<h2><span class="dot"></span>${d.name}</h2><p style="line-height:1.55">${d.summary}</p><ul>${d.features.map(x=>`<li>${x}</li>`).join('')}</ul>`}
function buildClinical(){const m=document.createElement('section');m.id='mclinical';m.className='module';m.innerHTML=head('EEG klinicznie','Porównaj wariant kontrolny z przykładem cechy opisywanej w danym zaburzeniu. Zwróć uwagę na różnicę między korelatem grupowym a zwalidowanym markerem diagnostycznym.','EEG KLINICZNIE')+`<div class="panel"><div class="clinical-tabs">${Object.entries(CLIN).map(([k,v])=>`<button class="btn ${k==='epilepsy'?'active':''}" data-clin="${k}">${v.name}</button>`).join('')}</div></div><div class="clinical-grid"><div class="panel"><h2><span class="dot"></span><span id="clinCompareTitle">Porównanie</span></h2><div class="clinical-compare"><div><h3 id="clinLeftLabel"></h3><canvas id="clinNormal" width="430" height="260"></canvas></div><div><h3 id="clinRightLabel"></h3><canvas id="clinAffected" width="430" height="260"></canvas></div></div><div class="readout" id="clinCompareNote" style="margin-top:10px"></div><div class="clinical-correlation-warning"><b>Korelat ≠ marker diagnostyczny.</b> Różnica statystyczna między grupami nie oznacza, że można na jej podstawie wiarygodnie rozpoznać zaburzenie u pojedynczej osoby. Marker diagnostyczny wymaga osobnej walidacji czułości, swoistości, powtarzalności i wartości dodanej względem standardowej diagnostyki.</div></div><div><div class="panel" id="clintext"></div><div class="clinical-warning" style="margin-top:14px"><b>Ograniczenie diagnostyczne:</b> EEG interpretuje się razem z wywiadem, badaniem neurologicznym, lekami, snem, wiekiem, obrazowaniem i badaniami laboratoryjnymi odpowiednimi dla podejrzewanej jednostki.</div><div class="panel"><h2><span class="dot"></span>Źródła dydaktyczne</h2><div class="row"><a class="btn" target="_blank" rel="noopener" href="https://www.ilae.org/guidelines/eeg">ILAE EEG</a><a class="btn" target="_blank" rel="noopener" href="https://pubmed.ncbi.nlm.nih.gov/22933737/">anti-NMDAR</a><a class="btn" target="_blank" rel="noopener" href="https://pubmed.ncbi.nlm.nih.gov/27760867/">ADHD</a><a class="btn" target="_blank" rel="noopener" href="https://pubmed.ncbi.nlm.nih.gov/40379988/">Otępienia</a></div></div></div></div>`;$('#main').appendChild(m);$$('[data-clin]',m).forEach(b=>b.onclick=()=>{$$('[data-clin]',m).forEach(x=>x.classList.toggle('active',x===b));drawPair(b.dataset.clin)});drawPair('epilepsy')}

window.addEventListener('load',()=>{buildLobes();buildClinical()},{once:true});
window.addEventListener('eeg:theme',()=>{const b=$('#mclinical [data-clin].active');if(b)requestAnimationFrame(()=>drawPair(b.dataset.clin))});