import{EEGEngine,ELECTRODES,dftPower,welch,bandPower,clamp,rand}from'./signal.js';

const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const eng=new EEGEngine();
const css=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const col=()=>({accent:css('--accent'),violet:css('--violet'),muted:css('--muted'),line:css('--line'),danger:css('--danger'),warn:css('--warn'),ok:css('--ok')});
const fmt=(v,d=1)=>Number(v).toFixed(d);
const head=(title,desc,label)=>`<div class="head"><div><div class="eyebrow">${label}</div><h1>${title}</h1><p>${desc}</p></div></div>`;

function axes(ctx,w,h,xlabel=''){const c=col();ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.strokeStyle=c.line;ctx.lineWidth=1;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(38,i*h/5);ctx.lineTo(w-8,i*h/5);ctx.stroke()}ctx.fillStyle=c.muted;ctx.font='10px IBM Plex Mono';if(xlabel)ctx.fillText(xlabel,w-55,h-7)}
function plot(ctx,a,x0,y0,w,h,min,max,color,lw=1.5){ctx.strokeStyle=color;ctx.lineWidth=lw;ctx.beginPath();a.forEach((v,i)=>{const x=x0+i/Math.max(a.length-1,1)*w,y=y0+h-(v-min)/(max-min)*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function showModule(id){$$('.module').forEach(m=>m.classList.toggle('active',m.id===id));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='m1x')drawEnhancedSignal();if(id==='mfft')drawFFT();if(id==='mpostx')drawPost();if(id==='msimlive')drawSimLive();}

function rebuildNav(){
 const items=[
  ['m0','Start','workflow i zasady'],['m1x','Sygnał i pasma','rytmy, artefakty, próbkowanie'],['mfft','FFT','czas → częstotliwość'],['m2','Montaż i QC','10–20, impedancja, referencja'],['m3','Eksperyment oddball','bodźce, triggery, reakcje'],['m5','PreProcessing','kontrola i czyszczenie'],['mpostx','PostProcessing','ERP, PSD, cechy'],['mfiles','Zapis danych EEG','EDF, BDF, EEG, BIDS'],['msimlive','SimLive','kamera → oczy → EEG'],['m6','Multimodalność','EMG, EKG, EDA, wzrok'],['m7','Źródła','forward/inverse problem']
 ];
 const n=$('#nav');n.innerHTML='<h4>Wirtualne laboratorium</h4>';
 items.forEach((x,i)=>{const b=document.createElement('button');b.dataset.go=x[0];b.innerHTML=`<span class="n">${i}</span><span><div class="t">${x[1]}</div><div class="d">${x[2]}</div></span>`;b.onclick=()=>showModule(x[0]);n.appendChild(b)});
 n.querySelector('[data-go="m0"]')?.classList.add('active');
}

function buildEnhancedSignal(){
 const old=$('#m1');if(old)old.classList.remove('active');
 const m=document.createElement('section');m.id='m1x';m.className='module';
 const bands=[['delta','Delta','0.5–4 Hz','sen głęboki, wolne składowe'],['theta','Theta','4–8 Hz','senność, pamięć, kontrola poznawcza'],['alpha','Alfa','8–13 Hz','silna potylicznie przy zamkniętych oczach'],['beta','Beta','13–30 Hz','aktywacja korowa i komponent EMG'],['gamma','Gamma','30–55 Hz','szybka aktywność, podatna na EMG']];
 const artifacts=[['blink','Mrugnięcie','EOG: duży wolny transient frontalny'],['saccade','Sakkada','poziomy EOG z przeciwną polaryzacją'],['emg','EMG czołowe','szerokopasmowy szum mięśniowy'],['jaw','Zaciskanie szczęki','silny EMG skroniowy'],['move','Ruch głowy','duży dryf i zmiana linii bazowej'],['cable','Poruszenie przewodu','oscylacyjny artefakt mechaniczny'],['pop','Electrode pop','nagły skok pojedynczego kanału'],['ecg','ECG','periodyczna domieszka zespołu QRS'],['sweat','Dryf potowy','bardzo wolna zmiana potencjału'],['lineburst','Burst 50 Hz','chwilowo nasilone zakłócenie sieciowe']];
 m.innerHTML=head('Sygnał EEG i pasma częstotliwości','Pasma można teraz ustawiać precyzyjnie przyciskami, polem liczbowym lub gotowymi profilami. Artefakty są pogrupowane według źródła, a zapis i widmo aktualizują się po każdej zmianie.','SYGNAŁ')+`
 <div class="grid g2"><div>
  <div class="panel"><h2><span class="dot"></span>Pasma częstotliwości</h2><div class="band-grid">${bands.map(([id,n,r,d])=>`<div class="band-card" data-band-card="${id}"><div class="band-title"><strong>${n}</strong><span>${r}</span></div><p>${d}</p><div class="band-control"><button class="mini" data-band-minus="${id}" aria-label="Zmniejsz ${n}">−</button><input type="number" min="0" max="100" step="5" value="${eng.bands[id]}" data-band="${id}"><span>%</span><button class="mini" data-band-plus="${id}" aria-label="Zwiększ ${n}">+</button></div><div class="band-meter"><i data-meter="${id}" style="width:${eng.bands[id]}%"></i></div></div>`).join('')}</div>
   <div class="preset-row"><button class="btn" data-preset="rest">Relaks / oczy zamknięte</button><button class="btn" data-preset="alert">Czuwanie</button><button class="btn" data-preset="drowsy">Senność</button><button class="btn" data-preset="flat">Wyrównaj pasma</button></div>
  </div>
  <div class="panel"><h2><span class="dot"></span>Wywołaj artefakt</h2><div class="artifact-grid">${artifacts.map(([id,n,d])=>`<button class="artifact-card" data-artx="${id}"><strong>${n}</strong><span>${d}</span></button>`).join('')}</div></div>
  <div class="panel"><h2><span class="dot"></span>Warunki rejestracji</h2><div class="row"><button class="btn on" id="xeyes">Oczy: zamknięte</button><label class="compact-field">fs <select id="xfs"><option>125</option><option selected>250</option><option>500</option><option>1000</option></select></label></div><div class="field" style="margin-top:12px"><label>Zakłócenie sieciowe 50 Hz <output id="xlineout">4 µV</output></label><input id="xline" type="range" min="0" max="20" value="4"></div></div>
 </div><div>
  <div class="panel"><h2><span class="dot"></span>EEG — 4 s</h2><canvas id="xeeg" width="950" height="390"></canvas><div class="legend"><span>Fp1, Fz, Cz, Pz, O1, O2</span><span>skala ±90 µV</span></div></div>
  <div class="panel"><h2><span class="dot"></span>Widmo mocy — O1</h2><canvas id="xpsd" width="950" height="270"></canvas><div class="readout" id="xread"></div></div>
 </div></div>`;
 $('#main').appendChild(m);
 $$('[data-band]',m).forEach(inp=>inp.onchange=()=>{eng.setBand(inp.dataset.band,inp.value);syncBand(inp.dataset.band);drawEnhancedSignal()});
 $$('[data-band-minus]',m).forEach(b=>b.onclick=()=>changeBand(b.dataset.bandMinus,-5));
 $$('[data-band-plus]',m).forEach(b=>b.onclick=()=>changeBand(b.dataset.bandPlus,5));
 $$('[data-preset]',m).forEach(b=>b.onclick=()=>preset(b.dataset.preset));
 $$('[data-artx]',m).forEach(b=>b.onclick=()=>{eng.artifact(b.dataset.artx);drawEnhancedSignal();b.classList.add('fired');setTimeout(()=>b.classList.remove('fired'),350)});
 $('#xeyes',m).onclick=e=>{eng.eyesClosed=!eng.eyesClosed;e.currentTarget.textContent='Oczy: '+(eng.eyesClosed?'zamknięte':'otwarte');e.currentTarget.classList.toggle('on',eng.eyesClosed);drawEnhancedSignal()};
 $('#xfs',m).onchange=e=>{eng.setFs(e.target.value);drawEnhancedSignal()};
 $('#xline',m).oninput=e=>{eng.lineNoise=+e.target.value;$('#xlineout',m).textContent=e.target.value+' µV';drawEnhancedSignal()};
 function changeBand(id,d){eng.setBand(id,eng.bands[id]+d);syncBand(id);drawEnhancedSignal()}
 function syncBand(id){const inp=$(`[data-band="${id}"]`,m);inp.value=eng.bands[id];$(`[data-meter="${id}"]`,m).style.width=eng.bands[id]+'%'}
 function preset(p){const maps={rest:{delta:35,theta:32,alpha:85,beta:22,gamma:10},alert:{delta:18,theta:25,alpha:35,beta:70,gamma:38},drowsy:{delta:55,theta:82,alpha:35,beta:18,gamma:8},flat:{delta:45,theta:45,alpha:45,beta:45,gamma:45}};Object.entries(maps[p]).forEach(([k,v])=>{eng.setBand(k,v);syncBand(k)});eng.eyesClosed=p==='rest';$('#xeyes',m).textContent='Oczy: '+(eng.eyesClosed?'zamknięte':'otwarte');$('#xeyes',m).classList.toggle('on',eng.eyesClosed);drawEnhancedSignal()}
}

function drawEnhancedSignal(){const m=$('#m1x');if(!m)return;const d=eng.generate(4),ids=['Fp1','Fz','Cz','Pz','O1','O2'],cv=$('#xeeg',m),ctx=cv.getContext('2d'),c=col(),W=cv.width,H=cv.height;axes(ctx,W,H,'4 s');const row=(H-35)/ids.length;ids.forEach((id,k)=>{const mid=10+row*(k+.5);ctx.fillStyle=c.muted;ctx.font='10px IBM Plex Mono';ctx.fillText(id,7,mid+3);ctx.strokeStyle=c.accent;ctx.beginPath();d[id].forEach((v,i)=>{const x=45+i/(d[id].length-1)*(W-60),y=mid-clamp(v,-90,90)/90*row*.42;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()});const p=welch(d.O1,eng.fs),pc=$('#xpsd',m),px=pc.getContext('2d');axes(px,pc.width,pc.height,'Hz');const max=Math.max(...p.map(q=>q.p),1);px.strokeStyle=c.violet;px.lineWidth=2;px.beginPath();p.forEach((q,i)=>{if(q.f>60)return;const x=40+q.f/60*(pc.width-55),y=pc.height-28-q.p/max*(pc.height-45);i?px.lineTo(x,y):px.moveTo(x,y)});px.stroke();const bp={δ:bandPower(p,.5,4),θ:bandPower(p,4,8),α:bandPower(p,8,13),β:bandPower(p,13,30),γ:bandPower(p,30,55)},tot=Object.values(bp).reduce((a,b)=>a+b,0)||1;$('#xread',m).innerHTML=Object.entries(bp).map(([k,v])=>`${k}: <b>${fmt(v/tot*100,0)}%</b>`).join(' · ')+` · fs=<b>${eng.fs} Hz</b>`}

function buildFFT(){const m=document.createElement('section');m.id='mfft';m.className='module';m.innerHTML=head('FFT — z dziedziny czasu do częstotliwości','Ta sama seria próbek jest pokazana jako przebieg czasowy oraz jako amplituda składowych częstotliwościowych. Zmieniaj czas okna i funkcję okna, aby zobaczyć rozdzielczość częstotliwościową i leakage.','FFT')+`<div class="panel"><div class="row fft-tools"><label class="compact-field">Kanał <select id="fftch"><option>O1</option><option>Pz</option><option>Cz</option><option>Fp1</option></select></label><label class="compact-field">Długość <select id="fftlen"><option value="1">1 s</option><option value="2" selected>2 s</option><option value="4">4 s</option></select></label><label class="compact-field">Okno <select id="fftwin"><option value="hann">Hann</option><option value="rect">Prostokątne</option></select></label><button class="btn primary" id="fftrun">Przelicz FFT</button></div></div><div class="fft-flow"><div class="panel"><h2><span class="dot"></span>Dziedzina czasu</h2><canvas id="ffttime" width="560" height="300"></canvas><div class="readout" id="timeinfo"></div></div><div class="fft-arrow"><b>FFT</b><span>→</span><small>x[n] → X[k]</small></div><div class="panel"><h2><span class="dot"></span>Dziedzina częstotliwości</h2><canvas id="fftfreq" width="560" height="300"></canvas><div class="readout" id="fftinfo"></div></div></div><div class="callout" style="margin-top:14px"><b>Interpretacja:</b> FFT nie „tworzy” nowych informacji. Rozkłada ten sam skończony fragment sygnału na składowe sinusoidalne. Rozdzielczość częstotliwościowa jest w przybliżeniu równa 1/T, gdzie T jest długością analizowanego okna.</div>`;$('#main').appendChild(m);$('#fftrun',m).onclick=drawFFT;['fftch','fftlen','fftwin'].forEach(id=>$(`#${id}`,m).onchange=drawFFT)}
function drawFFT(){const m=$('#mfft');if(!m)return;const sec=+$('#fftlen',m).value,ch=$('#fftch',m).value,win=$('#fftwin',m).value,d=eng.generate(sec)[ch],x=win==='hann'?d.map((v,i)=>v*(.5-.5*Math.cos(2*Math.PI*i/(d.length-1)))):d.slice(),spec=dftPower(x,eng.fs,Math.min(60,eng.fs/2-1)),c=col();const a=$('#ffttime',m),ac=a.getContext('2d');axes(ac,a.width,a.height,'czas [s]');plot(ac,d,42,15,a.width-55,a.height-45,-100,100,c.accent,1.4);const f=$('#fftfreq',m),fc=f.getContext('2d');axes(fc,f.width,f.height,'Hz');const max=Math.max(...spec.map(q=>q.p),1);fc.strokeStyle=c.violet;fc.lineWidth=2;fc.beginPath();spec.forEach((q,i)=>{const xx=42+q.f/60*(f.width-55),yy=f.height-28-q.p/max*(f.height-45);i?fc.lineTo(xx,yy):fc.moveTo(xx,yy)});fc.stroke();const top=[...spec].sort((a,b)=>b.p-a.p).slice(0,4).map(q=>q.f+' Hz').join(', ');$('#timeinfo',m).innerHTML=`N=<b>${d.length}</b> próbek · T=<b>${sec} s</b> · fs=<b>${eng.fs} Hz</b>`;$('#fftinfo',m).innerHTML=`Δf ≈ <b>${fmt(1/sec,2)} Hz</b> · dominujące składowe: <b>${top}</b>`}

function buildPost(){const m=document.createElement('section');m.id='mpostx';m.className='module';m.innerHTML=head('PostProcessing — cechy i interpretacja','Po oczyszczeniu sygnału wyznaczamy cechy: ERP, PSD, moc pasmową i proste miary czasu–częstotliwości. Ten etap nie powinien naprawiać jakości danych, tylko odpowiadać na pytanie badawcze.','POSTPROCESSING')+`<div class="grid g2"><div><div class="panel"><h2><span class="dot"></span>Wybór analizy</h2><div class="post-tabs"><button class="btn on" data-post="erp">ERP</button><button class="btn" data-post="psd">PSD</button><button class="btn" data-post="features">Cechy pasmowe</button></div><div class="field" style="margin-top:12px"><label>Liczba prób do uśrednienia <output id="postn">30</output></label><input id="postnr" type="range" min="1" max="100" value="30"></div><div class="readout" id="postdesc"></div></div><div class="callout">PreProcessing odpowiada głównie na pytanie „czy dane są wiarygodne i czyste?”, a PostProcessing — „jaką cechę policzyć, aby przetestować hipotezę?”.</div></div><div class="panel"><h2><span class="dot"></span>Wynik analizy</h2><canvas id="postcanvas" width="900" height="420"></canvas><div class="readout" id="postread"></div></div></div>`;$('#main').appendChild(m);$$('[data-post]',m).forEach(b=>b.onclick=()=>{$$('[data-post]',m).forEach(x=>x.classList.toggle('on',x===b));m.dataset.post=b.dataset.post;drawPost()});m.dataset.post='erp';$('#postnr',m).oninput=e=>{$('#postn',m).textContent=e.target.value;drawPost()}}
function drawPost(){const m=$('#mpostx');if(!m)return;const mode=m.dataset.post||'erp',cv=$('#postcanvas',m),ctx=cv.getContext('2d'),c=col();axes(ctx,cv.width,cv.height,mode==='erp'?'ms':'Hz');if(mode==='erp'){const n=+$('#postnr',m).value,fs=250,N=250,avg=new Array(N).fill(0);for(let tr=0;tr<n;tr++)for(let i=0;i<N;i++){const ms=i/fs*1000-200;avg[i]+=(rand(-9,9)+11*Math.exp(-((ms-340-rand(-20,20))**2)/(2*48**2)))/n}plot(ctx,avg,45,18,cv.width-60,cv.height-50,-10,18,c.accent,2);$('#postdesc',m).textContent='ERP: segmentacja względem triggera, baseline, odrzucenie złych epok i uśrednianie.';$('#postread',m).innerHTML=`Uśredniono <b>${n}</b> prób. Większe N zmniejsza niezależny szum w przybliżeniu jak 1/√N.`}else if(mode==='psd'){const d=eng.generate(4).O1,p=welch(d,eng.fs),max=Math.max(...p.map(x=>x.p),1);ctx.strokeStyle=c.violet;ctx.lineWidth=2;ctx.beginPath();p.filter(q=>q.f<=60).forEach((q,i)=>{const x=45+q.f/60*(cv.width-60),y=cv.height-30-q.p/max*(cv.height-55);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();$('#postdesc',m).textContent='PSD: rozkład mocy sygnału po częstotliwości; Welch redukuje wariancję względem pojedynczej FFT.';$('#postread',m).innerHTML='PSD Welch dla kanału <b>O1</b>.'}else{const d=eng.generate(4).O1,p=welch(d,eng.fs),bands=[['δ',.5,4],['θ',4,8],['α',8,13],['β',13,30],['γ',30,55]],vals=bands.map(x=>bandPower(p,x[1],x[2])),max=Math.max(...vals,1);bands.forEach((b,i)=>{const bw=(cv.width-80)/5,h=vals[i]/max*(cv.height-75);ctx.fillStyle=i===2?c.accent:c.violet;ctx.fillRect(50+i*bw,cv.height-35-h,bw*.62,h);ctx.fillStyle=c.muted;ctx.fillText(b[0],55+i*bw,cv.height-15)});$('#postdesc',m).textContent='Cechy pasmowe: agregacja PSD w ustalonych zakresach częstotliwości.';$('#postread',m).innerHTML=`Największa moc względna: <b>${bands[vals.indexOf(max)]?.[0]||'—'}</b>.`}}

const FORMATS={
 EDF:{title:'EDF / EDF+',ext:'.edf',kind:'format sygnału',desc:'European Data Format. Nagłówek ASCII + rekordy danych; EDF używa próbek 16-bitowych. EDF+ dodaje standardowe adnotacje.',tree:['header (256 B)','signal headers (256 B × N)','data record 1','  ch1 int16 samples','  ch2 int16 samples','data record 2','annotations (EDF+)']},
 BDF:{title:'BDF / BDF+',ext:'.bdf',kind:'format sygnału',desc:'Rozszerzenie BioSemi wywodzące się z EDF. Typowo przechowuje próbki 24-bitowe i zapewnia większy zakres cyfrowy.',tree:['EDF-like header','signal headers','data records','  channel samples: 24-bit','status/trigger channel','BDF+ annotations']},
 EEG:{title:'BrainVision EEG',ext:'.eeg',kind:'zestaw plików',desc:'Plik .eeg jest binarnym payloadem BrainVision; interpretacja wymaga zwykle pliku .vhdr, a markery są w .vmrk. Samo rozszerzenie .eeg nie definiuje jednego uniwersalnego standardu.',tree:['sub-01_task-demo.eeg','sub-01_task-demo.vhdr','  sampling interval','  channel labels','  binary format','sub-01_task-demo.vmrk','  stimulus markers']},
 BIDS:{title:'EEG-BIDS',ext:'folder',kind:'struktura danych',desc:'BIDS nie zastępuje EDF/BDF/BrainVision. Definiuje organizację datasetu, nazewnictwo i pliki metadanych, a surowy EEG pozostaje w obsługiwanym formacie.',tree:['dataset_description.json','participants.tsv','sub-01/','  eeg/','    sub-01_task-demo_eeg.edf','    sub-01_task-demo_eeg.json','    sub-01_task-demo_channels.tsv','    sub-01_task-demo_events.tsv']}
};
function buildFiles(){const m=document.createElement('section');m.id='mfiles';m.className='module';m.innerHTML=head('Zapis sygnału EEG i organizacja danych','Porównuj formaty rekordów EEG oraz strukturę BIDS. Po lewej i prawej stronie możesz niezależnie wybrać format. Przykładowe dane są generowane w przeglądarce i można je pobrać.','ZAPIS DANYCH')+`<div class="compare-toolbar"><label>Lewy format <select id="fmtL">${Object.keys(FORMATS).map(k=>`<option ${k==='EDF'?'selected':''}>${k}</option>`).join('')}</select></label><button class="btn" id="swapfmt">⇄ Zamień</button><label>Prawy format <select id="fmtR">${Object.keys(FORMATS).map(k=>`<option ${k==='BIDS'?'selected':''}>${k}</option>`).join('')}</select></label></div><div class="format-compare"><div class="panel format-panel" id="formatL"></div><div class="panel format-panel" id="formatR"></div></div><div class="panel" style="margin-top:14px"><h2><span class="dot"></span>Pobierz przykładowe dane</h2><div class="row"><button class="btn primary" id="downloadEDF">Pobierz demo.edf</button><button class="btn" id="downloadTSV">Pobierz BIDS *_eeg.tsv</button><button class="btn" id="downloadJSON">Pobierz BIDS *_eeg.json</button></div><div class="readout" style="margin-top:10px">Plik EDF jest generowany jako minimalny rekord wielokanałowy 16-bit z 19 kanałami 10–20. Pliki BIDS TSV/JSON są dydaktycznym eksportem danych i metadanych.</div></div>`;$('#main').appendChild(m);function render(){renderFormat('formatL',$('#fmtL',m).value);renderFormat('formatR',$('#fmtR',m).value)}$('#fmtL',m).onchange=render;$('#fmtR',m).onchange=render;$('#swapfmt',m).onclick=()=>{const a=$('#fmtL',m).value;$('#fmtL',m).value=$('#fmtR',m).value;$('#fmtR',m).value=a;render()};$('#downloadEDF',m).onclick=downloadEDF;$('#downloadTSV',m).onclick=downloadTSV;$('#downloadJSON',m).onclick=downloadBidsJSON;render()}
function renderFormat(id,key){const f=FORMATS[key],e=$('#'+id);e.innerHTML=`<div class="format-head"><div><span class="file-badge">${f.ext}</span><h2>${f.title}</h2></div><small>${f.kind}</small></div><p>${f.desc}</p><pre class="file-tree">${f.tree.join('\n')}</pre>`}
function ascii(view,off,len,text){const s=String(text).padEnd(len,' ').slice(0,len);for(let i=0;i<len;i++)view.setUint8(off+i,s.charCodeAt(i));return off+len}
function makeEDF(){const fs=eng.fs,sec=4,data=eng.generate(sec),ids=ELECTRODES.map(e=>e.id),ns=ids.length,header=256+ns*256,records=sec,total=header+records*ns*fs*2,buf=new ArrayBuffer(total),v=new DataView(buf);let o=0;o=ascii(v,o,8,'0');o=ascii(v,o,80,'X X X X');o=ascii(v,o,80,'Startdate X');const now=new Date(),dd=String(now.getDate()).padStart(2,'0'),mm=String(now.getMonth()+1).padStart(2,'0'),yy=String(now.getFullYear()%100).padStart(2,'0'),hh=String(now.getHours()).padStart(2,'0'),mi=String(now.getMinutes()).padStart(2,'0'),ss=String(now.getSeconds()).padStart(2,'0');o=ascii(v,o,8,`${dd}.${mm}.${yy}`);o=ascii(v,o,8,`${hh}.${mi}.${ss}`);o=ascii(v,o,8,String(header));o=ascii(v,o,44,'EDF+C');o=ascii(v,o,8,String(records));o=ascii(v,o,8,'1');o=ascii(v,o,4,String(ns));const fields=[[16,id=>id],[80,()=> 'EEG electrode'],[8,()=> 'uV'],[8,()=> '-200'],[8,()=> '200'],[8,()=> '-32768'],[8,()=> '32767'],[80,()=> 'HP:0.1Hz LP:70Hz'],[8,()=> String(fs)],[32,()=> '']];for(const [len,fn] of fields)for(const id of ids)o=ascii(v,o,len,fn(id));let pos=header;for(let r=0;r<records;r++)for(const id of ids)for(let i=0;i<fs;i++){const uv=clamp(data[id][r*fs+i],-200,200),dig=Math.round(uv/200*32767);v.setInt16(pos,dig,true);pos+=2}return new Blob([buf],{type:'application/octet-stream'})}
function save(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function downloadEDF(){save(makeEDF(),'sub-01_task-demo_eeg.edf')}
function downloadTSV(){const d=eng.generate(4),ids=ELECTRODES.map(e=>e.id),rows=['time\t'+ids.join('\t')];for(let i=0;i<4*eng.fs;i++)rows.push((i/eng.fs).toFixed(4)+'\t'+ids.map(id=>d[id][i].toFixed(3)).join('\t'));save(new Blob([rows.join('\n')],{type:'text/tab-separated-values'}),'sub-01_task-demo_eeg.tsv')}
function downloadBidsJSON(){const meta={TaskName:'demo',SamplingFrequency:eng.fs,PowerLineFrequency:50,EEGReference:eng.reference,EEGChannelCount:ELECTRODES.length,RecordingType:'continuous',SoftwareFilters:'n/a',Note:'Synthetic educational dataset generated by EEG-Lab.'};save(new Blob([JSON.stringify(meta,null,2)],{type:'application/json'}),'sub-01_task-demo_eeg.json')}

let live={stream:null,landmarker:null,running:false,raf:0,earBase:null,closed:false,lastBlink:0,buffO:[],buffF:[],phase:0};
function buildSimLive(){const m=document.createElement('section');m.id='msimlive';m.className='module';m.innerHTML=head('SimLive — wpływ oczu użytkownika na symulowany EEG','Kamera jest analizowana lokalnie w przeglądarce przez MediaPipe Face Landmarker. Zamknięcie oczu zwiększa rytm alfa w O1, a wykryte mrugnięcie dodaje transient EOG w Fp1. Obraz nie jest wysyłany do serwera aplikacji.','SIMLIVE')+`<div class="grid g2"><div><div class="panel"><h2><span class="dot"></span>Kamera i detekcja oczu</h2><div class="video-wrap"><video id="livevideo" autoplay playsinline muted></video><canvas id="liveoverlay" width="640" height="480"></canvas></div><div class="row" style="margin-top:10px"><button class="btn primary" id="livestart">Uruchom kamerę + MediaPipe</button><button class="btn" id="livestop" disabled>Zatrzymaj</button></div><div class="readout" id="livestatus" style="margin-top:10px">Kamera wyłączona. Po uruchomieniu przeglądarka poprosi o zgodę.</div></div><div class="panel"><h2><span class="dot"></span>Stan detektora</h2><div class="live-metrics"><div class="metric"><div class="k">OCZY</div><div class="v" id="eyeState">—</div></div><div class="metric"><div class="k">EAR</div><div class="v" id="earVal">—</div></div><div class="metric"><div class="k">MRUGNIĘCIA</div><div class="v" id="blinkCount">0</div></div></div><div class="callout" style="margin-top:10px">Pierwsze sekundy służą do oszacowania typowego otwarcia oczu. Próg jest adaptacyjny, dlatego wynik zależy od pozycji twarzy, oświetlenia i kamery.</div></div></div><div><div class="panel"><h2><span class="dot"></span>SimLive EEG — Fp1 i O1</h2><canvas id="liveeeg" width="950" height="420"></canvas><div class="legend"><span><i class="swatch" style="background:var(--danger)"></i>Fp1 — EOG/mrugnięcie</span><span><i class="swatch" style="background:var(--accent)"></i>O1 — alfa / oczy zamknięte</span></div></div><div class="panel"><h2><span class="dot"></span>Co jest mapowane?</h2><table><thead><tr><th>Detekcja</th><th>Zmiana w symulacji</th></tr></thead><tbody><tr><td>Oczy otwarte</td><td>niższa amplituda alfa O1</td></tr><tr><td>Oczy zamknięte</td><td>wzrost amplitudy 8–13 Hz O1</td></tr><tr><td>Mrugnięcie</td><td>krótki dodatni transient EOG Fp1</td></tr></tbody></table></div></div></div>`;$('#main').appendChild(m);$('#livestart',m).onclick=startLive;$('#livestop',m).onclick=stopLive;seedLive();drawSimLive()}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function eyeEAR(lm,idx){const [p1,p2,p3,p4,p5,p6]=idx.map(i=>lm[i]);return(dist(p2,p6)+dist(p3,p5))/(2*dist(p1,p4))}
async function startLive(){const m=$('#msimlive'),status=$('#livestatus',m),video=$('#livevideo',m);try{status.textContent='Ładowanie MediaPipe…';const mp=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/+esm');const vision=await mp.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm');live.landmarker=await mp.FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task'},runningMode:'VIDEO',numFaces:1,minFaceDetectionConfidence:.5,minTrackingConfidence:.5});live.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});video.srcObject=live.stream;await video.play();live.running=true;live.earBase=null;live.closed=false;$('#livestart',m).disabled=true;$('#livestop',m).disabled=false;status.textContent='MediaPipe działa lokalnie. Patrz naturalnie w kamerę przez kilka sekund — trwa kalibracja otwartych oczu.';liveLoop()}catch(err){status.innerHTML=`<span class="bad">Nie udało się uruchomić SimLive:</span> ${String(err.message||err)}`;stopLive()}}
function stopLive(){live.running=false;cancelAnimationFrame(live.raf);live.stream?.getTracks().forEach(t=>t.stop());live.stream=null;live.landmarker?.close?.();live.landmarker=null;const m=$('#msimlive');if(m){$('#livestart',m).disabled=false;$('#livestop',m).disabled=true;$('#livestatus',m).textContent='Kamera wyłączona.'}}
let blinkCounter=0;
function liveLoop(){if(!live.running)return;const m=$('#msimlive'),video=$('#livevideo',m);if(video.readyState>=2){const res=live.landmarker.detectForVideo(video,performance.now());const lm=res.faceLandmarks?.[0];if(lm){const left=eyeEAR(lm,[33,160,158,133,153,144]),right=eyeEAR(lm,[362,385,387,263,373,380]),ear=(left+right)/2;if(live.earBase===null)live.earBase=ear;else if(!live.closed)live.earBase=.98*live.earBase+.02*ear;const threshold=live.earBase*.62,was=live.closed;live.closed=ear<threshold;$('#earVal',m).textContent=ear.toFixed(3);$('#eyeState',m).textContent=live.closed?'zamknięte':'otwarte';if(was&&!live.closed&&performance.now()-live.lastBlink>180){live.lastBlink=performance.now();blinkCounter++;$('#blinkCount',m).textContent=blinkCounter;addBlink()}$('#livestatus',m).innerHTML=`Twarz wykryta · próg EAR <b>${threshold.toFixed(3)}</b> · stan wpływa na generator EEG.`;drawEyeOverlay(lm)}else{$('#eyeState',m).textContent='brak twarzy';$('#livestatus',m).textContent='Nie wykryto twarzy — ustaw twarz na wprost kamery.'}}updateLiveSignal();drawSimLive();live.raf=requestAnimationFrame(liveLoop)}
function drawEyeOverlay(lm){const m=$('#msimlive'),cv=$('#liveoverlay',m),video=$('#livevideo',m),ctx=cv.getContext('2d');cv.width=video.videoWidth||640;cv.height=video.videoHeight||480;ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle=live.closed?'#b53e35':'#087f70';[33,133,160,158,153,144,362,263,385,387,373,380].forEach(i=>{ctx.beginPath();ctx.arc((1-lm[i].x)*cv.width,lm[i].y*cv.height,3,0,Math.PI*2);ctx.fill()})}
function seedLive(){live.buffO=new Array(750).fill(0);live.buffF=new Array(750).fill(0)}
function addBlink(){for(let k=0;k<55;k++){const idx=live.buffF.length-1-k;if(idx>=0)live.buffF[idx]+=95*Math.exp(-((k-22)**2)/(2*9**2))}}
function updateLiveSignal(){const fs=250,batch=5;for(let k=0;k<batch;k++){live.phase+=1/fs;const t=live.phase,alpha=(live.closed?28:8)*Math.sin(2*Math.PI*10*t),base=5*Math.sin(2*Math.PI*6*t)+rand(-4,4);live.buffO.push(alpha+base);live.buffF.push(6*Math.sin(2*Math.PI*18*t)+rand(-5,5));live.buffO.shift();live.buffF.shift()}}
function drawSimLive(){const m=$('#msimlive');if(!m)return;const cv=$('#liveeeg',m),ctx=cv.getContext('2d'),c=col();axes(ctx,cv.width,cv.height,'3 s');ctx.fillStyle=c.muted;ctx.fillText('Fp1',8,120);ctx.fillText('O1',8,300);const draw=(a,mid,color)=>{ctx.strokeStyle=color;ctx.lineWidth=1.6;ctx.beginPath();a.forEach((v,i)=>{const x=48+i/(a.length-1)*(cv.width-62),y=mid-clamp(v,-100,100)/100*115;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()};draw(live.buffF,115,c.danger);draw(live.buffO,295,c.accent)}

function init(){
 buildEnhancedSignal();buildFFT();buildPost();buildFiles();buildSimLive();
 const old4=$('#m4');if(old4){old4.querySelector('.eyebrow')?.replaceChildren('ARCHIWALNY MODUŁ ANALIZY');old4.classList.add('hidden')}
 rebuildNav();showModule('m0');
}
window.addEventListener('load',init,{once:true});
window.addEventListener('beforeunload',stopLive);
