const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const QUESTIONS=[
 {cat:'Rytmy EEG',q:'W odprowadzeniach O1 i O2 po zamknięciu oczu wzrasta moc oscylacji około 10 Hz. Któremu rytmowi EEG odpowiada taki wzorzec?',o:['Rytm delta','Rytm theta','Rytm alfa','Rytm beta'],a:2,e:'Rytm alfa obejmuje zwykle zakres 8–13 Hz i w spoczynku jest najsilniejszy w okolicach potylicznych przy zamkniętych oczach.'},
 {cat:'Artefakty',q:'W odprowadzeniach czołowych pojawia się wolna, wysokonapięciowa defleksja zsynchronizowana z mrugnięciem. Jakie jest najbardziej prawdopodobne źródło tego sygnału?',o:['Aktywność mięśni żwaczy (EMG)','Potencjał okoruchowy związany z mrugnięciem (EOG)','Zakłócenie sieciowe 50 Hz','Składowa P300'],a:1,e:'Mrugnięcie powoduje zmianę potencjału rejestrowaną jako artefakt EOG, zwykle o największej amplitudzie w odprowadzeniach czołowych.'},
 {cat:'Artefakty',q:'Podczas zaciskania szczęki w zapisie narasta szerokopasmowa aktywność wysokoczęstotliwościowa, szczególnie w odprowadzeniach skroniowych. Co jest jej najbardziej prawdopodobnym źródłem?',o:['Rytm alfa','Aktywność mięśniowa (EMG)','Wolny dryf potencjału elektrody','Rytm theta'],a:1,e:'Aktywność mięśniowa ma szerokie widmo częstotliwości i może istotnie zanieczyszczać zwłaszcza zakres beta oraz gamma.'},
 {cat:'Próbkowanie',q:'Sygnał jest próbkowany z częstotliwością 100 Hz, a analizowana składowa ma częstotliwość 70 Hz. Jakie zjawisko wystąpi?',o:['Dryf linii podstawowej','Aliasing, czyli błędne odwzorowanie częstotliwości','Nasycenie toru pomiarowego','Zmiana układu odniesienia'],a:1,e:'Dla częstotliwości próbkowania 100 Hz częstotliwość Nyquista wynosi 50 Hz. Składowa 70 Hz zostanie więc błędnie odwzorowana jako składowa o niższej częstotliwości.'},
 {cat:'Potencjały wywołane',q:'Dlaczego uśrednianie wielu epok poprawia stosunek sygnału do szumu składowej P300?',o:['Wzmacnia wszystkie składowe w jednakowym stopniu','Osłabia aktywność zsynchronizowaną z bodźcem','Aktywność zsynchronizowana czasowo ze zdarzeniem sumuje się zgodnie, natomiast aktywność nieskorelowana ulega częściowemu zniesieniu','Eliminuje potrzebę korekcji linii podstawowej'],a:2,e:'Składowa P300 jest związana czasowo ze zdarzeniem, dlatego jej przebieg sumuje się między próbami bardziej zgodnie niż aktywność nieskorelowana i szum.'},
 {cat:'EEG kliniczne',q:'Czy brak wyładowań padaczkokształtnych w pojedynczym rutynowym badaniu EEG wyklucza rozpoznanie padaczki?',o:['Tak, zawsze','Tak, jeżeli zapis trwał ponad 20 minut','Nie','Tylko u osób dorosłych'],a:2,e:'Prawidłowy rutynowy zapis EEG nie wyklucza padaczki. Wynik EEG interpretuje się łącznie z obrazem klinicznym i pozostałymi danymi diagnostycznymi.'},
 {cat:'EEG kliniczne',q:'Jak należy interpretować podwyższony stosunek mocy theta do beta (TBR) u osoby ocenianej w kierunku ADHD?',o:['Jako samodzielny marker diagnostyczny','Jako wynik wystarczający do potwierdzenia ADHD','Jako potencjalny korelat obserwowany na poziomie grupowym, wymagający interpretacji w szerszym kontekście','Jako równoważnik badania neuropsychologicznego'],a:2,e:'TBR nie jest samodzielnym markerem diagnostycznym ADHD. Korelat obserwowany na poziomie grupowym nie jest równoznaczny z markerem diagnostycznym u pojedynczej osoby.'},
 {cat:'qEEG',q:'Wartość standaryzowana z dla mocy alfa wynosi −2,2 względem bazy normatywnej. Jaki wniosek jest uzasadniony?',o:['Wynik sam w sobie dowodzi patologii','Jest to odchylenie od średniej bazy normatywnej, wymagające oceny jakości danych i kontekstu','Wynik wskazuje lokalizację źródła neuronalnego','Wynik jest niezależny od zastosowanego układu odniesienia'],a:1,e:'Wartość z zależy od procedury przetwarzania, jakości danych, stanu badanego, układu odniesienia oraz właściwości bazy normatywnej.'},
 {cat:'Topografia EEG',q:'Co przedstawia mapa topograficzna cechy qEEG?',o:['Bezpośrednią lokalizację generatorów neuronalnych','Interpolowany przestrzenny rozkład wartości mierzonej cechy na powierzchni głowy','Obraz strukturalny rezonansu magnetycznego','Wyłącznie impedancję elektrod'],a:1,e:'Mapa topograficzna przedstawia interpolowany rozkład wartości zmierzonych w elektrodach. Nie jest bezpośrednią mapą źródeł aktywności neuronalnej.'},
 {cat:'Przetwarzanie wstępne',q:'Dlaczego w analizie EEG należy raportować zastosowany układ odniesienia?',o:['Ponieważ wpływa na wartości potencjałów w poszczególnych kanałach i ich rozkład przestrzenny','Ponieważ zmienia anatomię mózgu','Ponieważ zwiększa fizyczną amplitudę źródła neuronalnego','Ponieważ zastępuje filtrację sygnału'],a:0,e:'EEG rejestruje różnice potencjałów. Wybór układu odniesienia wpływa więc na wartości kanałów oraz na obserwowaną topografię napięcia.'},
 {cat:'Analiza widmowa',q:'Jak wydłużenie analizowanego odcinka sygnału wpływa na rozdzielczość częstotliwościową dyskretnej transformaty Fouriera?',o:['Pogarsza ją','Poprawia ją','Nie wpływa na nią','Zależy wyłącznie od liczby elektrod'],a:1,e:'Odstęp między kolejnymi częstotliwościami widma jest w przybliżeniu równy 1/T, dlatego dłuższy odcinek sygnału zapewnia drobniejszą rozdzielczość częstotliwościową.'},
 {cat:'EEG kliniczne',q:'Jaki kierunek zmian w spoczynkowym EEG jest często opisywany w chorobie Alzheimera i części innych zespołów otępiennych?',o:['Przesunięcie mocy ku wyższym częstotliwościom z dominacją gamma','Spowolnienie czynności podstawowej: większy udział theta i delta oraz osłabienie lub zwolnienie rytmu alfa','Stała aktywność 50 Hz','Wyłącznie wzrost mocy beta'],a:1,e:'W wielu zespołach otępiennych opisuje się spowolnienie czynności podstawowej EEG, jednak jego nasilenie i charakter zależą od etiologii oraz stadium choroby.'}
];
const quiz={i:0,correct:0,wrong:0,answered:false,order:QUESTIONS.map((_,i)=>i)};
function current(){return QUESTIONS[quiz.order[quiz.i]]}
function render(){const m=$('#mquiz');if(!m)return;const q=current();$('#testcat',m).textContent=q.cat;$('#testpos',m).textContent=`${quiz.i+1}/${quiz.order.length}`;$('#testq',m).textContent=q.q;$('#testanswers',m).innerHTML=q.o.map((x,i)=>`<button class="test-answer" data-answer="${i}"><span>${String.fromCharCode(65+i)}</span><b>${x}</b></button>`).join('');$('#testfeedback',m).className='test-feedback hidden';$('#testfeedback',m).textContent='';$('#testnext',m).disabled=true;$('#testcorrect',m).textContent=quiz.correct;$('#testwrong',m).textContent=quiz.wrong;$('#testnumber',m).textContent=quiz.i+1;quiz.answered=false;$$('[data-answer]',m).forEach(b=>b.onclick=()=>answer(+b.dataset.answer))}
function answer(i){if(quiz.answered)return;quiz.answered=true;const m=$('#mquiz'),q=current(),ok=i===q.a;if(ok)quiz.correct++;else quiz.wrong++;$$('[data-answer]',m).forEach((b,j)=>{b.disabled=true;b.classList.toggle('correct',j===q.a);b.classList.toggle('wrong',j===i&&!ok)});const f=$('#testfeedback',m);f.className='test-feedback '+(ok?'ok':'bad');f.innerHTML=`<b>${ok?'Poprawna odpowiedź.':'Niepoprawna odpowiedź.'}</b> ${q.e}`;$('#testnext',m).disabled=false;$('#testcorrect',m).textContent=quiz.correct;$('#testwrong',m).textContent=quiz.wrong}
function next(){quiz.i=(quiz.i+1)%quiz.order.length;render()}
function reset(){quiz.i=0;quiz.correct=0;quiz.wrong=0;quiz.answered=false;quiz.order=QUESTIONS.map((_,i)=>i);render()}
function shuffle(){quiz.order.sort(()=>Math.random()-.5);quiz.i=0;quiz.correct=0;quiz.wrong=0;render()}
function build(){const m=document.createElement('section');m.id='mquiz';m.className='module';m.innerHTML=`<div class="head"><div><div class="eyebrow">SPRAWDŹ SIĘ</div><h1>Sprawdź się — pytania jednokrotnego wyboru</h1><p>Wybierz jedną poprawną odpowiedź. Po udzieleniu odpowiedzi otrzymasz krótkie wyjaśnienie.</p></div></div><div class="test-layout"><div class="panel test-main"><div class="flash-meta"><span id="testcat"></span><span id="testpos"></span></div><div class="test-question" id="testq"></div><div class="test-answers" id="testanswers"></div><div class="test-feedback hidden" id="testfeedback"></div><div class="row" style="margin-top:14px"><button class="btn primary" id="testnext" disabled>Następne pytanie</button></div></div><div><div class="panel"><h2><span class="dot"></span>Wynik</h2><div class="score-box"><div class="metric"><div class="k">POPRAWNE</div><div class="v" id="testcorrect">0</div></div><div class="metric"><div class="k">BŁĘDNE</div><div class="v" id="testwrong">0</div></div><div class="metric"><div class="k">PYTANIE</div><div class="v" id="testnumber">1</div></div></div><div class="row" style="margin-top:10px"><button class="btn" id="testshuffle">Losuj kolejność</button><button class="btn" id="testreset">Reset</button></div></div></div></div>`;$('#main').appendChild(m);$('#testnext',m).onclick=next;$('#testreset',m).onclick=reset;$('#testshuffle',m).onclick=shuffle;render()}
window.addEventListener('load',build,{once:true});