import{rand}from'./signal.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const css=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const C=()=>({accent:css('--accent'),muted:css('--muted'),line:css('--line')});
function axes(ctx,w,h,xlabel=''){const c=C();ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.strokeStyle=c.line;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(38,i*h/5);ctx.lineTo(w-8,i*h/5);ctx.stroke()}ctx.fillStyle=c.muted;ctx.font='10px IBM Plex Mono';if(xlabel)ctx.fillText(xlabel,w-62,h-7)}
function plot(ctx,a,x0,y0,w,h,min,max,color){ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();a.forEach((v,i)=>{const x=x0+i/Math.max(a.length-1,1)*w,y=y0+h-(v-min)/(max-min)*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function head(title,desc,label){return`<div class="head"><div><div class="eyebrow">${label}</div><h1>${title}</h1><p>${desc}</p></div></div>`}
const CARDS=[
 {cat:'Pasma',q:'W zapisie O1/O2 po zamknięciu oczu wyraźnie wzrasta rytm około 10 Hz. Jakie pasmo obserwujesz?',a:'Rytm alfa, typowo 8–13 Hz. Klasyczny posterior dominant rhythm nasila się przy zamkniętych oczach.',sig:'alpha'},
 {cat:'Artefakty',q:'Duży wolny dodatni transient dominuje w Fp1/Fp2 i pojawia się równocześnie z zamknięciem powiek. Co to najpewniej?',a:'Artefakt mrugnięcia / EOG. Jego topografia jest zwykle silnie czołowa.',sig:'blink'},
 {cat:'Artefakty',q:'Szerokopasmowa szybka aktywność narasta podczas zaciskania szczęki, szczególnie skroniowo. Co to?',a:'EMG mięśni twarzy/żwaczy. Może szczególnie zanieczyszczać beta i gamma.',sig:'emg'},
 {cat:'Próbkowanie',q:'Przy fs = 100 Hz próbujesz analizować składową 70 Hz. Jaki problem wystąpi?',a:'Aliasing. Nyquist wynosi 50 Hz, więc 70 Hz zostanie odwzorowane jako niższa częstotliwość.',sig:'concept'},
 {cat:'ERP',q:'Dlaczego uśrednianie wielu epok może poprawić widoczność P300?',a:'Składowa związana czasowo z bodźcem sumuje się zgodnie, a część losowego szumu i nieskorelowanej aktywności ulega redukcji.',sig:'erp'},
 {cat:'Kliniczne',q:'Czy brak wyładowań padaczkowych w pojedynczym rutynowym EEG wyklucza padaczkę?',a:'Nie. Rozpoznanie jest kliniczne, a czułość EEG rośnie m.in. przy powtórzeniach i zapisie snu.',sig:'spike'},
 {cat:'Kliniczne',q:'Czy zwiększony theta/beta ratio może sam potwierdzić ADHD?',a:'Nie. Nie powinien zastępować standardowej oceny klinicznej ani służyć do samodzielnego potwierdzania ADHD.',sig:'tbr'},
 {cat:'qEEG',q:'Z-score alfa = −2.2 w bazie normatywnej. Czy oznacza to automatycznie patologię?',a:'Nie. Wynik zależy m.in. od jakości danych, wieku, stanu, montażu, referencji i bazy normatywnej.',sig:'concept'},
 {cat:'Topografia',q:'Czy qEEG HeatMap pokazuje miejsce źródła neuronalnego?',a:'Nie. Topomap interpoluje wartości zmierzone na skórze głowy. Lokalizacja źródeł wymaga rozwiązania zagadnienia odwrotnego.',sig:'concept'},
 {cat:'PreProcessing',q:'Po co zmienia się referencję EEG?',a:'EEG mierzy różnice potencjałów. Wybór referencji zmienia reprezentację napięć i może wpływać na topografię, dlatego musi być raportowany.',sig:'concept'},
 {cat:'FFT',q:'Co dzieje się z rozdzielczością częstotliwościową FFT, gdy wydłużasz analizowane okno?',a:'Poprawia się — odstęp częstotliwościowy jest w przybliżeniu równy 1/T.',sig:'concept'},
 {cat:'Otępienia',q:'Jaki kierunek zmian spoczynkowego EEG jest często opisywany w otępieniach typu Alzheimer/DLB?',a:'Spowolnienie widma: słabszy lub wolniejszy tylny alfa oraz większy udział theta/delta; szczegóły zależą od etiologii i stadium.',sig:'slow'}
];
const quiz={i:0,good:0,bad:0,order:CARDS.map((_,i)=>i)};
function signal(type){const n=900,a=[];for(let i=0;i<n;i++){const t=i/180;let v=rand(-2,2)+4*Math.sin(2*Math.PI*6*t);if(type==='alpha')v+=18*Math.sin(2*Math.PI*10*t);if(type==='blink')v+=70*Math.exp(-((t-2.1)**2)/(2*.12**2));if(type==='emg')v+=rand(-18,18)*Math.sin(2*Math.PI*42*t);if(type==='spike')v+=75*Math.exp(-((t-2.4)**2)/(2*.015**2))-25*Math.exp(-((t-2.47)**2)/(2*.04**2));if(type==='slow')v+=14*Math.sin(2*Math.PI*3*t);if(type==='erp')v+=18*Math.exp(-((t-2.8)**2)/(2*.18**2));if(type==='tbr')v+=14*Math.sin(2*Math.PI*6*t)+5*Math.sin(2*Math.PI*20*t);a.push(v)}return a}
function next(){quiz.i=(quiz.i+1)%quiz.order.length;render()}
function render(){const m=$('#mquiz');if(!m)return;const d=CARDS[quiz.order[quiz.i]];$('#flashcat',m).textContent=d.cat;$('#flashpos',m).textContent=`${quiz.i+1}/${quiz.order.length}`;$('#flashq',m).textContent=d.q;$('#flasha',m).textContent=d.a;$('#flasha',m).classList.add('hidden');$('#qgood',m).textContent=quiz.good;$('#qbad',m).textContent=quiz.bad;$('#qnum',m).textContent=quiz.i+1;$('#flashlist',m).innerHTML=quiz.order.map((j,i)=>`<button class="btn ${i===quiz.i?'on':''}" data-flash="${i}">${i+1}. ${CARDS[j].cat}</button>`).join('');$$('[data-flash]',m).forEach(b=>b.onclick=()=>{quiz.i=+b.dataset.flash;render()});const cv=$('#flashcv',m),ctx=cv.getContext('2d'),c=C();axes(ctx,cv.width,cv.height,'przykład');if(d.sig!=='concept')plot(ctx,signal(d.sig),42,12,cv.width-55,cv.height-42,-90,90,c.accent);else{ctx.fillStyle=c.muted;ctx.font='14px IBM Plex Mono';ctx.textAlign='center';ctx.fillText('Karta koncepcyjna — odpowiedz bez wykresu',cv.width/2,cv.height/2)}}
function build(){const m=document.createElement('section');m.id='mquiz';m.className='module';m.innerHTML=head('Sprawdź się — Flash cards','Pytania obejmują pasma, artefakty, FFT, preprocessing, qEEG oraz interpretację kliniczną. Część kart zawiera syntetyczny przykład sygnału.','SPRAWDŹ SIĘ')+`<div class="flash-shell"><div class="panel flash-card"><div class="flash-meta"><span id="flashcat"></span><span id="flashpos"></span></div><div class="flash-question" id="flashq"></div><canvas class="flash-signal" id="flashcv" width="900" height="240"></canvas><div class="flash-answer hidden" id="flasha"></div><div class="row" style="margin-top:12px"><button class="btn primary" id="flashshow">Pokaż odpowiedź</button><button class="btn" id="flashgood">✓ Wiedziałam/em</button><button class="btn" id="flashbad">✕ Powtórzę</button><button class="btn" id="flashnext">Następna</button></div></div><div><div class="panel"><h2><span class="dot"></span>Wynik</h2><div class="score-box"><div class="metric"><div class="k">DOBRZE</div><div class="v" id="qgood">0</div></div><div class="metric"><div class="k">DO POWTÓRKI</div><div class="v" id="qbad">0</div></div><div class="metric"><div class="k">KARTA</div><div class="v" id="qnum">1</div></div></div><div class="row" style="margin-top:10px"><button class="btn" id="qshuffle">Losuj kolejność</button><button class="btn" id="qreset">Reset</button></div></div><div class="panel"><h2><span class="dot"></span>Zestaw</h2><div class="flash-list" id="flashlist"></div></div></div></div>`;$('#main').appendChild(m);$('#flashshow',m).onclick=()=>$('#flasha',m).classList.remove('hidden');$('#flashgood',m).onclick=()=>{quiz.good++;next()};$('#flashbad',m).onclick=()=>{quiz.bad++;next()};$('#flashnext',m).onclick=next;$('#qshuffle',m).onclick=()=>{quiz.order.sort(()=>Math.random()-.5);quiz.i=0;render()};$('#qreset',m).onclick=()=>{quiz.i=0;quiz.good=0;quiz.bad=0;quiz.order=CARDS.map((_,i)=>i);render()};render()}
window.addEventListener('load',build,{once:true});
