const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const QUESTIONS=[
 {cat:'Pasma',q:'W zapisie O1/O2 po zamknięciu oczu wyraźnie wzrasta rytm około 10 Hz. Które pasmo jest najbardziej prawdopodobne?',o:['Delta','Theta','Alfa','Beta'],a:2,e:'Rytm alfa ma zwykle około 8–13 Hz i typowo nasila się potylicznie przy zamkniętych oczach.'},
 {cat:'Artefakty',q:'Duży wolny transient dominuje w kanałach czołowych i pojawia się równocześnie z mrugnięciem. Co jest najbardziej prawdopodobnym źródłem?',o:['EMG żwaczy','EOG / mrugnięcie','Zakłócenie 50 Hz','P300'],a:1,e:'Mrugnięcia generują silny wolny artefakt EOG, zwykle największy w kanałach czołowych.'},
 {cat:'Artefakty',q:'Szerokopasmowa szybka aktywność narasta podczas zaciskania szczęki. Co najpewniej obserwujesz?',o:['Alfa potyliczne','EMG mięśni twarzy','Dryf elektrody','Theta czołową'],a:1,e:'Aktywność mięśniowa jest szerokopasmowa i może silnie zanieczyszczać zwłaszcza zakres beta/gamma.'},
 {cat:'Próbkowanie',q:'Przy fs = 100 Hz próbujesz analizować składową 70 Hz. Jaki problem wystąpi?',o:['Baseline drift','Aliasing','Clipping','Rereferencja'],a:1,e:'Częstotliwość Nyquista wynosi 50 Hz, więc 70 Hz zostanie odwzorowane jako niższa częstotliwość.'},
 {cat:'ERP',q:'Dlaczego uśrednianie wielu epok zwiększa widoczność P300?',o:['Wzmacnia każdą składową jednakowo','Redukuje aktywność związaną czasowo z bodźcem','Składowa time-locked sumuje się zgodnie, a część losowego szumu się redukuje','Usuwa konieczność baseline correction'],a:2,e:'ERP związany czasowo z bodźcem zachowuje się między próbami bardziej zgodnie niż nieskorelowany szum.'},
 {cat:'Kliniczne',q:'Czy brak wyładowań epileptiformnych w pojedynczym rutynowym EEG wyklucza padaczkę?',o:['Tak, zawsze','Tak, jeśli zapis trwał >20 min','Nie','Tylko u dorosłych'],a:2,e:'Prawidłowy rutynowy zapis EEG nie wyklucza padaczki; EEG jest elementem szerszej oceny klinicznej.'},
 {cat:'Kliniczne',q:'Jak należy traktować podwyższony theta/beta ratio w ADHD?',o:['Jako samodzielny marker diagnostyczny','Jako wynik, który sam potwierdza ADHD','Jako potencjalny korelat grupowy wymagający kontekstu','Jako odpowiednik testu neuropsychologicznego'],a:2,e:'TBR nie powinien samodzielnie potwierdzać ADHD. Korelat grupowy nie jest automatycznie markerem diagnostycznym.'},
 {cat:'qEEG',q:'Z-score alfa = −2.2 w bazie normatywnej. Co można bezpiecznie powiedzieć?',o:['To automatycznie oznacza patologię','To odchylenie od średniej bazy, wymagające kontroli jakości i kontekstu','To dowód lokalizacji źródła','To wynik niezależny od referencji'],a:1,e:'Z-score zależy od pipeline, jakości danych, stanu badanego, referencji i właściwości bazy normatywnej.'},
 {cat:'Topografia',q:'Co pokazuje qEEG HeatMap?',o:['Bezpośrednią lokalizację generatorów neuronalnych','Interpolowany przestrzenny rozkład cechy mierzonej na skalpie','Obraz MRI','Wyłącznie impedancję elektrod'],a:1,e:'Topomapa pokazuje interpolację wartości między elektrodami na powierzchni głowy; nie jest rozwiązaniem problemu odwrotnego.'},
 {cat:'Preprocessing',q:'Dlaczego wybór referencji EEG musi być raportowany?',o:['Bo zmienia reprezentację potencjałów między kanałami','Bo zmienia anatomię mózgu','Bo zwiększa fizycznie amplitudę generatora','Bo zastępuje filtrację'],a:0,e:'EEG mierzy różnice potencjałów. Referencja wpływa na wartości kanałów i topografię.'},
 {cat:'FFT',q:'Co dzieje się z rozdzielczością częstotliwościową FFT, gdy wydłużasz analizowane okno?',o:['Pogarsza się','Poprawia się','Nie zmienia się','Zależy wyłącznie od liczby elektrod'],a:1,e:'Odstęp częstotliwościowy jest w przybliżeniu równy 1/T, więc dłuższe okno daje drobniejszą rozdzielczość.'},
 {cat:'Otępienia',q:'Jaki kierunek zmian spoczynkowego EEG jest często opisywany w chorobie Alzheimera i części innych otępień?',o:['Przyspieszenie widma do gamma','Spowolnienie: więcej theta/delta i słabszy lub wolniejszy alfa','Stałe 50 Hz','Wyłącznie wzrost beta'],a:1,e:'Często opisuje się spowolnienie widma, ale jego zakres zależy od etiologii i stadium.'}
];
const quiz={i:0,correct:0,wrong:0,answered:false,order:QUESTIONS.map((_,i)=>i)};
function current(){return QUESTIONS[quiz.order[quiz.i]]}
function render(){const m=$('#mquiz');if(!m)return;const q=current();$('#testcat',m).textContent=q.cat;$('#testpos',m).textContent=`${quiz.i+1}/${quiz.order.length}`;$('#testq',m).textContent=q.q;$('#testanswers',m).innerHTML=q.o.map((x,i)=>`<button class="test-answer" data-answer="${i}"><span>${String.fromCharCode(65+i)}</span><b>${x}</b></button>`).join('');$('#testfeedback',m).className='test-feedback hidden';$('#testfeedback',m).textContent='';$('#testnext',m).disabled=true;$('#testcorrect',m).textContent=quiz.correct;$('#testwrong',m).textContent=quiz.wrong;$('#testnumber',m).textContent=quiz.i+1;quiz.answered=false;$$('[data-answer]',m).forEach(b=>b.onclick=()=>answer(+b.dataset.answer))}
function answer(i){if(quiz.answered)return;quiz.answered=true;const m=$('#mquiz'),q=current(),ok=i===q.a;if(ok)quiz.correct++;else quiz.wrong++;$$('[data-answer]',m).forEach((b,j)=>{b.disabled=true;b.classList.toggle('correct',j===q.a);b.classList.toggle('wrong',j===i&&!ok)});const f=$('#testfeedback',m);f.className='test-feedback '+(ok?'ok':'bad');f.innerHTML=`<b>${ok?'Poprawna odpowiedź.':'Niepoprawna odpowiedź.'}</b> ${q.e}`;$('#testnext',m).disabled=false;$('#testcorrect',m).textContent=quiz.correct;$('#testwrong',m).textContent=quiz.wrong}
function next(){quiz.i=(quiz.i+1)%quiz.order.length;render()}
function reset(){quiz.i=0;quiz.correct=0;quiz.wrong=0;quiz.answered=false;quiz.order=QUESTIONS.map((_,i)=>i);render()}
function shuffle(){quiz.order.sort(()=>Math.random()-.5);quiz.i=0;quiz.correct=0;quiz.wrong=0;render()}
function build(){const m=document.createElement('section');m.id='mquiz';m.className='module';m.innerHTML=`<div class="head"><div><div class="eyebrow">SPRAWDŹ SIĘ</div><h1>Sprawdź się — test ABCD</h1><p>Wybierz jedną poprawną odpowiedź. Po odpowiedzi otrzymasz krótkie wyjaśnienie.</p></div></div><div class="test-layout"><div class="panel test-main"><div class="flash-meta"><span id="testcat"></span><span id="testpos"></span></div><div class="test-question" id="testq"></div><div class="test-answers" id="testanswers"></div><div class="test-feedback hidden" id="testfeedback"></div><div class="row" style="margin-top:14px"><button class="btn primary" id="testnext" disabled>Następne pytanie</button></div></div><div><div class="panel"><h2><span class="dot"></span>Wynik</h2><div class="score-box"><div class="metric"><div class="k">POPRAWNE</div><div class="v" id="testcorrect">0</div></div><div class="metric"><div class="k">BŁĘDNE</div><div class="v" id="testwrong">0</div></div><div class="metric"><div class="k">PYTANIE</div><div class="v" id="testnumber">1</div></div></div><div class="row" style="margin-top:10px"><button class="btn" id="testshuffle">Losuj kolejność</button><button class="btn" id="testreset">Reset</button></div></div></div></div>`;$('#main').appendChild(m);$('#testnext',m).onclick=next;$('#testreset',m).onclick=reset;$('#testshuffle',m).onclick=shuffle;render()}
window.addEventListener('load',build,{once:true});