import{clamp,rand}from'./signal.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const css=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const C=()=>({accent:css('--accent')||'#087f70',danger:css('--danger')||'#b53e35',warn:css('--warn')||'#a76400',violet:css('--violet')||'#6954b8',muted:css('--muted')||'#5a7077',line:css('--line')||'#d5e0e3',well:css('--well')||'#f0f4f5'});
const STEPS=[['1. Centrowanie','Od każdego kanału odejmuje się średnią, aby dane były skupione wokół zera.'],['2. Whitening','Usuwa się korelacje drugiego rzędu i ujednolica skalę osi.'],['3. W · X','Algorytm wyznacza macierz rozdzielającą W i tworzy kandydatów na niezależne komponenty.'],['4. Ocena IC','Komponent ocenia się na podstawie przebiegu, topografii, widma i związku z EOG/EMG.'],['5. Odrzucenie artefaktów','Usuwa się wyłącznie komponenty dobrze uzasadnione jako artefaktowe.'],['6. Rekonstrukcja','Pozostałe komponenty są mieszane z powrotem do przestrzeni kanałów.']];
function axes(ctx,w,h){const c=C();ctx.clearRect(0,0,w,h);ctx.fillStyle=c.well;ctx.fillRect(0,0,w,h);ctx.strokeStyle=c.line;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(42,i*h/4);ctx.lineTo(w-8,i*h/4);ctx.stroke()}}
function stack(ctx,arrs,names,cols){const c=C(),H=ctx.canvas.height,row=(H-30)/arrs.length;axes(ctx,ctx.canvas.width,H);arrs.forEach((a,k)=>{const mid=10+row*(k+.5);ctx.fillStyle=c.muted;ctx.font='10px IBM Plex Mono';ctx.fillText(names[k],6,mid+3);ctx.strokeStyle=cols[k]||c.accent;ctx.lineWidth=1.4;ctx.beginPath();a.forEach((v,i)=>{const x=44+i/(a.length-1)*(ctx.canvas.width-56),y=mid-clamp(v,-110,110)/110*row*.42;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()})}
function data(){const n=650,src={blink:[],emg:[],alpha:[]};for(let i=0;i<n;i++){const t=i/250;src.blink.push(90*Math.exp(-((t-1.25)**2)/.012)+70*Math.exp(-((t-2.05)**2)/.014));src.emg.push((t>1.55&&t<2.2?1:0)*rand(-32,32));src.alpha.push(18*Math.sin(2*Math.PI*10*t)+rand(-3,3))}const mix=[src.alpha.map((v,i)=>v+.75*src.blink[i]+.25*src.emg[i]),src.alpha.map((v,i)=>.7*v+.2*src.blink[i]+.8*src.emg[i]),src.alpha.map((v,i)=>.45*v+.42*src.blink[i]-.55*src.emg[i])];return{src,mix}}
function draw(){const m=$('#mica');if(!m)return;const {src,mix}=data(),c=C();stack($('#icamix',m).getContext('2d'),mix,['Fz','Cz','Pz'],[c.accent,c.accent,c.accent]);stack($('#icacomp',m).getContext('2d'),[src.blink,src.emg,src.alpha],['IC1 EOG','IC2 EMG','IC3 alfa'],[c.danger,c.warn,c.violet]);const rem=new Set($$('[data-ic]:checked',m).map(x=>x.dataset.ic));const clean=mix.map((ch,j)=>ch.map((v,i)=>v-(rem.has('blink')?[.75,.2,.42][j]*src.blink[i]:0)-(rem.has('emg')?[.25,.8,-.55][j]*src.emg[i]:0)-(rem.has('alpha')?[1,.7,.45][j]*src.alpha[i]:0)));stack($('#icarec',m).getContext('2d'),clean,['Fz','Cz','Pz'],[c.accent,c.accent,c.accent])}
function build(){const m=document.createElement('section');m.id='mica';m.className='module';m.innerHTML=`<div class="head"><div><div class="eyebrow">ICA</div><h1>Analiza składowych niezależnych</h1><p>ICA rozkłada wielokanałowy EEG na możliwie niezależne komponenty, aby rozpoznać m.in. EOG i EMG. Oceń komponenty, usuń tylko dobrze uzasadnione artefakty i sprawdź rekonstrukcję.</p></div></div><div class="ica-step-grid">${STEPS.map(([a,b])=>`<article><strong>${a}</strong><p>${b}</p></article>`).join('')}</div><div class="ica-flow" style="margin-top:14px"><div class="panel"><h2><span class="dot"></span>Sygnały obserwowane X</h2><canvas id="icamix" width="480" height="360"></canvas></div><div class="ica-arrow">→</div><div class="panel"><h2><span class="dot"></span>Komponenty IC</h2><canvas id="icacomp" width="480" height="360"></canvas><div class="ica-components"><label><input type="checkbox" data-ic="blink" checked> usuń IC1 — EOG</label><label><input type="checkbox" data-ic="emg" checked> usuń IC2 — EMG</label><label><input type="checkbox" data-ic="alpha"> usuń IC3 — alfa neuronalna</label></div></div><div class="ica-arrow">→</div><div class="panel"><h2><span class="dot"></span>Rekonstrukcja</h2><canvas id="icarec" width="480" height="360"></canvas><div class="row" style="margin-top:8px"><button class="btn primary" id="icarun">Rekonstruuj</button><button class="btn" id="icanew">Nowy przykład</button></div></div></div><div class="grid g3" style="margin-top:14px"><div class="panel"><h2><span class="dot"></span>Założenia</h2><p class="readout">Źródła powinny być w przybliżeniu niezależne statystycznie i mieszać się liniowo.</p></div><div class="panel"><h2><span class="dot"></span>Ocena artefaktu</h2><p class="readout">Łącz topografię, przebieg czasowy, widmo oraz związek z EOG/EMG.</p></div><div class="panel"><h2><span class="dot"></span>Ryzyko</h2><p class="readout">Usunięcie komponentu neuronalnego bezpowrotnie usuwa część użytecznego sygnału.</p></div></div>`;$('#main').appendChild(m);$('#icarun',m).onclick=draw;$('#icanew',m).onclick=draw;$$('[data-ic]',m).forEach(x=>x.onchange=draw);draw()}
window.addEventListener('load',build,{once:true});
window.addEventListener('eeg:theme',()=>requestAnimationFrame(draw));
window.addEventListener('eeg:module',e=>{if(e.detail==='mica')requestAnimationFrame(draw)});
