import{clamp,rand}from'./signal.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const css=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const C=()=>({accent:css('--accent'),danger:css('--danger'),violet:css('--violet'),warn:css('--warn'),muted:css('--muted'),line:css('--line'),well:css('--well'),text:css('--text')});
const head=(t,d,l)=>`<div class="head"><div><div class="eyebrow">${l}</div><h1>${t}</h1><p>${d}</p></div></div>`;
const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function axes(ctx,w,h,label=''){const c=C();ctx.clearRect(0,0,w,h);ctx.fillStyle=c.well||'#fff';ctx.fillRect(0,0,w,h);ctx.strokeStyle=c.line;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(42,i*h/5);ctx.lineTo(w-8,i*h/5);ctx.stroke()}ctx.fillStyle=c.muted;ctx.font='10px IBM Plex Mono';if(label)ctx.fillText(label,w-65,h-8)}
function trace(ctx,a,mid,scale,color){ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();a.forEach((v,i)=>{const x=48+i/Math.max(a.length-1,1)*(ctx.canvas.width-62),y=mid-v/scale;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function traceRange(ctx,a,min,max,color){const w=ctx.canvas.width,h=ctx.canvas.height,x0=46,y0=14,pw=w-60,ph=h-42;ctx.strokeStyle=color;ctx.lineWidth=1.6;ctx.beginPath();a.forEach((v,i)=>{const x=x0+i/Math.max(a.length-1,1)*pw,y=y0+ph-(clamp(v,min,max)-min)/Math.max(max-min,1e-6)*ph;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
async function faceLandmarker(blend=false){const mp=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/+esm');const vision=await mp.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm');return mp.FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task'},runningMode:'VIDEO',numFaces:1,outputFaceBlendshapes:blend,minFaceDetectionConfidence:.5,minTrackingConfidence:.5})}

const SIM_FS=250,SIM_SECONDS=6,SIM_N=SIM_FS*SIM_SECONDS;
const sim={stream:null,lm:null,running:false,raf:0,lastVideo:-1,lastFrame:0,acc:0,baseEAR:null,closed:false,prevClosed:false,blink:0,blinks:0,muscle:0,t:0,faceBox:null,buf:{Fp1:new Array(SIM_N).fill(0),F7:new Array(SIM_N).fill(0),T7:new Array(SIM_N).fill(0),O1:new Array(SIM_N).fill(0)}};
function ear(lm,ids){const[p1,p2,p3,p4,p5,p6]=ids.map(i=>lm[i]);return(dist(p2,p6)+dist(p3,p5))/(2*Math.max(dist(p1,p4),1e-6))}
function muscleScore(c=[]){const g=n=>c.find(x=>x.categoryName===n)?.score||0;return clamp(.45*g('jawOpen')+.2*Math.max(g('mouthFunnel'),g('mouthPucker'))+.2*Math.max(g('mouthSmileLeft'),g('mouthSmileRight'))+.15*Math.max(g('cheekPuff'),g('browDownLeft'),g('browDownRight')),0,1)}
function buildSim(){const m=document.createElement('section');m.id='msimlive2';m.className='module';m.innerHTML=head('SimLive — oczy i mięśnie twarzy wpływają na EEG','MediaPipe stale analizuje oczy i ruchy twarzy. Zamknięcie oczu zwiększa rytm alfa potyliczny, mrugnięcie dodaje EOG, a ruch ust, żuchwy, policzków i brwi automatycznie zwiększa domieszkę EMG w kanałach czołowo-skroniowych.','SIMLIVE')+`<div class="live-layout simlive-layout"><div><div class="panel sim-camera-panel"><h2><span class="dot"></span>Kamera — automatyczny kadr twarzy</h2><div class="live-video sim-face-preview"><video id="simv" autoplay playsinline muted></video><canvas id="simo" width="360" height="260"></canvas></div><div class="row" style="margin-top:10px"><button class="btn primary" id="sims">Uruchom</button><button class="btn" id="simx" disabled>Zatrzymaj</button></div><div class="readout" id="simst" style="margin-top:10px">Kamera wyłączona. Widoczny jest bazowy syntetyczny EEG.</div><div class="module-note" style="margin-top:10px"><b>Śledzenie EMG twarzy jest zawsze aktywne.</b> Mówienie, ruch żuchwy, policzków i brwi są traktowane jako źródło szerokopasmowego artefaktu mięśniowego.</div></div><div class="live-indicator"><div class="metric"><div class="k">OCZY</div><div class="v" id="sime">—</div></div><div class="metric"><div class="k">MRUGNIĘCIA</div><div class="v" id="simb">0</div></div><div class="metric"><div class="k">EMG TWARZY</div><div class="v" id="simemg">0%</div></div><div class="metric"><div class="k">WPŁYW</div><div class="v" id="simimpact" style="font-size:.82rem">EOG + alfa + EMG</div></div></div></div><div><div class="panel"><h2><span class="dot"></span>EEG na żywo — ${SIM_SECONDS} s</h2><canvas id="simeeg" width="1000" height="460"></canvas><div class="legend"><span>Fp1/F7/T7: EEG z EOG i EMG twarzy</span><span>O1: EEG z modulacją alfa</span></div></div><div class="module-note"><b>Tempo jest rzeczywiste:</b> okno ${SIM_SECONDS} s potrzebuje ${SIM_SECONDS} s, aby przesunąć się przez cały wykres. EMG nie jest osobnym kanałem — modyfikuje istniejący EEG.</div></div></div>`;$('#main').appendChild(m);$('#sims',m).onclick=startSim;$('#simx',m).onclick=stopSim;for(let i=0;i<SIM_N;i++)stepSim(1);drawSim()}
async function startSim(){const m=$('#msimlive2'),v=$('#simv',m),s=$('#simst',m);try{s.textContent='Ładowanie MediaPipe…';sim.lm=await faceLandmarker(true);sim.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});v.srcObject=sim.stream;await v.play();sim.running=true;sim.lastVideo=-1;sim.lastFrame=performance.now();sim.acc=0;sim.baseEAR=null;$('#sims',m).disabled=true;$('#simx',m).disabled=false;s.textContent='Aktywne. MediaPipe śledzi oczy i ruchy twarzy.';simLoop(sim.lastFrame)}catch(e){stopSim();s.textContent='Błąd: '+String(e.message||e)}}
function stopSim(){sim.running=false;cancelAnimationFrame(sim.raf);sim.stream?.getTracks().forEach(t=>t.stop());sim.stream=null;sim.lm?.close?.();sim.lm=null;const m=$('#msimlive2');if(m){$('#sims',m).disabled=false;$('#simx',m).disabled=true;$('#simst',m).textContent='Kamera wyłączona.'}}
function simLoop(now){if(!sim.running)return;const m=$('#msimlive2'),v=$('#simv',m);const dt=Math.min((now-sim.lastFrame)/1000,.1);sim.lastFrame=now;sim.acc+=dt*SIM_FS;const n=Math.floor(sim.acc);if(n>0){stepSim(n);sim.acc-=n}if(v.readyState>=2&&v.currentTime!==sim.lastVideo){sim.lastVideo=v.currentTime;const r=sim.lm.detectForVideo(v,now),lm=r.faceLandmarks?.[0];if(lm){const e=(ear(lm,[33,160,158,133,153,144])+ear(lm,[362,385,387,263,373,380]))/2;sim.baseEAR=sim.baseEAR===null?e:(!sim.closed?.985*sim.baseEAR+.015*e:sim.baseEAR);const th=sim.baseEAR*.62;sim.prevClosed=sim.closed;sim.closed=e<th;if(sim.prevClosed&&!sim.closed){sim.blink=1;sim.blinks++}sim.muscle=.85*sim.muscle+.15*muscleScore(r.faceBlendshapes?.[0]?.categories||[]);$('#sime',m).textContent=sim.closed?'zamknięte':'otwarte';$('#simb',m).textContent=sim.blinks;$('#simemg',m).textContent=Math.round(sim.muscle*100)+'%';$('#simst',m).textContent=`Twarz wykryta · EAR ${e.toFixed(3)} · EMG ${Math.round(sim.muscle*100)}%`;drawFacePreview($('#simo',m),v,lm)}else{$('#simst',m).textContent='Nie wykryto twarzy.';sim.muscle*=.92}}drawSim();sim.raf=requestAnimationFrame(simLoop)}
function stepSim(samples=1){for(let k=0;k<samples;k++){sim.t+=1/SIM_FS;sim.blink*=.965;const t=sim.t,alpha=(sim.closed?29:8)*Math.sin(2*Math.PI*10*t),base=5*Math.sin(2*Math.PI*6*t)+3*Math.sin(2*Math.PI*19*t),eog=85*sim.blink,emg=sim.muscle,fast=()=>rand(-1,1)*(18+38*Math.abs(Math.sin(2*Math.PI*(32+rand(0,20))*t))),vals={Fp1:base+rand(-4,4)+eog+1.3*emg*fast(),F7:.9*base+rand(-4,4)+.55*eog+1.15*emg*fast(),T7:.65*base+rand(-4,4)+1.35*emg*fast(),O1:alpha+5*Math.sin(2*Math.PI*6*t)+rand(-4,4)+.12*emg*fast()};Object.keys(sim.buf).forEach(id=>{sim.buf[id].push(vals[id]);sim.buf[id].shift()})}}
function drawSim(){const m=$('#msimlive2');if(!m)return;const cv=$('#simeeg',m),ctx=cv.getContext('2d'),c=C(),ids=['Fp1','F7','T7','O1'],row=(cv.height-36)/4;axes(ctx,cv.width,cv.height,`${SIM_SECONDS} s`);ids.forEach((id,i)=>{const mid=12+row*(i+.5);ctx.fillStyle=c.muted;ctx.font='10px IBM Plex Mono';ctx.fillText(id,8,mid+3);trace(ctx,sim.buf[id],mid,1.35,c.accent)})}
function faceBounds(lm){let minX=1,minY=1,maxX=0,maxY=0;lm.forEach(p=>{minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y)});return{minX,minY,maxX,maxY}}
function drawFacePreview(cv,v,lm){const vw=v.videoWidth||640,vh=v.videoHeight||480,ctx=cv.getContext('2d'),b=faceBounds(lm),cx=(b.minX+b.maxX)/2*vw,cy=(b.minY+b.maxY)/2*vh,fw=(b.maxX-b.minX)*vw,fh=(b.maxY-b.minY)*vh;const target=.70,srcW=Math.min(vw,Math.max(fw/target,fh/cv.height*cv.width/target)),srcH=srcW*cv.height/cv.width;let sx=clamp(cx-srcW/2,0,Math.max(0,vw-srcW)),sy=clamp(cy-srcH/2,0,Math.max(0,vh-srcH));ctx.save();ctx.clearRect(0,0,cv.width,cv.height);ctx.translate(cv.width,0);ctx.scale(-1,1);ctx.drawImage(v,sx,sy,srcW,srcH,0,0,cv.width,cv.height);ctx.restore();ctx.fillStyle=C().accent;[33,133,362,263,13,14,61,291].forEach(i=>{const p=lm[i];if(!p)return;const x=cv.width-(p.x*vw-sx)/srcW*cv.width,y=(p.y*vh-sy)/srcH*cv.height;if(x<0||x>cv.width||y<0||y>cv.height)return;ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()})}

const PHYS_FS=100,PHYS_SECONDS=10,PHYS_N=PHYS_FS*PHYS_SECONDS;
const stimuli={neutral:{name:'Neutralny',hr:70,eda:4.8,emg:8},cognitive:{name:'Zadanie poznawcze',hr:88,eda:5.8,emg:16},startle:{name:'Nagły bodziec',hr:116,eda:7.2,emg:34},recovery:{name:'Regeneracja',hr:64,eda:4.5,emg:7}};
const phys={k:'neutral',hr:70,eda:4.8,emg:8,t:0,lastFrame:0,acc:0,scr:0,buf:{ecg:new Array(PHYS_N).fill(0),eda:new Array(PHYS_N).fill(4.8),emg:new Array(PHYS_N).fill(0)}};
function buildPhys(){const m=document.createElement('section');m.id='mphys2';m.className='module';m.innerHTML=head('EMG · EKG · GSR','Trzy sygnały fizjologiczne mają różne źródła i czujniki. Wybierz bodziec i obserwuj ich zmianę w rzeczywistym czasie — 10 sekund na osi odpowiada 10 sekundom symulacji.','FIZJOLOGIA OBWODOWA')+`<div class="grid g2"><div><div class="panel"><h2><span class="dot"></span>Co mierzymy?</h2><div class="phys-explain"><article><b>EKG / ECG</b><p>Elektrokardiografia rejestruje różnice potencjałów powstające podczas depolaryzacji i repolaryzacji serca. Mierzy się ją elektrodami skórnymi; z odstępów R–R wyznacza się m.in. HR i HRV.</p></article><article><b>GSR / EDA</b><p>Electrodermal Activity opisuje zmiany przewodnictwa skóry zależne głównie od aktywności gruczołów potowych sterowanych współczulnie. Zwykle mierzy się ją dwiema elektrodami na palcach lub dłoni; jednostką przewodnictwa jest µS.</p></article><article><b>EMG</b><p>Elektromiografia mierzy aktywność elektryczną mięśni. Elektrody powierzchniowe umieszcza się nad brzuścem mięśnia; większe napięcie zwykle zwiększa amplitudę i szerokopasmową energię sygnału.</p></article></div></div><div class="panel"><h2><span class="dot"></span>Bodziec</h2><div class="artifact-grid">${Object.entries(stimuli).map(([k,v])=>`<button class="artifact-card" data-p="${k}"><strong>${v.name}</strong><span>HR ${v.hr} bpm · EDA ${v.eda} µS · EMG ${v.emg} a.u.</span></button>`).join('')}</div></div><div class="live-indicator"><div class="metric"><div class="k">HR</div><div class="v" id="phr">70</div><div class="s">bpm</div></div><div class="metric"><div class="k">EDA</div><div class="v" id="peda">4.8</div><div class="s">µS</div></div><div class="metric"><div class="k">EMG</div><div class="v" id="pemg">8</div><div class="s">a.u.</div></div><div class="metric"><div class="k">BODZIEC</div><div class="v" id="pst" style="font-size:.9rem">Neutralny</div></div></div></div><div><div class="panel"><h2><span class="dot"></span>EKG — ${PHYS_SECONDS} s</h2><canvas id="pecg" width="950" height="180"></canvas><div class="readout">Elektrody skórne → przebieg P–QRS–T → częstość serca i odstępy R–R.</div></div><div class="panel"><h2><span class="dot"></span>GSR / EDA — ${PHYS_SECONDS} s</h2><canvas id="pedaCv" width="950" height="180"></canvas><div class="readout">Przewodnictwo skóry [µS]. Wolniejszy sygnał niż EKG; po bodźcu zmiana rozwija się stopniowo.</div></div><div class="panel"><h2><span class="dot"></span>EMG — ${PHYS_SECONDS} s</h2><canvas id="pemgCv" width="950" height="180"></canvas><div class="readout">Aktywność mięśniowa jest szybka i szerokopasmowa; amplituda rośnie wraz z napięciem mięśnia.</div></div></div></div>`;$('#main').appendChild(m);$$('[data-p]',m).forEach(b=>b.onclick=()=>{phys.k=b.dataset.p;if(b.dataset.p==='startle')phys.scr=1});phys.lastFrame=performance.now();physLoop(phys.lastFrame)}
function physStep(samples){const q=stimuli[phys.k];for(let k=0;k<samples;k++){const dt=1/PHYS_FS;phys.t+=dt;phys.hr+=(q.hr-phys.hr)*dt/1.8;phys.eda+=(q.eda-phys.eda)*dt/2.6;phys.emg+=(q.emg-phys.emg)*dt/.8;phys.scr*=Math.exp(-dt/2.2);const per=60/phys.hr,ph=(phys.t%per)/per;const ecg=100*Math.exp(-((ph-.08)**2)/.00022)-18*Math.exp(-((ph-.045)**2)/.0003)+20*Math.exp(-((ph-.19)**2)/.004)+rand(-1.5,1.5);const eda=phys.eda+1.25*phys.scr*(1-Math.exp(-Math.max(0,phys.t%10)/.7))+0.08*Math.sin(2*Math.PI*.08*phys.t)+rand(-.018,.018);const emg=rand(-phys.emg,phys.emg)*(0.65+0.35*Math.sin(2*Math.PI*31*phys.t));phys.buf.ecg.push(ecg);phys.buf.eda.push(eda);phys.buf.emg.push(emg);Object.values(phys.buf).forEach(a=>a.shift())}}
function physLoop(now){const m=$('#mphys2');if(!m){requestAnimationFrame(physLoop);return}if(!phys.lastFrame)phys.lastFrame=now;const dt=Math.min((now-phys.lastFrame)/1000,.1);phys.lastFrame=now;if(m.classList.contains('active')){phys.acc+=dt*PHYS_FS;const n=Math.floor(phys.acc);if(n>0){physStep(n);phys.acc-=n}const q=stimuli[phys.k],c=C();$('#phr',m).textContent=Math.round(phys.hr);$('#peda',m).textContent=phys.eda.toFixed(2);$('#pemg',m).textContent=Math.round(phys.emg);$('#pst',m).textContent=q.name;const ec=$('#pecg',m),ed=$('#pedaCv',m),em=$('#pemgCv',m);axes(ec.getContext('2d'),ec.width,ec.height,`${PHYS_SECONDS} s`);traceRange(ec.getContext('2d'),phys.buf.ecg,-35,125,c.danger);axes(ed.getContext('2d'),ed.width,ed.height,`${PHYS_SECONDS} s`);traceRange(ed.getContext('2d'),phys.buf.eda,3.5,8.5,c.accent);axes(em.getContext('2d'),em.width,em.height,`${PHYS_SECONDS} s`);traceRange(em.getContext('2d'),phys.buf.emg,-45,45,c.violet)}requestAnimationFrame(physLoop)}

const eye={pts:[],stream:null,lm:null,running:false,raf:0,last:-1,cal:{x:.5,y:.5},raw:{x:.5,y:.5}};
function buildEye(){const m=document.createElement('section');m.id='meye2';m.className='module';m.innerHTML=head('Eye-Tracking','Symuluj ścieżkę wzroku kliknięciami lub użyj MediaPipe do przybliżonego śledzenia spojrzenia z położenia tęczówek.','EYE-TRACKING')+`<div class="grid g2"><div><div class="panel"><h2><span class="dot"></span>Tryb Live</h2><div class="live-video"><video id="eyev" autoplay playsinline muted></video><canvas id="eyeo" width="640" height="480"></canvas></div><div class="row" style="margin-top:10px"><button class="btn primary" id="eyeLiveStart">Uruchom MediaPipe</button><button class="btn" id="eyecal">Kalibruj środek</button><button class="btn" id="eyex" disabled>Zatrzymaj</button></div><div class="readout" id="eyest" style="margin-top:10px">Tryb Live wyłączony.</div></div><div class="panel"><h2><span class="dot"></span>Tryb ręczny</h2><div class="row"><button class="btn" id="eyeclear">Wyczyść</button><button class="btn" id="eyedemo">Symuluj scanpath</button></div></div></div><div><div class="panel"><h2><span class="dot"></span>Scena</h2><div class="eye-stage2" id="eyestage"><div class="eye-target2" style="left:13%;top:18%">A</div><div class="eye-target2" style="left:72%;top:17%">B</div><div class="eye-target2" style="left:43%;top:67%">C</div></div></div></div></div>`;$('#main').appendChild(m);const st=$('#eyestage',m);st.onclick=e=>{const r=st.getBoundingClientRect();eye.pts.push({x:clamp((e.clientX-r.left)/r.width,0,1),y:clamp((e.clientY-r.top)/r.height,0,1)});renderEye()};$('#eyeclear',m).onclick=()=>{eye.pts=[];renderEye()};$('#eyedemo',m).onclick=()=>{eye.pts=[];[[.18,.25],[.22,.28],[.48,.72],[.76,.24],[.51,.69],[.20,.26]].forEach((p,i)=>setTimeout(()=>{eye.pts.push({x:p[0],y:p[1]});renderEye()},i*250))};$('#eyeLiveStart',m).onclick=startEye;$('#eyex',m).onclick=stopEye;$('#eyecal',m).onclick=()=>{eye.cal={...eye.raw};$('#eyest',m).textContent='Środek skalibrowany.'};renderEye()}
function iris(lm,ids){const p=ids.map(i=>lm[i]).filter(Boolean);return{x:mean(p.map(x=>x.x)),y:mean(p.map(x=>x.y))}}
function rawGaze(lm){if(!lm[477])return{x:.5,y:.5};const l=iris(lm,[468,469,470,471,472]),r=iris(lm,[473,474,475,476,477]);return{x:mean([(l.x-lm[33].x)/Math.max(lm[133].x-lm[33].x,1e-4),(r.x-lm[362].x)/Math.max(lm[263].x-lm[362].x,1e-4)]),y:mean([(l.y-lm[159].y)/Math.max(lm[145].y-lm[159].y,1e-4),(r.y-lm[386].y)/Math.max(lm[374].y-lm[386].y,1e-4)])}}
async function startEye(){const m=$('#meye2'),v=$('#eyev',m),s=$('#eyest',m);try{s.textContent='Ładowanie MediaPipe…';eye.lm=await faceLandmarker(false);eye.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});v.srcObject=eye.stream;await v.play();eye.running=true;eye.last=-1;$('#eyeLiveStart',m).disabled=true;$('#eyex',m).disabled=false;s.textContent='Live aktywny. Spójrz na środek i kliknij „Kalibruj środek”.';eyeLoop()}catch(e){stopEye();s.textContent='Błąd: '+String(e.message||e)}}
function stopEye(){eye.running=false;cancelAnimationFrame(eye.raf);eye.stream?.getTracks().forEach(t=>t.stop());eye.stream=null;eye.lm?.close?.();eye.lm=null;const m=$('#meye2');if(m){$('#eyeLiveStart',m).disabled=false;$('#eyex',m).disabled=true;$('#eyest',m).textContent='Tryb Live wyłączony.'}}
function eyeLoop(){if(!eye.running)return;const m=$('#meye2'),v=$('#eyev',m);if(v.readyState>=2&&v.currentTime!==eye.last){eye.last=v.currentTime;const r=eye.lm.detectForVideo(v,performance.now()),lm=r.faceLandmarks?.[0];if(lm){eye.raw=rawGaze(lm);const g={x:clamp(.5+(eye.raw.x-eye.cal.x)*2.8,0,1),y:clamp(.5+(eye.raw.y-eye.cal.y)*2.5,0,1)};renderEye(g);$('#eyest',m).textContent=`Live · X ${(g.x*100).toFixed(0)}% · Y ${(g.y*100).toFixed(0)}%`;drawEyeOverlay($('#eyeo',m),v,lm)}else $('#eyest',m).textContent='Nie wykryto twarzy.'}eye.raf=requestAnimationFrame(eyeLoop)}
function drawEyeOverlay(cv,v,lm){cv.width=v.videoWidth||640;cv.height=v.videoHeight||480;const ctx=cv.getContext('2d');ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle=C().accent;[33,133,362,263,468,473].forEach(i=>{if(!lm[i])return;ctx.beginPath();ctx.arc((1-lm[i].x)*cv.width,lm[i].y*cv.height,4,0,Math.PI*2);ctx.fill()})}
function renderEye(g=null){const m=$('#meye2');if(!m)return;const st=$('#eyestage',m);$$('.fix-point,.scan-seg,.gaze-point',st).forEach(x=>x.remove());eye.pts.forEach((p,i)=>{const d=document.createElement('i');d.className='fix-point';Object.assign(d.style,{left:p.x*100+'%',top:p.y*100+'%',width:'24px',height:'24px'});st.appendChild(d);if(i){const a=eye.pts[i-1],dx=(p.x-a.x)*st.clientWidth,dy=(p.y-a.y)*st.clientHeight,s=document.createElement('i');s.className='scan-seg';Object.assign(s.style,{left:a.x*100+'%',top:a.y*100+'%',width:Math.hypot(dx,dy)+'px',transform:`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`});st.appendChild(s)}});if(g){const d=document.createElement('i');d.className='gaze-point';d.style.left=g.x*100+'%';d.style.top=g.y*100+'%';st.appendChild(d)}}

function init(){['#msimlive','#mphys','#meye','#m6'].forEach(id=>$(id)?.classList.add('hidden'));buildSim();buildPhys();buildEye();window.addEventListener('beforeunload',()=>{stopSim();stopEye()})}
window.addEventListener('load',()=>setTimeout(init,0),{once:true});
window.addEventListener('eeg:module',e=>{if(e.detail!=='msimlive2'&&sim.running)stopSim();if(e.detail!=='meye2'&&eye.running)stopEye()});
