import{clamp,rand}from'./signal.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const css=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const C=()=>({accent:css('--accent'),danger:css('--danger'),violet:css('--violet'),warn:css('--warn'),muted:css('--muted'),line:css('--line'),well:css('--well')});
const head=(t,d,l)=>`<div class="head"><div><div class="eyebrow">${l}</div><h1>${t}</h1><p>${d}</p></div></div>`;
const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function axes(ctx,w,h,label=''){const c=C();ctx.clearRect(0,0,w,h);ctx.fillStyle=c.well||'#fff';ctx.fillRect(0,0,w,h);ctx.strokeStyle=c.line;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(42,i*h/5);ctx.lineTo(w-8,i*h/5);ctx.stroke()}ctx.fillStyle=c.muted;ctx.font='10px IBM Plex Mono';if(label)ctx.fillText(label,w-65,h-8)}
function trace(ctx,a,mid,scale,color){ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();a.forEach((v,i)=>{const x=48+i/Math.max(a.length-1,1)*(ctx.canvas.width-62),y=mid-v/scale;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
async function faceLandmarker(blend=false){const mp=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/+esm');const vision=await mp.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm');return mp.FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task'},runningMode:'VIDEO',numFaces:1,outputFaceBlendshapes:blend,minFaceDetectionConfidence:.5,minTrackingConfidence:.5})}

const sim={stream:null,lm:null,running:false,raf:0,last:-1,baseEAR:null,closed:false,prevClosed:false,blink:0,blinks:0,muscleOn:false,muscle:0,t:0,buf:{Fp1:new Array(750).fill(0),F7:new Array(750).fill(0),T7:new Array(750).fill(0),O1:new Array(750).fill(0)}};
function ear(lm,ids){const[p1,p2,p3,p4,p5,p6]=ids.map(i=>lm[i]);return(dist(p2,p6)+dist(p3,p5))/(2*Math.max(dist(p1,p4),1e-6))}
function muscleScore(c=[]){const g=n=>c.find(x=>x.categoryName===n)?.score||0;return clamp(.45*g('jawOpen')+.2*Math.max(g('mouthFunnel'),g('mouthPucker'))+.2*Math.max(g('mouthSmileLeft'),g('mouthSmileRight'))+.15*Math.max(g('cheekPuff'),g('browDownLeft'),g('browDownRight')),0,1)}
function buildSim(){const m=document.createElement('section');m.id='msimlive2';m.className='module';m.innerHTML=head('SimLive — oczy i mięśnie twarzy wpływają na EEG','Zamknięcie oczu zwiększa rytm alfa potyliczny, mrugnięcie dodaje EOG, a po włączeniu śledzenia mięśni ruch ust, żuchwy, policzków i brwi zwiększa szerokopasmowe zakłócenie tych samych kanałów EEG.','SIMLIVE')+`<div class="live-layout"><div><div class="panel"><h2><span class="dot"></span>Kamera</h2><div class="live-video"><video id="simv" autoplay playsinline muted></video><canvas id="simo" width="640" height="480"></canvas></div><div class="row" style="margin-top:10px"><button class="btn primary" id="sims">Uruchom</button><button class="btn" id="simx" disabled>Zatrzymaj</button></div><label class="toggle-row" style="margin-top:12px"><input id="simm" type="checkbox"><span><b>Śledzenie artefaktów mięśniowych</b><small>Ruchy twarzy i mówienie zanieczyszczają Fp1/F7/T7, nie tworzą osobnego kanału.</small></span></label><div class="readout" id="simst" style="margin-top:10px">Kamera wyłączona.</div></div><div class="live-indicator"><div class="metric"><div class="k">OCZY</div><div class="v" id="sime">—</div></div><div class="metric"><div class="k">MRUGNIĘCIA</div><div class="v" id="simb">0</div></div><div class="metric"><div class="k">EMG</div><div class="v" id="simemg">0%</div></div><div class="metric"><div class="k">TRYB</div><div class="v" id="simimpact" style="font-size:.9rem">EOG + alfa</div></div></div></div><div><div class="panel"><h2><span class="dot"></span>EEG na żywo</h2><canvas id="simeeg" width="1000" height="460"></canvas><div class="legend"><span>Fp1/F7/T7: EEG z EOG/EMG</span><span>O1: EEG z modulacją alfa</span></div></div><div class="module-note"><b>EMG twarzy/mowa</b> jest domieszką do istniejącego EEG. Im większa aktywność mięśniowa, tym silniejsza szybka, nieregularna aktywność szczególnie nad czołem i skronią.</div></div></div>`;$('#main').appendChild(m);$('#sims',m).onclick=startSim;$('#simx',m).onclick=stopSim;$('#simm',m).onchange=e=>{sim.muscleOn=e.target.checked;$('#simimpact',m).textContent=sim.muscleOn?'EOG + alfa + EMG':'EOG + alfa'};drawSim()}
async function startSim(){const m=$('#msimlive2'),v=$('#simv',m),s=$('#simst',m);try{s.textContent='Ładowanie MediaPipe…';sim.lm=await faceLandmarker(true);sim.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});v.srcObject=sim.stream;await v.play();sim.running=true;sim.last=-1;sim.baseEAR=null;$('#sims',m).disabled=true;$('#simx',m).disabled=false;s.textContent='Aktywne. Patrz naturalnie w kamerę.';simLoop()}catch(e){stopSim();s.textContent='Błąd: '+String(e.message||e)}}
function stopSim(){sim.running=false;cancelAnimationFrame(sim.raf);sim.stream?.getTracks().forEach(t=>t.stop());sim.stream=null;sim.lm?.close?.();sim.lm=null;const m=$('#msimlive2');if(m){$('#sims',m).disabled=false;$('#simx',m).disabled=true}}
function simLoop(){if(!sim.running)return;const m=$('#msimlive2'),v=$('#simv',m);if(v.readyState>=2&&v.currentTime!==sim.last){sim.last=v.currentTime;const r=sim.lm.detectForVideo(v,performance.now()),lm=r.faceLandmarks?.[0];if(lm){const e=(ear(lm,[33,160,158,133,153,144])+ear(lm,[362,385,387,263,373,380]))/2;sim.baseEAR=sim.baseEAR===null?e:(!sim.closed?.985*sim.baseEAR+.015*e:sim.baseEAR);const th=sim.baseEAR*.62;sim.prevClosed=sim.closed;sim.closed=e<th;if(sim.prevClosed&&!sim.closed){sim.blink=1;sim.blinks++}sim.muscle=sim.muscleOn?(.85*sim.muscle+.15*muscleScore(r.faceBlendshapes?.[0]?.categories||[])):0;$('#sime',m).textContent=sim.closed?'zamknięte':'otwarte';$('#simb',m).textContent=sim.blinks;$('#simemg',m).textContent=Math.round(sim.muscle*100)+'%';$('#simst',m).textContent=`Twarz wykryta · EAR ${e.toFixed(3)}`;overlay($('#simo',m),v,lm)}else $('#simst',m).textContent='Nie wykryto twarzy.'}stepSim();drawSim();sim.raf=requestAnimationFrame(simLoop)}
function stepSim(){for(let k=0;k<5;k++){sim.t+=1/250;sim.blink*=.9;const t=sim.t,alpha=(sim.closed?29:8)*Math.sin(2*Math.PI*10*t),base=5*Math.sin(2*Math.PI*6*t)+3*Math.sin(2*Math.PI*19*t),eog=85*sim.blink,emg=sim.muscleOn?sim.muscle:0,fast=()=>rand(-1,1)*(18+38*Math.abs(Math.sin(2*Math.PI*(32+rand(0,20))*t))),vals={Fp1:base+rand(-4,4)+eog+1.3*emg*fast(),F7:.9*base+rand(-4,4)+.55*eog+1.15*emg*fast(),T7:.65*base+rand(-4,4)+1.35*emg*fast(),O1:alpha+5*Math.sin(2*Math.PI*6*t)+rand(-4,4)+.12*emg*fast()};Object.keys(sim.buf).forEach(id=>{sim.buf[id].push(vals[id]);sim.buf[id].shift()})}}
function drawSim(){const m=$('#msimlive2');if(!m)return;const cv=$('#simeeg',m),ctx=cv.getContext('2d'),c=C(),ids=['Fp1','F7','T7','O1'],row=(cv.height-36)/4;axes(ctx,cv.width,cv.height,'3 s');ids.forEach((id,i)=>{const mid=12+row*(i+.5);ctx.fillStyle=c.muted;ctx.font='10px IBM Plex Mono';ctx.fillText(id,8,mid+3);trace(ctx,sim.buf[id],mid,1.35,c.accent)})}
function overlay(cv,v,lm){cv.width=v.videoWidth||640;cv.height=v.videoHeight||480;const ctx=cv.getContext('2d');ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle=C().accent;[33,133,362,263,13,14,61,291].forEach(i=>{if(!lm[i])return;ctx.beginPath();ctx.arc((1-lm[i].x)*cv.width,lm[i].y*cv.height,3,0,Math.PI*2);ctx.fill()})}

const stimuli={neutral:{name:'Neutralny',hr:70,eda:4.8,emg:8},cognitive:{name:'Zadanie poznawcze',hr:88,eda:5.8,emg:16},startle:{name:'Nagły bodziec',hr:116,eda:7.2,emg:34},recovery:{name:'Regeneracja',hr:64,eda:4.5,emg:7}};
const phys={k:'neutral',hr:70,eda:4.8,emg:8,t:0,buf:{ecg:new Array(1000).fill(0),eda:new Array(1000).fill(4.8),emg:new Array(1000).fill(0)}};
function buildPhys(){const m=document.createElement('section');m.id='mphys2';m.className='module';m.innerHTML=head('EMG · EKG · GSR','Wybierz bodziec i obserwuj dynamiczną zmianę częstości serca, przewodnictwa skóry i napięcia mięśniowego.','FIZJOLOGIA OBWODOWA')+`<div class="grid g2"><div><div class="panel"><h2><span class="dot"></span>Bodziec</h2><div class="artifact-grid">${Object.entries(stimuli).map(([k,v])=>`<button class="artifact-card" data-p="${k}"><strong>${v.name}</strong><span>HR ${v.hr} · EDA ${v.eda} · EMG ${v.emg}</span></button>`).join('')}</div></div><div class="live-indicator"><div class="metric"><div class="k">HR</div><div class="v" id="phr">70</div></div><div class="metric"><div class="k">EDA</div><div class="v" id="peda">4.8</div></div><div class="metric"><div class="k">EMG</div><div class="v" id="pemg">8</div></div><div class="metric"><div class="k">BODZIEC</div><div class="v" id="pst" style="font-size:.9rem">Neutralny</div></div></div></div><div><div class="panel"><h2><span class="dot"></span>EKG</h2><canvas id="pecg" width="950" height="180"></canvas></div><div class="panel"><h2><span class="dot"></span>GSR / EDA</h2><canvas id="pedaCv" width="950" height="150"></canvas></div><div class="panel"><h2><span class="dot"></span>EMG</h2><canvas id="pemgCv" width="950" height="150"></canvas></div></div></div>`;$('#main').appendChild(m);$$('[data-p]',m).forEach(b=>b.onclick=()=>phys.k=b.dataset.p);physLoop()}
function physLoop(){const q=stimuli[phys.k];phys.hr+=(q.hr-phys.hr)*.015;phys.eda+=(q.eda-phys.eda)*.006;phys.emg+=(q.emg-phys.emg)*.025;for(let k=0;k<2;k++){phys.t+=.01;const per=60/phys.hr,ph=(phys.t%per)/per;phys.buf.ecg.push(100*Math.exp(-((ph-.08)**2)/.00022)-18*Math.exp(-((ph-.045)**2)/.0003)+20*Math.exp(-((ph-.19)**2)/.004)+rand(-1.5,1.5));phys.buf.eda.push(phys.eda+rand(-.02,.02));phys.buf.emg.push(rand(-phys.emg,phys.emg));Object.values(phys.buf).forEach(a=>a.shift())}const m=$('#mphys2');if(m?.classList.contains('active')){const c=C();$('#phr',m).textContent=Math.round(phys.hr);$('#peda',m).textContent=phys.eda.toFixed(1);$('#pemg',m).textContent=Math.round(phys.emg);$('#pst',m).textContent=q.name;[['pecg',phys.buf.ecg,1.2,c.danger],['pedaCv',phys.buf.eda,.05,c.accent],['pemgCv',phys.buf.emg,.45,c.violet]].forEach(([id,a,s,col])=>{const cv=$('#'+id,m),ctx=cv.getContext('2d');axes(ctx,cv.width,cv.height,'10 s');trace(ctx,a,cv.height/2,s,col)})}requestAnimationFrame(physLoop)}

const eye={pts:[],stream:null,lm:null,running:false,raf:0,last:-1,cal:{x:.5,y:.5},raw:{x:.5,y:.5}};
function buildEye(){const m=document.createElement('section');m.id='meye2';m.className='module';m.innerHTML=head('Eye-Tracking','Symuluj ścieżkę wzroku kliknięciami lub użyj MediaPipe do przybliżonego śledzenia spojrzenia z położenia tęczówek.','EYE-TRACKING')+`<div class="grid g2"><div><div class="panel"><h2><span class="dot"></span>Tryb Live</h2><div class="live-video"><video id="eyev" autoplay playsinline muted></video><canvas id="eyeo" width="640" height="480"></canvas></div><div class="row" style="margin-top:10px"><button class="btn primary" id="eyes">Uruchom MediaPipe</button><button class="btn" id="eyecal">Kalibruj środek</button><button class="btn" id="eyex" disabled>Zatrzymaj</button></div><div class="readout" id="eyest" style="margin-top:10px">Tryb Live wyłączony.</div></div><div class="panel"><h2><span class="dot"></span>Tryb ręczny</h2><div class="row"><button class="btn" id="eyeclear">Wyczyść</button><button class="btn" id="eyedemo">Symuluj scanpath</button></div></div></div><div><div class="panel"><h2><span class="dot"></span>Scena</h2><div class="eye-stage2" id="eyestage"><div class="eye-target2" style="left:13%;top:18%">A</div><div class="eye-target2" style="left:72%;top:17%">B</div><div class="eye-target2" style="left:43%;top:67%">C</div></div></div></div></div>`;$('#main').appendChild(m);const st=$('#eyestage',m);st.onclick=e=>{const r=st.getBoundingClientRect();eye.pts.push({x:clamp((e.clientX-r.left)/r.width,0,1),y:clamp((e.clientY-r.top)/r.height,0,1)});renderEye()};$('#eyeclear',m).onclick=()=>{eye.pts=[];renderEye()};$('#eyedemo',m).onclick=()=>{eye.pts=[];[[.18,.25],[.22,.28],[.48,.72],[.76,.24],[.51,.69],[.20,.26]].forEach((p,i)=>setTimeout(()=>{eye.pts.push({x:p[0],y:p[1]});renderEye()},i*250))};$('#eyes',m).onclick=startEye;$('#eyex',m).onclick=stopEye;$('#eyecal',m).onclick=()=>{eye.cal={...eye.raw};$('#eyest',m).textContent='Środek skalibrowany.'};renderEye()}
function iris(lm,ids){const p=ids.map(i=>lm[i]).filter(Boolean);return{x:mean(p.map(x=>x.x)),y:mean(p.map(x=>x.y))}}
function rawGaze(lm){if(!lm[477])return{x:.5,y:.5};const l=iris(lm,[468,469,470,471,472]),r=iris(lm,[473,474,475,476,477]);return{x:mean([(l.x-lm[33].x)/Math.max(lm[133].x-lm[33].x,1e-4),(r.x-lm[362].x)/Math.max(lm[263].x-lm[362].x,1e-4)]),y:mean([(l.y-lm[159].y)/Math.max(lm[145].y-lm[159].y,1e-4),(r.y-lm[386].y)/Math.max(lm[374].y-lm[386].y,1e-4)])}}
async function startEye(){const m=$('#meye2'),v=$('#eyev',m),s=$('#eyest',m);try{s.textContent='Ładowanie MediaPipe…';eye.lm=await faceLandmarker(false);eye.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});v.srcObject=eye.stream;await v.play();eye.running=true;eye.last=-1;$('#eyes',m).disabled=true;$('#eyex',m).disabled=false;s.textContent='Live aktywny. Spójrz na środek i kliknij „Kalibruj środek”.';eyeLoop()}catch(e){stopEye();s.textContent='Błąd: '+String(e.message||e)}}
function stopEye(){eye.running=false;cancelAnimationFrame(eye.raf);eye.stream?.getTracks().forEach(t=>t.stop());eye.stream=null;eye.lm?.close?.();eye.lm=null;const m=$('#meye2');if(m){$('#eyes',m).disabled=false;$('#eyex',m).disabled=true}}
function eyeLoop(){if(!eye.running)return;const m=$('#meye2'),v=$('#eyev',m);if(v.readyState>=2&&v.currentTime!==eye.last){eye.last=v.currentTime;const r=eye.lm.detectForVideo(v,performance.now()),lm=r.faceLandmarks?.[0];if(lm){eye.raw=rawGaze(lm);const g={x:clamp(.5+(eye.raw.x-eye.cal.x)*2.8,0,1),y:clamp(.5+(eye.raw.y-eye.cal.y)*2.5,0,1)};renderEye(g);$('#eyest',m).textContent=`Live · X ${(g.x*100).toFixed(0)}% · Y ${(g.y*100).toFixed(0)}%`;overlay($('#eyeo',m),v,lm)}else $('#eyest',m).textContent='Nie wykryto twarzy.'}eye.raf=requestAnimationFrame(eyeLoop)}
function renderEye(g=null){const m=$('#meye2');if(!m)return;const st=$('#eyestage',m);$$('.fix-point,.scan-seg,.gaze-point',st).forEach(x=>x.remove());eye.pts.forEach((p,i)=>{const d=document.createElement('i');d.className='fix-point';Object.assign(d.style,{left:p.x*100+'%',top:p.y*100+'%',width:'24px',height:'24px'});st.appendChild(d);if(i){const a=eye.pts[i-1],dx=(p.x-a.x)*st.clientWidth,dy=(p.y-a.y)*st.clientHeight,s=document.createElement('i');s.className='scan-seg';Object.assign(s.style,{left:a.x*100+'%',top:a.y*100+'%',width:Math.hypot(dx,dy)+'px',transform:`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`});st.appendChild(s)}});if(g){const d=document.createElement('i');d.className='gaze-point';d.style.left=g.x*100+'%';d.style.top=g.y*100+'%';st.appendChild(d)}}

function init(){['#msimlive','#mphys','#meye','#m6'].forEach(id=>$(id)?.classList.add('hidden'));buildSim();buildPhys();buildEye();window.addEventListener('beforeunload',()=>{stopSim();stopEye()})}
window.addEventListener('load',()=>setTimeout(init,0),{once:true});
