import{clamp,rand}from'./signal.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const css=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const C=()=>({accent:css('--accent'),danger:css('--danger'),violet:css('--violet'),muted:css('--muted'),line:css('--line'),panel:css('--panel'),well:css('--well'),text:css('--text')});
const head=(t,d,l)=>`<div class="head"><div><div class="eyebrow">${l}</div><h1>${t}</h1><p>${d}</p></div></div>`;
function axes(ctx,w,h,label=''){const c=C();ctx.clearRect(0,0,w,h);ctx.fillStyle=c.well||'#fff';ctx.fillRect(0,0,w,h);ctx.strokeStyle=c.line;ctx.lineWidth=1;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(42,i*h/5);ctx.lineTo(w-8,i*h/5);ctx.stroke()}ctx.fillStyle=c.muted;ctx.font='10px IBM Plex Mono';if(label)ctx.fillText(label,w-72,h-8)}
function trace(ctx,a,x0,mid,w,scale,color){ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();a.forEach((v,i)=>{const x=x0+i/Math.max(a.length-1,1)*w,y=mid-v/scale;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function mean(a){return a.length?a.reduce((s,v)=>s+v,0)/a.length:0}

const sim={stream:null,landmarker:null,running:false,raf:0,lastVideoTime:-1,baseEAR:null,closed:false,wasClosed:false,blinkPulse:0,blinkCount:0,muscleEnabled:false,muscle:0,t:0,buf:{Fp1:new Array(750).fill(0),F7:new Array(750).fill(0),T7:new Array(750).fill(0),O1:new Array(750).fill(0)}};
function ear(lm,ids){const[p1,p2,p3,p4,p5,p6]=ids.map(i=>lm[i]);return(dist(p2,p6)+dist(p3,p5))/(2*Math.max(dist(p1,p4),1e-6))}
function blendScore(cats=[]){const g=n=>cats.find(x=>x.categoryName===n)?.score||0;return clamp(.42*g('jawOpen')+.20*Math.max(g('mouthFunnel'),g('mouthPucker'))+.18*Math.max(g('mouthSmileLeft'),g('mouthSmileRight'))+.12*Math.max(g('cheekPuff'),g('cheekSquintLeft'),g('cheekSquintRight'))+.08*Math.max(g('browDownLeft'),g('browDownRight'),g('browInnerUp')),0,1)}
function buildSimLive2(){const m=document.createElement('section');m.id='msimlive2';m.className='module';m.innerHTML=head('SimLive — oczy, mrugnięcia i EMG twarzy w jednym EEG','MediaPipe analizuje twarz lokalnie w przeglądarce. Zamknięcie oczu moduluje alfa potyliczne, mrugnięcia wprowadzają EOG, a ruchy ust, żuchwy, policzków i brwi — po włączeniu opcji — zanieczyszczają te same kanały EEG szerokopasmowym EMG.','SIMLIVE')+`<div class="live-layout"><div><div class="panel"><h2><span class="dot"></span>Kamera i detekcja</h2><div class="live-video"><video id="sim2video" autoplay playsinline muted></video><canvas id="sim2overlay" width="640" height="480"></canvas></div><div class="row" style="margin-top:10px"><button class="btn primary" id="sim2start">Uruchom kamerę</button><button class="btn" id="sim2stop" disabled>Zatrzymaj</button></div><label class="toggle-row" style="margin-top:12px"><input type="checkbox" id="sim2muscle"><span><b>Śledzenie artefaktów mięśniowych</b><small>Ruchy twarzy i mówienie zwiększają szerokopasmowe zakłócenie w kanałach czołowo-skroniowych.</small></span></label><div class="readout" id="sim2status" style="margin-top:10px">Kamera wyłączona.</div></div><div class="panel"><h2><span class="dot"></span>Detektor</h2><div class="live-indicator"><div class="metric"><div class="k">OCZY</div><div class="v" id="sim2eyes">—</div></div><div class="metric"><div class="k">MRUGNIĘCIA</div><div class="v" id="sim2blinks">0</div></div><div class="metric"><div class="k">EMG TWARZY</div><div class="v" id="sim2emg">0%</div></div><div class="metric"><div class="k">WPŁYW</div><div class="v" id="sim2impact" style="font-size:.9rem">EOG + alfa</div></div></div></div></div><div><div class="panel"><h2><span class="dot"></span>EEG na żywo</h2><canvas id="sim2eeg" width="1000" height="460"></canvas><div class="legend"><span>Fp1/F7/T7 — EEG + EOG/EMG</span><span>O1 — EEG + modulacja alfa</span></div></div><div class="module-note"><b>Ważne:</b> „EMG twarzy/mowa” nie jest osobnym kanałem na wykresie. Zwiększa amplitudę szybkich zakłóceń już istniejących kanałów EEG, szczególnie Fp1, F7 i T7.</div></div></div>`;$('#main').appendChild(m);$('#sim2start',m).onclick=startSim;$('#sim2stop',m).onclick=stopSim;$('#sim2muscle',m).onchange=e=>{sim.muscleEnabled=e.target.checked;$('#sim2impact',m).textContent=sim.muscleEnabled?'EOG + alfa + EMG':'EOG + alfa'};drawSim()}
async function startSim(){const m=$('#msimlive2'),v=$('#sim2video',m),s=$('#sim2status',m);try{s.textContent='Ładowanie MediaPipe…';const mp=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/+esm');const vision=await mp.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm');sim.landmarker=await mp.FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task'},runningMode:'VIDEO',numFaces:1,outputFaceBlendshapes:true,minFaceDetectionConfidence:.5,minTrackingConfidence:.5});sim.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});v.srcObject=sim.stream;await v.play();sim.running=true;sim.baseEAR=null;sim.lastVideoTime=-1;$('#sim2start',m).disabled=true;$('#sim2stop',m).disabled=false;s.textContent='Detekcja aktywna. Patrz naturalnie w kamerę przez kilka sekund.';simLoop()}catch(e){s.innerHTML=`<span class="bad">Nie udało się uruchomić kamery/MediaPipe:</span> ${String(e.message||e)}`;stopSim()}}
function stopSim(){sim.running=false;cancelAnimationFrame(sim.raf);sim.stream?.getTracks().forEach(t=>t.stop());sim.stream=null;sim.landmarker?.close?.();sim.landmarker=null;const m=$('#msimlive2');if(m){$('#sim2start',m).disabled=false;$('#sim2stop',m).disabled=true;$('#sim2status',m).textContent='Kamera wyłączona.'}}
function simLoop(){if(!sim.running)return;const m=$('#msimlive2'),v=$('#sim2video',m);if(v.readyState>=2&&v.currentTime!==sim.lastVideoTime){sim.lastVideoTime=v.currentTime;const res=sim.landmarker.detectForVideo(v,performance.now()),lm=res.faceLandmarks?.[0];if(lm){const e=(ear(lm,[33,160,158,133,153,144])+ear(lm,[362,385,387,263,373,380]))/2;if(sim.baseEAR===null)sim.baseEAR=e;else if(!sim.closed)sim.baseEAR=.985*sim.baseEAR+.015*e;const th=sim.baseEAR*.62;sim.wasClosed=sim.closed;sim.closed=e<th;if(sim.wasClosed&&!sim.closed){sim.blinkPulse=1;sim.blinkCount++}const cats=res.faceBlendshapes?.[0]?.categories||[];sim.muscle=sim.muscleEnabled?(.84*sim.muscle+.16*blendScore(cats)):0;$('#sim2eyes',m).textContent=sim.closed?'zamknięte':'otwarte';$('#sim2blinks',m).textContent=sim.blinkCount;$('#sim2emg',m).textContent=Math.round(sim.muscle*100)+'%';$('#sim2status',m).textContent=`Twarz wykryta · EAR ${e.toFixed(3)} · próg ${th.toFixed(3)}`;drawFaceOverlay(lm)}else{$('#sim2status',m).textContent='Nie wykryto twarzy.';$('#sim2eyes',m).textContent='—'}}}simStep(5);drawSim();sim.raf=requestAnimationFrame(simLoop)}
function drawFaceOverlay(lm){const m=$('#msimlive2'),cv=$('#sim2overlay',m),v=$('#sim2video',m),ctx=cv.getContext('2d');cv.width=v.videoWidth||640;cv.height=v.videoHeight||480;ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle=sim.closed?C().danger:C().accent;[33,133,160,158,153,144,362,263,385,387,373,380,13,14,61,291].forEach(i=>{if(!lm[i])return;ctx.beginPath();ctx.arc((1-lm[i].x)*cv.width,lm[i].y*cv.height,3,0,Math.PI*2);ctx.fill()})}
function simStep(n=5){for(let k=0;k<n;k++){sim.t+=1/250;sim.blinkPulse*=.90;const t=sim.t,alpha=(sim.closed?29:8)*Math.sin(2*Math.PI*10*t),base=4*Math.sin(2*Math.PI*6.2*t)+3*Math.sin(2*Math.PI*19*t),pink=rand(-4,4),eog=sim.blinkPulse*85,emg=sim.muscleEnabled?sim.muscle:0;const fast=()=>rand(-1,1)*(20+35*Math.abs(Math.sin(2*Math.PI*(32+rand(0,18))*t)));const vals={Fp1:base+pink+eog+emg*1.3*fast(),F7:base*.9+rand(-4,4)+eog*.55+emg*1.15*fast(),T7:base*.65+rand(-4,4)+emg*1.35*fast(),O1:alpha+5*Math.sin(2*Math.PI*6*t)+rand(-4,4)+emg*.12*fast()};for(const id of Object.keys(sim.buf)){sim.buf[id].push(vals[id]);sim.buf[id].shift()}}}
function drawSim(){const m=$('#msimlive2');if(!m)return;const cv=$('#sim2eeg',m),ctx=cv.getContext('2d'),c=C(),ids=['Fp1','F7','T7','O1'],H=cv.height,row=(H-36)/4;axes(ctx,cv.width,H,'3 s');ids.forEach((id,i)=>{const mid=12+row*(i+.5);ctx.fillStyle=c.muted;ctx.font='10px IBM Plex Mono';ctx.fillText(id,8,mid+3);trace(ctx,sim.buf[id],48,mid,cv.width-62,1.35,c.accent)})}

const PSTIM={neutral:{label:'Neutralny',hr:70,eda:4.8,emg:8},cognitive:{label:'Zadanie poznawcze',hr:88,eda:5.8,emg:16},startle:{label:'Nagły bodziec',hr:116,eda:7.2,emg:34},recovery:{label:'Regeneracja',hr:64,eda:4.5,emg:7}};
const phys={stim:'neutral',hr:70,eda:4.8,emg:8,target:{...PSTIM.neutral},t:0,buf:{ecg:new Array(1000).fill(0),eda:new Array(1000).fill(4.8),emg:new Array(1000).fill(0)},raf:0};
function buildPhys2(){const m=document.createElement('section');m.id='mphys2';m.className='module';m.innerHTML=head('EMG · EKG · GSR','Zmieniaj bodziec i obserwuj zsynchronizowaną reakcję mięśniową, sercową i elektrodermalną. EKG nie jest stałym przebiegiem — częstość rytmu dochodzi dynamicznie do wartości zależnej od bodźca.','FIZJOLOGIA OBWODOWA')+`<div class="grid g2"><div><div class="panel"><h2><span class="dot"></span>Bodziec</h2><div class="artifact-grid">${Object.entries(PSTIM).map(([k,v])=>`<button class="artifact-card ${k==='neutral'?'fired':''}" data-pstim="${k}"><strong>${v.label}</strong><span>HR ${v.hr} bpm · EDA ${v.eda} µS · EMG ${v.emg}</span></button>`).join('')}</div></div><div class="panel"><h2><span class="dot"></span>Stan bieżący</h2><div class="live-indicator"><div class="metric"><div class="k">HR</div><div class="v" id="p2hr">70</div></div><div class="metric"><div class="k">EDA</div><div class="v" id="p2eda">4.8</div></div><div class="metric"><div class="k">EMG</div><div class="v" id="p2emg">8</div></div><div class="metric"><div class="k">BODZIEC</div><div class="v" id="p2stim" style="font-size:.9rem">Neutralny</div></div></div></div></div><div><div class="panel"><h2><span class="dot"></span>EKG</h2><canvas id="p2ecg" width="960" height="180"></canvas></div><div class="panel"><h2><span class="dot"></span>GSR / EDA</h2><canvas id="p2edaCv" width="960" height="150"></canvas></div><div class="panel"><h2><span class="dot"></span>EMG</h2><canvas id="p2emgCv" width="960" height="150"></canvas></div></div></div>`;$('#main').appendChild(m);$$('[data-pstim]',m).forEach(b=>b.onclick=()=>{phys.stim=b.dataset.pstim;phys.target={...PSTIM[phys.stim]};$$('[data-pstim]',m).forEach(x=>x.classList.toggle('fired',x===b))});physLoop()}
function physLoop(){phys.hr+=(phys.target.hr-phys.hr)*.015;phys.eda+=(phys.target.eda-phys.eda)*.006;phys.emg+=(phys.target.emg-phys.emg)*.025;for(let k=0;k<2;k++){phys.t+=.01;const per=60/phys.hr,ph=(phys.t%per)/per,qrs=100*Math.exp(-((ph-.08)**2)/.00022)-18*Math.exp(-((ph-.045)**2)/.0003)+20*Math.exp(-((ph-.19)**2)/.004);phys.buf.ecg.push(qrs+rand(-1.5,1.5));phys.buf.eda.push(phys.eda+.08*Math.sin(2*Math.PI*.07*phys.t)+rand(-.02,.02));phys.buf.emg.push(rand(-phys.emg,phys.emg)*(0.55+0.45*Math.sin(2*Math.PI*33*phys.t)));Object.values(phys.buf).forEach(a=>a.shift())}const m=$('#mphys2');if(m?.classList.contains('active')){const c=C();$('#p2hr',m).textContent=Math.round(phys.hr);$('#p2eda',m).textContent=phys.eda.toFixed(1);$('#p2emg',m).textContent=Math.round(phys.emg);$('#p2stim',m).textContent=PSTIM[phys.stim].label;[['p2ecg',phys.buf.ecg,-40,120,c.danger],['p2edaCv',phys.buf.eda,3.5,8,c.accent],['p2emgCv',phys.buf.emg,-45,45,c.violet]].forEach(([id,a,min,max,col])=>{const cv=$('#'+id,m),ctx=cv.getContext('2d');axes(ctx,cv.width,cv.height,'10 s');const mid=cv.height/2,sc=(cv.height*.38)/Math.max(Math.abs(min),Math.abs(max));trace(ctx,a,44,mid,cv.width-58,1/sc,col)})}phys.raf=requestAnimationFrame(physLoop)}

const eye={pts:[],stream:null,landmarker:null,running:false,raf:0,lastVideoTime:-1,cal:{x:.5,y:.5},raw:{x:.5,y:.5}};
function buildEye2(){const m=document.createElement('section');m.id='meye2';m.className='module';m.innerHTML=head('Eye-Tracking','Klikaj ręcznie, aby zasymulować ścieżkę wzroku, albo uruchom tryb Live. MediaPipe śledzi tęczówki względem konturów oczu i mapuje przybliżony kierunek spojrzenia na scenę.','EYE-TRACKING')+`<div class="grid g2"><div><div class="panel"><h2><span class="dot"></span>Tryb Live</h2><div class="live-video"><video id="eye2video" autoplay playsinline muted></video><canvas id="eye2overlay" width="640" height="480"></canvas></div><div class="row" style="margin-top:10px"><button class="btn primary" id="eye2start">Uruchom MediaPipe</button><button class="btn" id="eye2cal">Kalibruj środek</button><button class="btn" id="eye2stop" disabled>Zatrzymaj</button></div><div class="readout" id="eye2status" style="margin-top:10px">Tryb Live wyłączony.</div></div><div class="panel"><h2><span class="dot"></span>Tryb ręczny</h2><p class="readout">Klikaj w scenę po prawej. Każde kliknięcie jest traktowane jak kolejna fiksacja.</p><div class="row" style="margin-top:10px"><button class="btn" id="eye2clear">Wyczyść</button><button class="btn" id="eye2demo">Symuluj scanpath</button></div></div></div><div><div class="panel"><h2><span class="dot"></span>Scena</h2><div class="eye-stage2" id="eye2stage"><div class="eye-target2" style="left:13%;top:18%">A</div><div class="eye-target2" style="left:72%;top:17%">B</div><div class="eye-target2" style="left:43%;top:67%">C</div></div><div class="legend"><span>zielone: fiksacje</span><span>czerwone: bieżący gaze Live</span></div></div></div></div>`;$('#main').appendChild(m);const st=$('#eye2stage',m);st.onclick=e=>{const r=st.getBoundingClientRect();addFix((e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height)};$('#eye2clear',m).onclick=()=>{eye.pts=[];renderEye2()};$('#eye2demo',m).onclick=()=>{eye.pts=[];[[.18,.25],[.22,.28],[.48,.72],[.76,.24],[.51,.69],[.20,.26]].forEach((p,i)=>setTimeout(()=>addFix(...p),i*250))};$('#eye2start',m).onclick=startEye2;$('#eye2stop',m).onclick=stopEye2;$('#eye2cal',m).onclick=()=>{eye.cal={...eye.raw};$('#eye2status',m).textContent='Środek skalibrowany.'};renderEye2()}
function addFix(x,y){eye.pts.push({x:clamp(x,0,1),y:clamp(y,0,1)});if(eye.pts.length>40)eye.pts.shift();renderEye2()}
function renderEye2(gaze=null){const m=$('#meye2');if(!m)return;const st=$('#eye2stage',m);$$('.fix-point,.scan-seg,.gaze-point',st).forEach(x=>x.remove());eye.pts.forEach((p,i)=>{const d=document.createElement('i');d.className='fix-point';Object.assign(d.style,{left:p.x*100+'%',top:p.y*100+'%',width:'24px',height:'24px'});st.appendChild(d);if(i){const a=eye.pts[i-1],dx=(p.x-a.x)*st.clientWidth,dy=(p.y-a.y)*st.clientHeight,s=document.createElement('i');s.className='scan-seg';Object.assign(s.style,{left:a.x*100+'%',top:a.y*100+'%',width:Math.hypot(dx,dy)+'px',transform:`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`});st.appendChild(s)}});if(gaze){const d=document.createElement('i');d.className='gaze-point';d.style.left=gaze.x*100+'%';d.style.top=gaze.y*100+'%';st.appendChild(d)}}
function irisCenter(lm,ids){const pts=ids.map(i=>lm[i]).filter(Boolean);return{x:mean(pts.map(p=>p.x)),y:mean(pts.map(p=>p.y))}}
function gaze(lm){if(!lm[477])return{x:.5,y:.5};const li=irisCenter(lm,[468,469,470,471,472]),ri=irisCenter(lm,[473,474,475,476,477]);const lx=(li.x-lm[33].x)/Math.max(lm[133].x-lm[33].x,1e-4),rx=(ri.x-lm[362].x)/Math.max(lm[263].x-lm[362].x,1e-4),ly=(li.y-lm[159].y)/Math.max(lm[145].y-lm[159].y,1e-4),ry=(ri.y-lm[386].y)/Math.max(lm[374].y-lm[386].y,1e-4);return{x:mean([lx,rx]),y:mean([ly,ry])}}
async function startEye2(){const m=$('#meye2'),v=$('#eye2video',m),s=$('#eye2status',m);try{s.textContent='Ładowanie MediaPipe…';const mp=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/+esm');const vision=await mp.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm');eye.landmarker=await mp.FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task'},runningMode:'VIDEO',numFaces:1,minFaceDetectionConfidence:.5,minTrackingConfidence:.5});eye.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});v.srcObject=eye.stream;await v.play();eye.running=true;eye.lastVideoTime=-1;$('#eye2start',m).disabled=true;$('#eye2stop',m).disabled=false;s.textContent='Live aktywny. Spójrz na środek sceny i kliknij „Kalibruj środek”.';eye2Loop()}catch(e){s.innerHTML=`<span class="bad">Błąd:</span> ${String(e.message||e)}`;stopEye2()}}
function stopEye2(){eye.running=false;cancelAnimationFrame(eye.raf);eye.stream?.getTracks().forEach(t=>t.stop());eye.stream=null;eye.landmarker?.close?.();eye.landmarker=null;const m=$('#meye2');if(m){$('#eye2start',m).disabled=false;$('#eye2stop',m).disabled=true;$('#eye2status',m).textContent='Tryb Live wyłączony.';renderEye2()}}
function eye2Loop(){if(!eye.running)return;const m=$('#meye2'),v=$('#eye2video',m);if(v.readyState>=2&&v.currentTime!==eye.lastVideoTime){eye.lastVideoTime=v.currentTime;const res=eye.landmarker.detectForVideo(v,performance.now()),lm=res.faceLandmarks?.[0];if(lm){eye.raw=gaze(lm);const gx=clamp(.5+(eye.raw.x-eye.cal.x)*2.8,0,1),gy=clamp(.5+(eye.raw.y-eye.cal.y)*2.5,0,1);renderEye2({x:gx,y:gy});$('#eye2status',m).textContent=`Live · gaze X ${(gx*100).toFixed(0)}% · Y ${(gy*100).toFixed(0)}%`;drawEyeOverlay2(lm)}else $('#eye2status',m).textContent='Nie wykryto twarzy.'}eye.raf=requestAnimationFrame(eye2Loop)}
function drawEyeOverlay2(lm){const m=$('#meye2'),cv=$('#eye2overlay',m),v=$('#eye2video',m),ctx=cv.getContext('2d');cv.width=v.videoWidth||640;cv.height=v.videoHeight||480;ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle=C().accent;[33,133,362,263,468,473].forEach(i=>{if(!lm[i])return;ctx.beginPath();ctx.arc((1-lm[i].x)*cv.width,lm[i].y*cv.height,4,0,Math.PI*2);ctx.fill()})}

function init(){['#msimlive','#mphys','#meye','#m6'].forEach(id=>$(id)?.classList.add('hidden'));buildSimLive2();buildPhys2();buildEye2();window.addEventListener('beforeunload',()=>{stopSim();stopEye2()})}
window.addEventListener('load',()=>setTimeout(init,0),{once:true});
