import{ELECTRODES}from'./signal.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const SYSTEMS={
 '10-20':{label:'System 10–20',desc:'Podstawowy międzynarodowy system rozmieszczenia elektrod, stosowany do orientacji anatomicznej i klasycznych montaży.',points:ELECTRODES.map(e=>({id:e.id,x:e.x,y:e.y,region:e.region,canonical:true}))},
 '10-10':{label:'System 10–10',desc:'Gęstszy system wykorzystujący dodatkowe pozycje pomiędzy punktami 10–20, zapewniający lepsze próbkowanie przestrzenne.',points:[...ELECTRODES.map(e=>({id:e.id,x:e.x,y:e.y,region:e.region,canonical:true})),{id:'AF7',x:48,y:43},{id:'AF3',x:76,y:40},{id:'AFz',x:100,y:39},{id:'AF4',x:124,y:40},{id:'AF8',x:152,y:43},{id:'FT7',x:27,y:78},{id:'FC5',x:48,y:78},{id:'FC3',x:70,y:77},{id:'FC1',x:88,y:76},{id:'FCz',x:100,y:76},{id:'FC2',x:112,y:76},{id:'FC4',x:130,y:77},{id:'FC6',x:152,y:78},{id:'FT8',x:173,y:78},{id:'TP7',x:27,y:122},{id:'CP5',x:48,y:122},{id:'CP3',x:70,y:123},{id:'CP1',x:88,y:124},{id:'CPz',x:100,y:124},{id:'CP2',x:112,y:124},{id:'CP4',x:130,y:123},{id:'CP6',x:152,y:122},{id:'TP8',x:173,y:122},{id:'PO7',x:49,y:157},{id:'PO3',x:76,y:160},{id:'POz',x:100,y:161},{id:'PO4',x:124,y:160},{id:'PO8',x:151,y:157}]},
 '10-5':{label:'System 10–5',desc:'Bardzo gęste rozmieszczenie pozycji, stosowane w wysokogęstościowym EEG i dokładniejszej analizie topografii.',points:[]}
};
function make105(){const pts=[],rows=[[34,['Fp1h','Fpz','Fp2h']],[45,['AFp7','AFp3','AFpz','AFp4','AFp8']],[56,['AFF9h','AFF7h','AFF5h','AFF3h','AFF1h','AFFz','AFF2h','AFF4h','AFF6h','AFF8h','AFF10h']],[72,['FFT9h','FFT7h','FFC5h','FFC3h','FFC1h','FFCz','FFC2h','FFC4h','FFC6h','FFT8h','FFT10h']],[90,['FTT9h','FTT7h','FCC5h','FCC3h','FCC1h','FCCz','FCC2h','FCC4h','FCC6h','FTT8h','FTT10h']],[108,['TTP9h','TTP7h','CCP5h','CCP3h','CCP1h','CCPz','CCP2h','CCP4h','CCP6h','TTP8h','TTP10h']],[126,['TPP9h','TPP7h','CPP5h','CPP3h','CPP1h','CPPz','CPP2h','CPP4h','CPP6h','TPP8h','TPP10h']],[144,['PPO9h','PPO7h','PPO5h','PPO3h','PPO1h','PPOz','PPO2h','PPO4h','PPO6h','PPO8h','PPO10h']],[160,['POO9h','POO7h','POO3h','POOz','POO4h','POO8h','POO10h']],[173,['OI1h','Oz','OI2h']]];for(const[y,names]of rows){const span=Math.min(156,38+(100-Math.abs(103-y))*.9),x0=100-span/2;names.forEach((id,i)=>pts.push({id,x:x0+(names.length===1?span/2:i/(names.length-1)*span),y}))}return pts.concat(ELECTRODES.map(e=>({id:e.id,x:e.x,y:e.y,canonical:true})))}
SYSTEMS['10-5'].points=make105();
function electrodeMarkup(p,dense,labels){const showLabel=labels&&(!dense||p.canonical);return`<g class="montage-electrode ${p.canonical?'canonical':'secondary-electrode'}"><circle cx="${p.x+10}" cy="${p.y+8}" r="${dense?(p.canonical?4.5:2.5):5.2}"/>${showLabel?`<text x="${p.x+10}" y="${p.y+10}" text-anchor="middle">${p.id}</text>`:''}</g>`}
function svg(system,labels=true){const s=SYSTEMS[system],dense=system==='10-5';return`<svg class="montage-map" viewBox="0 0 220 225" role="img" aria-label="${s.label}"><circle class="scalp" cx="110" cy="108" r="88"/><path class="feature" d="M98 20L110 7L122 20 M22 98Q12 108 22 118 M198 98Q208 108 198 118"/><g class="landmark"><circle cx="110" cy="7" r="4"/><text x="110" y="3" text-anchor="middle">NASION</text></g><g class="landmark"><circle cx="110" cy="196" r="4"/><text x="110" y="214" text-anchor="middle">INION</text></g>${s.points.map(p=>electrodeMarkup(p,dense,labels)).join('')}</svg>`}
function build(){const m=document.createElement('section');m.id='m2x';m.className='module';m.innerHTML=`<div class="head"><div><div class="eyebrow">MONTAŻ</div><h1>Systemy rozmieszczenia elektrod EEG</h1><p>Porównaj systemy 10–20, 10–10 i 10–5 oraz ich gęstość próbkowania przestrzennego. Punkty NASION i INION stanowią podstawowe punkty orientacyjne podczas pozycjonowania czepka.</p></div></div><div class="grid g2"><div><div class="panel"><h2><span class="dot"></span>Wybierz system</h2><div class="montage-tabs">${Object.entries(SYSTEMS).map(([k,v])=>`<button class="btn ${k==='10-20'?'primary':''}" data-montage-system="${k}">${v.label}</button>`).join('')}</div><div class="readout" id="system-desc" style="margin-top:12px"></div></div><div class="panel"><h2><span class="dot"></span>Punkty orientacyjne</h2><table><tbody><tr><td><b>NASION</b></td><td>przedni punkt odniesienia linii środkowej</td></tr><tr><td><b>INION</b></td><td>tylny punkt odniesienia linii środkowej</td></tr><tr><td><b>Punkty przeduszne</b></td><td>punkty odniesienia wymiaru poprzecznego głowy</td></tr></tbody></table></div><div class="panel"><h2><span class="dot"></span>Porównanie</h2><div class="readout" id="system-stats"></div></div></div><div><div class="panel"><h2><span class="dot"></span>Mapa elektrod</h2><div id="montage-map-wrap"></div></div><div class="panel"><h2><span class="dot"></span>Ćwiczenie</h2><p>Przełącz systemy i porównaj, jak zwiększenie liczby pozycji wpływa na próbkowanie powierzchni głowy.</p><button class="btn" id="show-labels">Pokaż/ukryj etykiety</button></div></div></div>`;$('#main').appendChild(m);let current='10-20',labels=true,pendingRender=0;const buttons=$$('.montage-tabs button[data-montage-system]',m);function render(){if(pendingRender)cancelAnimationFrame(pendingRender);pendingRender=requestAnimationFrame(()=>{pendingRender=0;const s=SYSTEMS[current];$('#montage-map-wrap',m).innerHTML=svg(current,labels);$('#system-desc',m).innerHTML=`<b>${s.label}</b> — ${s.desc}`;$('#system-stats',m).innerHTML=`Liczba punktów na schemacie: <b>${s.points.length}</b> · gęstość: <b>${current==='10-20'?'podstawowa':current==='10-10'?'średnia':'wysoka'}</b>${current==='10-5'&&labels?' · dla wydajności etykiety pokazano tylko dla pozycji 10–20':''}`;buttons.forEach(x=>x.classList.toggle('primary',x.dataset.montageSystem===current));});}buttons.forEach(b=>b.addEventListener('click',()=>{current=b.dataset.montageSystem;render()}));$('#show-labels',m).addEventListener('click',()=>{labels=!labels;render()});render()}
window.addEventListener('load',build,{once:true});