import{ELECTRODES,clamp,rand}from'./signal.js';
const $=(s,r=document)=>r.querySelector(s);
function head(title,desc,label){return`<div class="head"><div><div class="eyebrow">${label}</div><h1>${title}</h1><p>${desc}</p></div></div>`}
const topo=ELECTRODES.map(e=>({...e,x:(e.x-100)/88,y:(e.y-100)/88}));
function values(measure,preset){const out={};for(const e of topo){const front=e.region==='frontal',occ=e.region==='occipital',par=e.region==='parietal';let v=rand(-0.25,0.25);if(measure==='alpha'){const spatial=occ?1.8:(par?0.8:0.2);v+=spatial*(preset==='closed'?1.5:0.6)}if(measure==='theta')v+=(front?0.8:0.3)+(preset==='dementia'?1.25:0);if(measure==='tbr')v+=(front?1.2:0.5)+(preset==='adhd'?0.7:0);if(measure==='zalpha')v+=(occ?-1.1:-0.2)+(preset==='dementia'?-0.8:0);out[e.id]=v}return out}
function cmap(v,min,max){const t=clamp((v-min)/Math.max(max-min,0.001),0,1);if(t<0.5){const q=t*2;return[49+(247-49)*q,91+(247-91)*q,185+(247-185)*q]}const q=(t-0.5)*2;return[247+(196-247)*q,247+(60-247)*q,247+(49-247)*q]}
function interpret(measure,preset,vals){const sorted=Object.entries(vals).sort((a,b)=>b[1]-a[1]),hi=sorted.slice(0,3).map(x=>x[0]).join(', '),lo=sorted.slice(-3).map(x=>x[0]).join(', ');const what={alpha:'Mapa pokazuje przestrzenny rozkład mocy alfa. Przy oczach zamkniętych większa aktywność potyliczna jest typowym przykładem reaktywności rytmu alfa.',theta:'Mapa theta pozwala szybko zobaczyć, czy wolniejsza aktywność jest bardziej czołowa, rozlana czy lokalna.',tbr:'Theta/beta ratio przedstawia relację dwóch zakresów częstotliwości. Może ujawnić różnice przestrzenne, ale sam wskaźnik nie jest samodzielnym markerem diagnostycznym.',zalpha:'Mapa z-score pokazuje, o ile odchyleń standardowych wynik różni się od odpowiedniej normy w każdej elektrodzie.'}[measure];return `${what} W tym przykładzie najwyższe wartości są w <b>${hi}</b>, a najniższe w <b>${lo}</b>. Kolor ułatwia dostrzeżenie wzorca przestrzennego, którego trudno byłoby wychwycić z samej tabeli 19 liczb.`}
function draw(){const m=$('#mheat');if(!m)return;const measure=$('#heatmeasure',m).value,preset=$('#heatpreset',m).value,vals=values(measure,preset),arr=Object.values(vals),min=Math.min(...arr),max=Math.max(...arr);const cv=$('#heatcv',m),ctx=cv.getContext('2d'),W=cv.width,H=cv.height,cx=W/2,cy=H/2,R=250,img=ctx.createImageData(W,H);for(let y=0;y<H;y+=2){for(let x=0;x<W;x+=2){const nx=(x-cx)/R,ny=(y-cy)/R;if(nx*nx+ny*ny<=1){let num=0,den=0;for(const e of topo){const d2=(nx-e.x)**2+(ny-e.y)**2+0.012,w=1/(d2*d2);num+=vals[e.id]*w;den+=w}const rgb=cmap(num/den,min,max).map(Math.round);for(let yy=0;yy<2;yy++){for(let xx=0;xx<2;xx++){const px=x+xx,py=y+yy;if(px<W&&py<H){const ii=(py*W+px)*4;img.data[ii]=rgb[0];img.data[ii+1]=rgb[1];img.data[ii+2]=rgb[2];img.data[ii+3]=255}}}}}}ctx.clearRect(0,0,W,H);ctx.putImageData(img,0,0);ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--muted').trim()||'#50666c';ctx.lineWidth=3;ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(cx-25,cy-R+5);ctx.lineTo(cx,cy-R-22);ctx.lineTo(cx+25,cy-R+5);ctx.stroke();for(const e of topo){const x=cx+e.x*R,y=cy+e.y*R;ctx.fillStyle='#fff';ctx.strokeStyle='#33484e';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y,10,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#17282d';ctx.font='700 11px IBM Plex Mono';ctx.textAlign='center';ctx.fillText(e.id,x,y+4)}$('#heatvals',m).innerHTML=ELECTRODES.map(e=>`<div class="electrode-value heat-electrode"><span>${e.id}</span><b>${vals[e.id].toFixed(2)}</b></div>`).join('');$('#heatinterpret',m).innerHTML=interpret(measure,preset,vals)}
function build(){const m=document.createElement('section');m.id='mheat';m.className='module';m.innerHTML=head('qEEG HeatMap','Topografia qEEG zamienia tabelę wartości z poszczególnych elektrod w przestrzenny obraz rozkładu cechy na skórze głowy. Ułatwia zauważenie asymetrii, ogniskowości i gradientów przód–tył.','qEEG HEATMAP')+`<div class="heatmap-top-row"><div class="panel heatmap-explain-panel"><h2><span class="dot"></span>Co daje taka mapa?</h2><p class="readout heatmap-compact-copy">Każda elektroda ma jedną wartość, np. moc alfa albo z-score. HeatMap interpoluje wartości pomiędzy elektrodami i pokazuje ich <b>wzorzec przestrzenny</b>. Ułatwia zauważenie przewagi potylicznej, asymetrii lub rozlanego spowolnienia. To nadal mapa skalpu, a nie bezpośrednia lokalizacja źródła neuronalnego.</p></div><div class="panel heatmap-control-panel"><div class="heatmap-tools"><label class="compact-field">Miara <select id="heatmeasure"><option value="alpha">moc alfa</option><option value="theta">moc theta</option><option value="tbr">theta/beta ratio</option><option value="zalpha">z-score alfa</option></select></label><label class="compact-field">Profil <select id="heatpreset"><option value="open">oczy otwarte</option><option value="closed">oczy zamknięte</option><option value="dementia">przykład spowolnienia</option><option value="adhd">przykład TBR</option></select></label><button class="btn primary" id="heatnew">Wygeneruj nowy przykład</button></div></div></div><div class="heatmap-wrap heatmap-raised"><div class="panel"><canvas class="heatmap-canvas" id="heatcv" width="650" height="650"></canvas><div class="scale-bar"></div><div class="legend"><span>niebieski: niżej</span><span>biały: środek skali</span><span>czerwony: wyżej</span></div><div class="readout" id="heatinterpret" style="margin-top:12px"></div></div><div><div class="panel"><h2><span class="dot"></span>Wartości elektrod</h2><div class="electrode-values heat-electrode-values" id="heatvals"></div></div><div class="panel" style="margin-top:14px"><h2><span class="dot"></span>Jak to czytać?</h2><p class="readout">1. Najpierw sprawdź skalę i jednostkę. 2. Zobacz, gdzie występują maksima i minima. 3. Oceń, czy wzorzec jest lokalny, rozlany czy asymetryczny. 4. Dopiero potem odnoś go do warunku eksperymentalnego lub normy. 5. Nie utożsamiaj obszaru koloru z dokładnym źródłem korowym.</p></div></div></div>`;$('#main').appendChild(m);$('#heatnew',m).onclick=draw;$('#heatmeasure',m).onchange=draw;$('#heatpreset',m).onchange=draw;draw()}
window.addEventListener('load',build,{once:true});
window.addEventListener('eeg:theme',()=>requestAnimationFrame(draw));
window.addEventListener('eeg:module',e=>{if(e.detail==='mheat')requestAnimationFrame(draw)});
