const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const QUESTIONS=[
 {cat:'Rytmy EEG',q:'W odprowadzeniach O1 i O2 po zamknięciu oczu wzrasta moc oscylacji około 10 Hz. Któremu rytmowi EEG odpowiada taki wzorzec?',o:['Rytm delta','Rytm theta','Rytm alfa','Rytm beta'],a:2,e:'Rytm alfa obejmuje zwykle zakres 8–13 Hz i w spoczynku jest najsilniejszy w okolicach potylicznych przy zamkniętych oczach.'},
 {cat:'Artefakty',q:'W odprowadzeniach czołowych pojawia się wolna, wysokonapięciowa defleksja zsynchronizowana z mrugnięciem. Jakie jest najbardziej prawdopodobne źródło tego sygnału?',o:['Aktywność mięśni żwaczy (EMG)','Potencjał okoruchowy związany z mrugnięciem (EOG)','Zakłócenie sieciowe 50 Hz','Składowa P300'],a:1,e:'Mrugnięcie powoduje zmianę potencjału rejestrowaną jako artefakt EOG, zwykle o największej amplitudzie w odprowadzeniach czołowych.'},
 {cat:'Artefakty',q:'Podczas zaciskania szczęki w zapisie narasta szerokopasmowa aktywność wysokoczęstotliwościowa, szczególnie w odprowadzeniach skroniowych. Co jest jej najbardziej prawdopodobnym źródłem?',o:['Rytm alfa','Aktywność mięśniowa (EMG)','Wolny dryf potencjału elektrody','Rytm theta'],a:1,e:'Aktywność mięśniowa ma szerokie widmo częstotliwości i może istotnie zanieczyszczać zwłaszcza zakres beta oraz gamma.'},
 {cat:'Próbkowanie',q:'Sygnał jest próbkowany z częstotliwością 100 Hz, a analizowana składowa ma częstotliwość 70 Hz. Jakie zjawisko wystąpi?',o:['Dryf linii podstawowej','Aliasing, czyli błędne odwzorowanie częstotliwości','Nasycenie toru pomiarowego','Zmiana układu odniesienia'],a:1,e:'Dla częstotliwości próbkowania 100 Hz częstotliwość Nyquista wynosi 50 Hz. Składowa 70 Hz zostanie więc błędnie odwzorowana jako składowa o niższej częstotliwości.'},
 {cat:'Potencjały wywołane',q:'Dlaczego uśrednianie wielu epok poprawia stosunek sygnału do szumu składowej P300?',o:['Wzmacnia wszystkie składowe w jednakowym stopniu','Osłabia aktywność zsynchronizowaną z bodźcem','Aktywność zsynchronizowana czasowo ze zdarzeniem sumuje się zgodnie, natomiast aktywność nieskorelowana ulega częściowemu zniesieniu','Eliminuje potrzebę korekcji linii podstawowej'],a:2,e:'Składowa P300 jest związana czasowo ze zdarzeniem, dlatego jej przebieg sumuje się między próbami bardziej zgodnie niż aktywność nieskorelowana i szum.'},
 {cat:'EEG kliniczne',q:'Czy brak wyładowań padaczkokształtnych w pojedynczym rutynowym badaniu EEG wyklucza rozpoznanie padaczki?',o:['Tak, zawsze','Tak, jeżeli zapis trwał ponad 20 minut','Nie','Tylko u osób dorosłych'],a:2,e:'Prawidłowy rutynowy zapis EEG nie wyklucza padaczki. Wynik EEG interpretuje się łącznie z obrazem klinicznym i pozostałymi danymi diagnostycznymi.'},
 {cat:'EEG kliniczne',q:'Jak należy interpretować podwyższony stosunek mocy theta do beta (TBR) u osoby ocenianej w kierunku ADHD?',o:['Jako samodzielny marker diagnostyczny','Jako wynik wystarczający do potwierdzenia ADHD','Jako potencjalny korelat obserwowany na poziomie grupowym, wymagający interpretacji w szerszym kontekście','Jako równoważnik badania neuropsychologicznego'],a:2,e:'TBR nie jest samodzielnym markerem diagnostycznym ADHD. Korelat obserwowany na poziomie grupowym nie jest równoznaczny z markerem diagnostycznym u pojedynczej osoby.'},
 {cat:'qEEG',q:'Wartość standaryzowana z dla mocy alfa wynosi −2,2 względem bazy normatywnej. Jaki wniosek jest uzasadniony?',o:['Wynik sam w sobie dowodzi patologii','Jest to odchylenie od średniej bazy normatywnej, wymagające oceny jakości danych i kontekstu','Wynik wskazuje lokalizację źródła neuronalnego','Wynik jest niezależny od zastosowanego układu odniesienia'],a:1,e:'Wartość z zależy od procedury przetwarzania, jakości danych, stanu badanego, układu odniesienia oraz właściwości bazy normatywnej.'},
 {cat:'Topografia EEG',q:'Co przedstawia mapa topograficzna cechy qEEG?',o:['Bezpośrednią lokalizację generatorów neuronalnych','Interpolowany przestrzenny rozkład wartości mierzonej cechy na powierzchni głowy','Obraz strukturalny rezonansu magnetycznego','Wyłącznie impedancję elektrod'],a:1,e:'Mapa topograficzna przedstawia interpolowany rozkład wartości zmierzonych w elektrodach. Nie jest bezpośrednią mapą źródeł aktywności neuronalnej.'},
 {cat:'Przetwarzanie wstępne',q:'Dlaczego w analizie EEG należy raportować zastosowany układ odniesienia?',o:['Ponieważ wpływa na wartości potencjałów w poszczególnych kanałach i ich rozkład przestrzenny','Ponieważ zmienia anatomię mózgu','Ponieważ zwiększa fizyczną amplitudę źródła neuronalnego','Ponieważ zastępuje filtrację sygnału'],a:0,e:'EEG rejestruje różnice potencjałów. Wybór układu odniesienia wpływa więc na wartości kanałów oraz na obserwowaną topografię napięcia.'},
 {cat:'Analiza widmowa',q:'Jak wydłużenie analizowanego odcinka sygnału wpływa na rozdzielczość częstotliwościową dyskretnej transformaty Fouriera?',o:['Pogarsza ją','Poprawia ją','Nie wpływa na nią','Zależy wyłącznie od liczby elektrod'],a:1,e:'Odstęp między kolejnymi częstotliwościami widma jest w przybliżeniu równy 1/T, dlatego dłuższy odcinek sygnału zapewnia drobniejszą rozdzielczość częstotliwościową.'},
 {cat:'EEG kliniczne',q:'Jaki kierunek zmian w spoczynkowym EEG jest często opisywany w chorobie Alzheimera i części innych zespołów otępiennych?',o:['Przesunięcie mocy ku wyższym częstotliwościom z dominacją gamma','Spowolnienie czynności podstawowej: większy udział theta i delta oraz osłabienie lub zwolnienie rytmu alfa','Stała aktywność 50 Hz','Wyłącznie wzrost mocy beta'],a:1,e:'W wielu zespołach otępiennych opisuje się spowolnienie czynności podstawowej EEG, jednak jego nasilenie i charakter zależą od etiologii oraz stadium choroby.'},
 {cat:'Fizjologia EEG',q:'Który mechanizm w największym stopniu przyczynia się do powstawania sygnału EEG rejestrowanego na skórze głowy?',o:['Potencjały czynnościowe pojedynczych neuronów ruchowych','Sumowanie zsynchronizowanych potencjałów postsynaptycznych dużych populacji neuronów korowych','Zmiany przepływu krwi mierzone bezpośrednio przez elektrodę','Aktywność wyłącznie jąder wzgórza'],a:1,e:'EEG powierzchniowe odzwierciedla przede wszystkim zsynchronizowaną aktywność postsynaptyczną dużych populacji neuronów, szczególnie komórek piramidowych ułożonych podobnie względem powierzchni kory.'},
 {cat:'Fizjologia EEG',q:'Dlaczego pojedyncza elektroda EEG nie rejestruje wyłącznie aktywności kory znajdującej się bezpośrednio pod nią?',o:['Ponieważ przewodzenie objętościowe rozprowadza pola elektryczne przez tkanki głowy','Ponieważ elektroda mierzy wyłącznie temperaturę skóry','Ponieważ wszystkie neurony mózgu generują identyczny sygnał','Ponieważ sygnał EEG powstaje wyłącznie w mięśniach'],a:0,e:'Przewodzenie objętościowe powoduje, że potencjały generowane przez źródła neuronalne rozchodzą się przez mózg, płyn mózgowo-rdzeniowy, czaszkę i skórę.'},
 {cat:'Rytmy EEG',q:'Który opis najlepiej pasuje do aktywności beta?',o:['Wolne oscylacje około 0,5–4 Hz','Oscylacje około 13–30 Hz często związane z czuwaniem i aktywnością poznawczą','Wyłącznie rytm potyliczny po zamknięciu oczu','Składowa pojawiająca się wyłącznie podczas snu głębokiego'],a:1,e:'Zakres beta jest zwykle definiowany w przybliżeniu jako 13–30 Hz. Jego interpretacja zależy jednak od lokalizacji, stanu badanego i obecności artefaktów mięśniowych.'},
 {cat:'Rytmy EEG',q:'Dlaczego wzrost mocy w paśmie gamma należy interpretować szczególnie ostrożnie w EEG powierzchniowym?',o:['Ponieważ gamma nie może występować w mózgu człowieka','Ponieważ aktywność mięśniowa może silnie zwiększać moc w wysokich częstotliwościach','Ponieważ gamma zawsze oznacza padaczkę','Ponieważ filtry dolnoprzepustowe wzmacniają gamma'],a:1,e:'EMG ma szerokie widmo i może silnie zanieczyszczać zakres wysokich częstotliwości, dlatego wzrost mocy gamma wymaga kontroli artefaktów mięśniowych.'},
 {cat:'Akwizycja EEG',q:'Co oznacza wysoka impedancja elektrody w praktycznym pomiarze EEG?',o:['Zawsze poprawia stosunek sygnału do szumu','Może zwiększać podatność pomiaru na zakłócenia i niestabilność kontaktu','Nie ma żadnego znaczenia dla jakości pomiaru','Automatycznie zwiększa częstotliwość próbkowania'],a:1,e:'Niestabilny lub zbyt oporowy kontakt elektroda–skóra może zwiększać podatność toru pomiarowego na zakłócenia. Akceptowalne wartości zależą od zastosowanego wzmacniacza i technologii elektrod.'},
 {cat:'Akwizycja EEG',q:'Dlaczego podczas rejestracji EEG warto monitorować jakość kontaktu elektrod przed rozpoczęciem eksperymentu?',o:['Aby wykryć problemy, których późniejszy preprocessing może nie naprawić','Aby zwiększyć liczbę kanałów programowo','Aby wyeliminować potrzebę stosowania znaczników zdarzeń','Aby zmienić położenie źródeł neuronalnych'],a:0,e:'Problemy sprzętowe i kontaktowe mogą powodować utratę informacji lub silne artefakty. Nie każdy błąd rejestracji można wiarygodnie naprawić po zakończeniu badania.'},
 {cat:'Próbkowanie',q:'Jaka jest minimalna teoretyczna częstotliwość próbkowania dla sygnału zawierającego składowe do 40 Hz zgodnie z twierdzeniem Nyquista?',o:['20 Hz','40 Hz','80 Hz','160 Hz'],a:2,e:'Częstotliwość próbkowania musi być większa niż dwukrotność najwyższej analizowanej częstotliwości. Dla 40 Hz granica teoretyczna wynosi 80 Hz, choć w praktyce stosuje się zapas i filtr antyaliasingowy.'},
 {cat:'Próbkowanie',q:'Jaki jest główny cel filtra antyaliasingowego przed próbkowaniem sygnału?',o:['Usunięcie wszystkich artefaktów EOG','Ograniczenie składowych powyżej pasma, które mogłyby zostać odwzorowane jako niższe częstotliwości','Zmiana referencji EEG','Wykrycie komponentu P300'],a:1,e:'Filtr antyaliasingowy ogranicza wysokie częstotliwości przed dyskretyzacją, aby nie zostały błędnie odwzorowane w niższym zakresie widma.'},
 {cat:'Filtracja',q:'Jakie ryzyko wiąże się z zastosowaniem zbyt agresywnego filtra górnoprzepustowego w analizie ERP?',o:['Może zniekształcić wolne komponenty i kształt odpowiedzi czasowej','Zawsze usuwa wyłącznie zakłócenia sieciowe','Nie wpływa na kształt sygnału','Zwiększa liczbę elektrod'],a:0,e:'Zbyt wysoka częstotliwość odcięcia filtra górnoprzepustowego może zniekształcać wolne składowe ERP, ich amplitudę i przebieg czasowy.'},
 {cat:'Filtracja',q:'Do czego najczęściej służy filtr notch 50 Hz w warunkach europejskiej sieci energetycznej?',o:['Do usuwania rytmu alfa','Do tłumienia zakłócenia sieciowego około 50 Hz','Do wzmacniania P300','Do usuwania wszystkich artefaktów mięśniowych'],a:1,e:'Filtr notch może ograniczać wąskopasmowe zakłócenie sieciowe około 50 Hz. Należy jednak kontrolować wpływ filtra na analizowane pasmo.'},
 {cat:'Przetwarzanie wstępne',q:'Dlaczego kolejność etapów preprocessingu EEG powinna być jawnie udokumentowana?',o:['Ponieważ kolejność operacji może wpływać na wynik końcowy i jego odtwarzalność','Ponieważ kolejność nigdy nie wpływa na dane','Wyłącznie ze względów estetycznych','Aby uniknąć zapisywania częstotliwości próbkowania'],a:0,e:'Filtrowanie, rereferencja, interpolacja, odrzucanie fragmentów i ICA mogą wzajemnie wpływać na swoje działanie. Reprodukowalność wymaga raportowania ich kolejności i parametrów.'},
 {cat:'Przetwarzanie wstępne',q:'Co jest najlepszą praktyką po zastosowaniu automatycznego algorytmu odrzucania artefaktów?',o:['Zaakceptować wynik bez kontroli','Sprawdzić dane przed i po operacji oraz zweryfikować, czy nie usunięto użytecznego sygnału','Usunąć dodatkowo wszystkie kanały','Zawsze zastosować ten sam próg dla każdego rodzaju badania'],a:1,e:'Automatyczna procedura powinna być kontrolowana jakościowo. Celem jest ograniczenie artefaktów przy zachowaniu sygnału istotnego dla analizowanej hipotezy.'},
 {cat:'Referencja EEG',q:'Co pozostaje fizjologicznie niezmienne po zmianie referencji EEG?',o:['Źródła bioelektryczne w mózgu w momencie pomiaru','Wartość napięcia każdego kanału','Topografia napięcia na wszystkich wykresach','Amplituda każdego komponentu względem zera'],a:0,e:'Rereferencja zmienia matematyczny opis kanałów, ale nie zmienia aktywności neuronalnej, która wystąpiła podczas rejestracji.'},
 {cat:'Referencja EEG',q:'Dlaczego określenie „elektroda zerowa” jest mylące w EEG?',o:['Ponieważ każda referencja również ma pewien potencjał elektryczny','Ponieważ elektrody nie mierzą napięcia','Ponieważ referencja zawsze znajduje się poza głową','Ponieważ EEG nie wymaga różnicy potencjałów'],a:0,e:'EEG jest pomiarem różnicy potencjałów. Elektroda referencyjna nie jest fizycznym punktem o absolutnym potencjale równym zero.'},
 {cat:'Artefakty',q:'Który wzorzec najbardziej sugeruje artefakt ruchowy elektrody?',o:['Nagły duży skok lub wolny dryf ograniczony do jednego lub kilku kanałów','Stabilny rytm alfa około 10 Hz w O1 i O2','Powtarzalna P300 około 350 ms po bodźcu','Symetryczna aktywność potyliczna przy zamkniętych oczach'],a:0,e:'Ruch lub pogorszenie kontaktu elektrody może wywołać nagłe przesunięcia potencjału, dryf oraz niestabilność szczególnie widoczną w pojedynczych kanałach.'},
 {cat:'Artefakty',q:'Dlaczego artefakt EOG jest zwykle silniejszy w kanałach czołowych?',o:['Oczy stanowią źródło potencjału elektrycznego położone blisko elektrod czołowych','Kanały czołowe mają zawsze większe wzmocnienie','Płat czołowy generuje wyłącznie artefakty','EOG powstaje w elektrodzie referencyjnej'],a:0,e:'Gałka oczna zachowuje się w przybliżeniu jak dipol elektryczny. Zmiany związane z ruchem oka i mruganiem są więc szczególnie silne w elektrodach położonych blisko oczu.'},
 {cat:'ICA',q:'Który zestaw informacji najlepiej uzasadnia oznaczenie komponentu ICA jako artefaktu mrugania?',o:['Czołowa topografia, duże wolne defleksje i zbieżność czasowa z mrugnięciami','Wyłącznie wysoki numer komponentu','Najniższa wariancja komponentu','Obecność piku dokładnie 10 Hz'],a:0,e:'Identyfikacja komponentu artefaktowego powinna opierać się na zgodności kilku niezależnych cech, np. topografii, przebiegu czasowego, widma i związku ze zdarzeniem fizjologicznym.'},
 {cat:'ICA',q:'Dlaczego nie należy automatycznie usuwać wszystkich komponentów ICA sklasyfikowanych jako „mięśniowe” przez algorytm?',o:['Klasyfikacja automatyczna może się mylić i wymaga kontroli','Ponieważ ICA nie działa na EEG','Ponieważ komponenty mięśniowe są zawsze sygnałem neuronalnym','Ponieważ usunięcie komponentu nie zmienia danych'],a:0,e:'Automatyczne etykiety są pomocą decyzyjną. Błędne odrzucenie komponentu może usunąć część użytecznego sygnału neuronalnego.'},
 {cat:'Potencjały wywołane',q:'Co oznacza korekcja linii podstawowej w typowej analizie ERP?',o:['Odniesienie amplitudy epoki do średniej wartości w wybranym okresie przed zdarzeniem','Usunięcie wszystkich częstotliwości poniżej 1 Hz','Zmianę montażu na bipolarny','Uśrednienie wszystkich elektrod'],a:0,e:'W korekcji baseline od wartości epoki odejmuje się zwykle średni poziom z ustalonego przedziału przed bodźcem, aby ujednolicić punkt odniesienia amplitudy.'},
 {cat:'Potencjały wywołane',q:'Co może się stać, jeśli znaczniki bodźców mają losowy jitter czasowy względem rzeczywistej prezentacji?',o:['Uśredniony ERP może zostać spłaszczony lub poszerzony czasowo','ERP zawsze zwiększy amplitudę','Jitter poprawi rozdzielczość czasową','Nie będzie miał znaczenia dla analizy czasowej'],a:0,e:'Jeżeli epoki są wyrównywane względem niedokładnych znaczników, ten sam komponent pojawia się w różnych miejscach osi czasu i częściowo znosi się podczas uśredniania.'},
 {cat:'Oddball',q:'Który element paradygmatu oddball jest kluczowy dla uzyskania klasycznej odpowiedzi P3/P300?',o:['Różnica prawdopodobieństwa i znaczenia bodźców, zwłaszcza rzadkiego bodźca docelowego','Stała prezentacja tylko jednego bodźca','Brak jakiegokolwiek zadania uczestnika w każdej odmianie paradygmatu','Losowa zmiana częstotliwości próbkowania EEG'],a:0,e:'P3 jest często silniejsza dla rzadkich, istotnych lub wymagających reakcji zdarzeń. Dokładna postać zależy od odmiany paradygmatu i zadania.'},
 {cat:'Oddball',q:'Dlaczego pojedynczej próby oddball zwykle nie należy używać do pewnej identyfikacji P300 wzrokowo?',o:['Ponieważ pojedynczy przebieg zawiera dużo aktywności nieskorelowanej i szumu','Ponieważ P300 występuje zawsze przed bodźcem','Ponieważ P300 ma częstotliwość dokładnie 300 Hz','Ponieważ ERP można analizować wyłącznie w domenie przestrzennej'],a:0,e:'ERP ma zwykle znacznie mniejszą amplitudę niż bieżące EEG, dlatego jego typowy kształt ujawnia się przede wszystkim po odpowiednim uśrednieniu wielu prób.'},
 {cat:'Eksperyment Stroopa',q:'Jak najtrafniej obliczyć efekt interferencji Stroopa na podstawie czasu reakcji?',o:['Średni czas prób niezgodnych minus średni czas prób zgodnych','Średni czas wszystkich prób pomnożony przez liczbę błędów','Najkrótszy czas reakcji minus najdłuższy','Wyłącznie liczba prób zgodnych'],a:0,e:'Typowa miara interferencji porównuje reakcje w warunku konfliktowym i zgodnym. Dodatnia różnica oznacza wolniejsze reakcje dla prób niezgodnych.'},
 {cat:'Eksperyment Stroopa',q:'Dlaczego wynik pojedynczej próby Stroopa ma niewielką wartość diagnostyczną?',o:['Czas reakcji pojedynczej odpowiedzi ma dużą zmienność i zależy od wielu czynników','Ponieważ efekt Stroopa nie istnieje','Ponieważ czas reakcji nie może być mierzony komputerowo','Ponieważ jedna próba zawsze jest zgodna'],a:0,e:'Wnioski opiera się na rozkładzie wielu obserwacji i porównaniu warunków. Pojedyncza odpowiedź jest silnie podatna na przypadkową zmienność.'},
 {cat:'Analiza widmowa',q:'Co przedstawia gęstość widmowa mocy (PSD)?',o:['Rozkład mocy sygnału w funkcji częstotliwości','Położenie elektrod w przestrzeni 3D','Rozkład czasu reakcji uczestnika','Wyłącznie amplitudę maksymalną sygnału'],a:0,e:'PSD opisuje, jak moc sygnału jest rozłożona w zakresie częstotliwości. Jest podstawowym narzędziem analizy rytmów EEG.'},
 {cat:'Analiza widmowa',q:'Dlaczego porównywanie mocy względnej i bezwzględnej może prowadzić do różnych wniosków?',o:['Moc względna jest udziałem danego pasma w mocy całkowitej i zależy również od zmian w innych pasmach','Obie wielkości są zawsze identyczne','Moc względna nie zależy od żadnego innego pasma','Moc bezwzględna nie ma jednostek'],a:0,e:'Moc względna normalizuje moc pasma względem pewnej mocy całkowitej. Jej zmiana może więc wynikać zarówno ze zmian analizowanego pasma, jak i pozostałej części widma.'},
 {cat:'qEEG',q:'Co jest konieczne, aby sensownie interpretować wynik z-score z bazy normatywnej qEEG?',o:['Zgodność procedury pomiarowej i przetwarzania z warunkami, dla których przygotowano normę','Wyłącznie znajomość wieku badacza','Brak informacji o referencji','Tylko liczba elektrod większa niż 2'],a:0,e:'Porównanie normatywne ma sens tylko wtedy, gdy dane badanego są porównywalne metodologicznie z bazą odniesienia, m.in. pod względem preprocessing’u, wieku i warunków rejestracji.'},
 {cat:'qEEG',q:'Co oznacza fakt, że cecha qEEG różni się statystycznie pomiędzy dwiema grupami klinicznymi?',o:['Nie oznacza automatycznie, że cecha dobrze klasyfikuje pojedyncze osoby','Dowodzi stuprocentowej trafności diagnostycznej','Oznacza, że rozkłady obu grup nie nakładają się','Eliminuje potrzebę walidacji na niezależnych danych'],a:0,e:'Istotna różnica średnich może współistnieć z dużym nakładaniem się rozkładów. Trafność indywidualnej klasyfikacji wymaga osobnej oceny czułości, swoistości i walidacji.'},
 {cat:'Topografia EEG',q:'Dlaczego przy porównywaniu dwóch heatmap EEG należy używać tej samej skali kolorów?',o:['Aby różnice barwy odpowiadały porównywalnym różnicom wartości','Ponieważ skala kolorów zmienia fizyczny sygnał EEG','Aby zwiększyć liczbę elektrod','Ponieważ interpolacja przestaje wtedy działać'],a:0,e:'Automatyczne skalowanie każdej mapy osobno może wizualnie wyolbrzymiać niewielkie różnice lub ukrywać duże. Wspólna skala umożliwia uczciwe porównanie.'},
 {cat:'Źródła EEG',q:'Dlaczego lokalizacja źródeł EEG jest problemem niedookreślonym?',o:['Wiele różnych konfiguracji źródeł może prowadzić do podobnego rozkładu potencjałów na skórze głowy','Ponieważ EEG nie mierzy napięcia','Ponieważ istnieje tylko jedno możliwe źródło każdego sygnału','Ponieważ liczba elektrod zawsze wynosi jeden'],a:0,e:'Problem odwrotny EEG nie ma jednego rozwiązania bez dodatkowych założeń. Dlatego stosuje się modele głowy, regularizację i ograniczenia przestrzeni rozwiązań.'},
 {cat:'Źródła EEG',q:'Co może poprawić wiarygodność estymacji źródeł EEG?',o:['Dokładniejsza geometria elektrod i indywidualny model głowy','Usunięcie informacji o położeniu elektrod','Zmniejszenie liczby kanałów do jednego','Zastąpienie EEG samą heatmapą kolorów'],a:0,e:'Dokładna lokalizacja elektrod, model przewodnictwa i geometria głowy ograniczają część niepewności rozwiązania problemu odwrotnego.'},
 {cat:'Eye tracking',q:'Czym jest fiksacja w analizie eye-trackingowej?',o:['Okresem względnie stabilnego spojrzenia w ograniczonym obszarze','Każdym mrugnięciem oka','Wyłącznie ruchem sakkadowym','Błędem kalibracji kamery'],a:0,e:'Fiksacja oznacza okres, w którym punkt spojrzenia pozostaje względnie stabilny w określonym obszarze, choć konkretna definicja zależy od zastosowanego algorytmu detekcji.'},
 {cat:'Eye tracking',q:'Dlaczego długa fiksacja na elemencie interfejsu nie jest jednoznacznym dowodem dużego zainteresowania?',o:['Może wynikać także z trudności przetwarzania, dezorientacji lub właściwości zadania','Ponieważ fiksacje nie mają żadnego związku z widzeniem','Ponieważ długość fiksacji jest zawsze losowa','Ponieważ eye tracking mierzy wyłącznie ruch głowy'],a:0,e:'Czas fiksacji jest wskaźnikiem zachowania wzrokowego, ale jego znaczenie wymaga kontekstu. Dłuższa fiksacja może oznaczać zainteresowanie, trudność, potrzebę dokładniejszej analizy lub inne procesy.'},
 {cat:'Eye tracking',q:'Co traci typowa zagregowana heatmapa spojrzeń względem pełnego scanpath?',o:['Informację o kolejności przechodzenia wzroku między obszarami','Informację o liczbie pikseli ekranu','Informację o kolorze tła','Całą informację o miejscach fiksacji'],a:0,e:'Heatmapa dobrze pokazuje zagęszczenie obserwacji, ale zwykle nie zachowuje temporalnej kolejności fiksacji i sakkad.'},
 {cat:'Fizjologia obwodowa',q:'Który sygnał zwykle reaguje najwolniej po krótkim nagłym bodźcu?',o:['EDA/GSR','EMG','Sygnał cyfrowego przycisku odpowiedzi','Znacznik zdarzenia'],a:0,e:'Odpowiedź elektrodermalna rozwija się relatywnie wolno, ponieważ zależy od aktywacji współczulnej i zmian przewodnictwa skóry związanych z gruczołami potowymi.'},
 {cat:'Fizjologia obwodowa',q:'Z czego oblicza się podstawową miarę zmienności rytmu serca HRV?',o:['Z kolejnych odstępów między uderzeniami serca, np. odstępów R–R','Z amplitudy rytmu alfa','Z liczby elektrod EEG','Z temperatury ekranu'],a:0,e:'HRV opiera się na zmienności kolejnych odstępów między pobudzeniami serca. W EKG często wykorzystuje się czasy pomiędzy kolejnymi załamkami R.'},
 {cat:'Projektowanie eksperymentu',q:'Dlaczego kolejność warunków eksperymentalnych warto randomizować lub równoważyć?',o:['Aby ograniczyć systematyczny wpływ kolejności, uczenia się i zmęczenia','Aby zwiększyć impedancję elektrod','Aby usunąć potrzebę grupy kontrolnej w każdym badaniu','Aby zmienić częstotliwość Nyquista'],a:0,e:'Stała kolejność warunków może mieszać efekt badanego czynnika z efektami czasu, uczenia, habituacji lub zmęczenia.'},
 {cat:'Projektowanie eksperymentu',q:'Po co stosuje się znaczniki zdarzeń synchronizowane z EEG?',o:['Aby powiązać próbki sygnału z dokładnym czasem bodźców i odpowiedzi','Aby zwiększyć fizyczną amplitudę EEG','Aby automatycznie diagnozować uczestnika','Aby zastąpić częstotliwość próbkowania'],a:0,e:'Znaczniki zdarzeń umożliwiają segmentację i analizę sygnału względem bodźców, odpowiedzi lub innych zdarzeń eksperymentalnych.'},
 {cat:'Reprodukowalność',q:'Który zestaw informacji jest najbardziej potrzebny do odtworzenia analizy EEG?',o:['Surowe dane, metadane, kod lub dokładny pipeline i jego parametry','Wyłącznie końcowy wykres','Tylko nazwisko osoby analizującej','Jedynie liczba uczestników'],a:0,e:'Reprodukowalność wymaga danych wejściowych oraz wystarczająco dokładnego opisu transformacji: kodu, wersji narzędzi, kolejności operacji i ich parametrów.'},
 {cat:'Formaty danych',q:'Dlaczego po konwersji danych EEG do innego formatu należy sprawdzić jednostki amplitudy?',o:['Format lub importer może stosować inne skalowanie, np. V zamiast µV','Jednostki nigdy nie mają znaczenia','Konwersja zawsze zmienia sygnał na EKG','Jednostki dotyczą tylko plików graficznych'],a:0,e:'Różne formaty i biblioteki mogą przechowywać napięcie w woltach, mikrowoltach lub z wykorzystaniem współczynników skalujących. Błędna interpretacja jednostek prowadzi do poważnych błędów analitycznych.'},
 {cat:'BIDS',q:'Jaka jest główna korzyść z organizacji danych EEG zgodnie z BIDS?',o:['Standaryzuje strukturę danych i metadanych, ułatwiając automatyzację i ponowne wykorzystanie','Automatycznie usuwa wszystkie artefakty','Zastępuje świadomą zgodę uczestników','Gwarantuje poprawność wszystkich analiz statystycznych'],a:0,e:'BIDS definiuje konwencje nazw, strukturę katalogów i pliki metadanych, dzięki czemu zbiory danych są bardziej jednoznaczne i łatwiejsze do przetwarzania przez różne narzędzia.'},
 {cat:'BIDS',q:'Dlaczego dane po preprocessingu powinny być odróżnione od danych surowych?',o:['Aby zachować możliwość powrotu do oryginalnego pomiaru i prześledzenia kolejnych transformacji','Ponieważ dane surowe należy zawsze usuwać','Ponieważ oba zbiory muszą mieć identyczną nazwę pliku','Aby uniemożliwić reprodukcję analizy'],a:0,e:'Rozdzielenie danych surowych i pochodnych chroni źródłowy pomiar oraz pozwala jednoznacznie śledzić, które wyniki powstały w wyniku określonego pipeline’u.'},
 {cat:'EEG kliniczne',q:'Które stwierdzenie najlepiej opisuje rolę qEEG w rozpoznawaniu zaburzeń psychicznych?',o:['Może dostarczać dodatkowych cech ilościowych, ale nie zastępuje standardowej diagnozy klinicznej','Samodzielnie potwierdza każde rozpoznanie psychiatryczne','Jest równoważne badaniu strukturalnemu MRI','Każdy wynik odbiegający o 2 SD oznacza chorobę'],a:0,e:'W psychiatrii większość cech qEEG ma ograniczoną swoistość na poziomie pojedynczej osoby. Mogą mieć znaczenie badawcze lub pomocnicze, ale interpretacja wymaga kontekstu klinicznego.'},
 {cat:'EEG kliniczne',q:'Dlaczego czułość i swoistość markera EEG powinny być oceniane na niezależnych danych?',o:['Aby sprawdzić, czy wynik generalizuje poza próbę, na której marker opracowano','Ponieważ walidacja zawsze obniża jakość modelu','Aby zwiększyć amplitudę sygnału','Ponieważ te miary nie zależą od populacji'],a:0,e:'Ocena na danych użytych do opracowania markera może być nadmiernie optymistyczna. Niezależna walidacja pozwala oszacować zdolność generalizacji.'},
 {cat:'Interpretacja',q:'Które stwierdzenie jest najbardziej poprawne metodologicznie?',o:['Najpierw należy określić pytanie badawcze, a następnie dobrać cechy EEG i pipeline analizy','Najpierw wybiera się najbardziej efektowną heatmapę, a potem tworzy hipotezę','Każdy pipeline jest równie dobry dla każdego pytania','Im więcej filtrów, tym bardziej wiarygodny wynik'],a:0,e:'Dobór preprocessing’u i cech powinien wynikać z pytania badawczego oraz właściwości sygnału. Pozwala to ograniczyć arbitralność i ryzyko nadinterpretacji.'},
 {cat:'Interpretacja',q:'Dlaczego korelacja między cechą EEG a wynikiem psychologicznym nie dowodzi związku przyczynowego?',o:['Korelacja nie wyklucza zmiennych zakłócających ani odwrotnego kierunku zależności','Ponieważ EEG nigdy nie koreluje z zachowaniem','Ponieważ każda korelacja jest błędem pomiarowym','Ponieważ przyczynowość można wykazać samą wartością p'],a:0,e:'Związek korelacyjny opisuje współzmienność, ale sam nie rozstrzyga mechanizmu przyczynowego. Potrzebny jest odpowiedni projekt badania i kontrola alternatywnych wyjaśnień.'}

];
const quiz={i:0,correct:0,wrong:0,answered:false,order:QUESTIONS.map((_,i)=>i)};
function current(){return QUESTIONS[quiz.order[quiz.i]]}
function render(){const m=$('#mquiz');if(!m)return;const q=current();$('#testcat',m).textContent=q.cat;$('#testpos',m).textContent=`${quiz.i+1}/${quiz.order.length}`;$('#testq',m).textContent=q.q;$('#testanswers',m).innerHTML=q.o.map((x,i)=>`<button class="test-answer" data-answer="${i}"><span>${String.fromCharCode(65+i)}</span><b>${x}</b></button>`).join('');$('#testfeedback',m).className='test-feedback hidden';$('#testfeedback',m).textContent='';$('#testnext',m).disabled=true;$('#testcorrect',m).textContent=quiz.correct;$('#testwrong',m).textContent=quiz.wrong;$('#testnumber',m).textContent=quiz.i+1;quiz.answered=false;$$('[data-answer]',m).forEach(b=>b.onclick=()=>answer(+b.dataset.answer))}
function answer(i){if(quiz.answered)return;quiz.answered=true;const m=$('#mquiz'),q=current(),ok=i===q.a;if(ok)quiz.correct++;else quiz.wrong++;$$('[data-answer]',m).forEach((b,j)=>{b.disabled=true;b.classList.toggle('correct',j===q.a);b.classList.toggle('wrong',j===i&&!ok)});const f=$('#testfeedback',m);f.className='test-feedback '+(ok?'ok':'bad');f.innerHTML=`<b>${ok?'Poprawna odpowiedź.':'Niepoprawna odpowiedź.'}</b> ${q.e}`;$('#testnext',m).disabled=false;$('#testcorrect',m).textContent=quiz.correct;$('#testwrong',m).textContent=quiz.wrong}
function next(){quiz.i=(quiz.i+1)%quiz.order.length;render()}
function reset(){quiz.i=0;quiz.correct=0;quiz.wrong=0;quiz.answered=false;quiz.order=QUESTIONS.map((_,i)=>i);render()}
function shuffle(){quiz.order.sort(()=>Math.random()-.5);quiz.i=0;quiz.correct=0;quiz.wrong=0;render()}
function build(){const m=document.createElement('section');m.id='mquiz';m.className='module';m.innerHTML=`<div class="head"><div><div class="eyebrow">SPRAWDŹ SIĘ</div><h1>Sprawdź się — pytania jednokrotnego wyboru</h1><p>Wybierz jedną poprawną odpowiedź. Po udzieleniu odpowiedzi otrzymasz krótkie wyjaśnienie.</p></div></div><div class="test-layout"><div class="panel test-main"><div class="flash-meta"><span id="testcat"></span><span id="testpos"></span></div><div class="test-question" id="testq"></div><div class="test-answers" id="testanswers"></div><div class="test-feedback hidden" id="testfeedback"></div><div class="row" style="margin-top:14px"><button class="btn primary" id="testnext" disabled>Następne pytanie</button></div></div><div><div class="panel"><h2><span class="dot"></span>Wynik</h2><div class="score-box"><div class="metric"><div class="k">POPRAWNE</div><div class="v" id="testcorrect">0</div></div><div class="metric"><div class="k">BŁĘDNE</div><div class="v" id="testwrong">0</div></div><div class="metric"><div class="k">PYTANIE</div><div class="v" id="testnumber">1</div></div></div><div class="row" style="margin-top:10px"><button class="btn" id="testshuffle">Losuj kolejność</button><button class="btn" id="testreset">Reset</button></div></div></div></div>`;$('#main').appendChild(m);$('#testnext',m).onclick=next;$('#testreset',m).onclick=reset;$('#testshuffle',m).onclick=shuffle;render()}
window.addEventListener('load',build,{once:true});