import{EEGEngine,welch,bandPower,clamp}from'./signal.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const engine=new EEGEngine();
const css=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const C=()=>({accent:css('--accent')||'#087f70',violet:css('--violet')||'#6954b8',muted:css('--muted')||'#5a7077',line:css('--line')||'#d5e0e3',well:css('--well')||'#f0f4f5'});
let active='',sigCycle=null,fftCycle=null,raf=0;
function sync(){const m=$('#m1x');if(!m)return;$$('[data-band]',m).forEach(x=>engine.setBand(x.dataset.band,x.value));const fs=$('#xfs',m);if(fs)engine.setFs(fs.value);const eyes=$('#xeyes',m);if(eyes)engine.eyesClosed=eyes.textContent.includes('zamknięte');const line=$('#xline',m);if(line)engine.lineNoise=+line.value}
function background(ctx,w,h,label=''){const c=C();ctx.clearRect(0,0,w,h);ctx.fillStyle=c.well;ctx.fillRect(0,0,w,h);ctx.strokeStyle=c.line;ctx.lineWidth=1;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(42,i*h/5);ctx.lineTo(w-8,i*h/5);ctx.stroke()}ctx.fillStyle=c.muted;ctx.font='10px IBM Plex Mono';if(label)ctx.fillText(label,w-68,h-7)}
function newSignalCycle(now=performance.now()){sync();sigCycle={start:now,data:engine.generate(4)};drawPSD(sigCycle.data)}
function drawSignal(now){const m=$('#m1x'),cv=$('#xeeg',m);if(!m?.classList.contains('active')||!cv)return;if(!sigCycle||now-sigCycle.start>=4000)newSignalCycle(now);const ids=['Fp1','Fz','Cz','Pz','O1','O2'],ctx=cv.getContext('2d'),c=C(),row=(cv.height-34)/ids.length,frac=clamp((now-sigCycle.start)/4000,0,1);background(ctx,cv.width,cv.height,'czas →');ids.forEach((id,k)=>{const a=sigCycle.data[id],last=Math.max(2,Math.floor(frac*(a.length-1))),mid=12+row*(k+.5);ctx.fillStyle=c.muted;ctx.font='10px IBM Plex Mono';ctx.fillText(id,7,mid+3);ctx.strokeStyle=c.accent;ctx.lineWidth=1.45;ctx.beginPath();for(let i=0;i<=last;i++){const x=46+i/(a.length-1)*(cv.width-58),y=mid-clamp(a[i],-90,90)/90*row*.42;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()})}
function drawPSD(data){const m=$('#m1x'),cv=$('#xpsd',m),read=$('#xread',m);if(!cv||!data)return;const p=welch(data.O1,engine.fs),ctx=cv.getContext('2d'),c=C();background(ctx,cv.width,cv.height,'Hz');const mx=Math.max(...p.filter(q=>q.f<=60).map(q=>q.p),1);ctx.strokeStyle=c.violet;ctx.lineWidth=2;ctx.beginPath();let first=true;p.forEach(q=>{if(q.f>60)return;const x=40+q.f/60*(cv.width-54),y=cv.height-27-q.p/mx*(cv.height-44);first?ctx.moveTo(x,y):ctx.lineTo(x,y);first=false});ctx.stroke();const bp={δ:bandPower(p,.5,4),θ:bandPower(p,4,8),α:bandPower(p,8,13),β:bandPower(p,13,30),γ:bandPower(p,30,55)},tot=Object.values(bp).reduce((a,b)=>a+b,0)||1;if(read)read.innerHTML=Object.entries(bp).map(([k,v])=>`${k}: <b>${(100*v/tot).toFixed(0)}%</b>`).join(' · ')+` · fs=<b>${engine.fs} Hz</b>`}
function newFftCycle(now=performance.now()){sync();const m=$('#mfft'),sec=+($('#fftlen',m)?.value||2),ch=$('#fftch',m)?.value||'O1';fftCycle={start:now,sec,ch,data:engine.generate(sec)[ch]};drawSpectrum()}
function drawFftTime(now){const m=$('#mfft'),cv=$('#ffttime',m);if(!m?.classList.contains('active')||!cv)return;const sec=+($('#fftlen',m)?.value||2),ch=$('#fftch',m)?.value||'O1';if(!fftCycle||fftCycle.sec!==sec||fftCycle.ch!==ch||now-fftCycle.start>=sec*1000)newFftCycle(now);const a=fftCycle.data,frac=clamp((now-fftCycle.start)/(sec*1000),0,1),last=Math.max(2,Math.floor(frac*(a.length-1))),ctx=cv.getContext('2d'),c=C();background(ctx,cv.width,cv.height,'czas [s]');ctx.strokeStyle=c.accent;ctx.lineWidth=1.5;ctx.beginPath();for(let i=0;i<=last;i++){const x=42+i/(a.length-1)*(cv.width-55),y=cv.height/2-clamp(a[i],-100,100)/100*(cv.height-50)/2;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();const info=$('#timeinfo',m);if(info)info.innerHTML=`<b>${ch}</b> · ${sec} s · ${a.length} próbek`}
function drawSpectrum(){const m=$('#mfft');if(!m||!fftCycle)return;const cv=$('#fftfreq',m),info=$('#fftinfo',m);if(!cv)return;const data=fftCycle.data,fs=engine.fs,n=Math.min(data.length,1024),windowed=($('#fftwin',m)?.value||'hann')==='hann'?data.map((v,i)=>v*(.5-.5*Math.cos(2*Math.PI*i/(data.length-1)))):data,spec=[];for(let f=1;f<=Math.min(60,Math.floor(fs/2)-1);f++){let re=0,im=0;for(let i=0;i<n;i++){const a=2*Math.PI*f*i/fs;re+=windowed[i]*Math.cos(a);im-=windowed[i]*Math.sin(a)}spec.push({f,p:(re*re+im*im)/n})}const ctx=cv.getContext('2d'),c=C();background(ctx,cv.width,cv.height,'Hz');const mx=Math.max(...spec.map(q=>q.p),1);ctx.strokeStyle=c.violet;ctx.lineWidth=2;ctx.beginPath();spec.forEach((q,i)=>{const x=42+q.f/60*(cv.width-55),y=cv.height-28-q.p/mx*(cv.height-45);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();if(info){const top=[...spec].sort((a,b)=>b.p-a.p).slice(0,4).map(q=>q.f+' Hz').join(', ');info.innerHTML=`Dominujące składowe: <b>${top}</b> · Δf ≈ <b>${(1/fftCycle.sec).toFixed(2)} Hz</b>`}}
function loop(now){if(active==='m1x')drawSignal(now);else if(active==='mfft')drawFftTime(now);raf=requestAnimationFrame(loop)}
function reset(){sigCycle=null;fftCycle=null}
window.addEventListener('load',()=>requestAnimationFrame(loop),{once:true});
window.addEventListener('eeg:artifact',e=>{engine.artifact(e.detail);sigCycle=null});
window.addEventListener('eeg:signal-settings',reset);
window.addEventListener('eeg:theme',reset);
window.addEventListener('eeg:module',e=>{active=e.detail;if(active==='m1x')sigCycle=null;if(active==='mfft')fftCycle=null});
window.addEventListener('beforeunload',()=>cancelAnimationFrame(raf));
