import{EEGEngine,ELECTRODES,clamp}from'./signal.js';
const $=(s,r=document)=>r.querySelector(s);const engine=new EEGEngine();
const head=(title,desc,label)=>`<div class="head"><div><div class="eyebrow">${label}</div><h1>${title}</h1><p>${desc}</p></div></div>`;
function save(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function saveText(name,text){save(name,new Blob([text],{type:'text/plain;charset=utf-8'}))}
function formatSection(title,ext,stores,tree,example,note=''){return`<section class="panel format-lesson"><h2><span class="dot"></span>${title} <code>${ext}</code></h2><p>${stores}</p><h3>Struktura</h3><pre class="format-tree">${tree}</pre><h3>Praktyczny przykład</h3><pre class="format-example">${example}</pre>${note?`<div class="module-note">${note}</div>`:''}</section>`}
function sample(sec=4,fs=250){engine.setFs(fs);const d=engine.generate(sec);return{fs,sec,d}}
function fw(v,n){return String(v).slice(0,n).padEnd(n,' ')}
function edfBlob(){const {fs,sec,d}=sample(),ids=ELECTRODES.map(e=>e.id),ns=ids.length,hb=256+ns*256,total=hb+sec*ns*fs*2,buf=new ArrayBuffer(total),view=new DataView(buf),enc=new TextEncoder();let header=fw('0',8)+fw('X Synthetic',80)+fw('EEG-Lab synthetic recording',80)+fw('16.09.26',8)+fw('12.00.00',8)+fw(hb,8)+fw('',44)+fw(sec,8)+fw('1',8)+fw(ns,4);const fields=[[16,id=>id],[80,()=> 'Ag/AgCl'],[8,()=> 'uV'],[8,()=> '-200'],[8,()=> '200'],[8,()=> '-32768'],[8,()=> '32767'],[80,()=> 'HP:0.5Hz LP:40Hz'],[8,()=> String(fs)],[32,()=> '']];for(const[len,fn]of fields)for(const id of ids)header+=fw(fn(id),len);new Uint8Array(buf).set(enc.encode(header).slice(0,hb));let off=hb;for(let r=0;r<sec;r++)for(const id of ids)for(let i=0;i<fs;i++){const uv=clamp(d[id][r*fs+i],-200,200);view.setInt16(off,Math.round(uv/200*32767),true);off+=2}return new Blob([buf],{type:'application/octet-stream'})}
function tsv(){const {fs,sec,d}=sample(),ids=['Fp1','Fz','Cz','Pz','O1','O2'],rows=['time\t'+ids.join('\t')];for(let i=0;i<fs*sec;i++)rows.push((i/fs).toFixed(4)+'\t'+ids.map(id=>d[id][i].toFixed(3)).join('\t'));return rows.join('\n')}
function brainHeader(){return`Brain Vision Data Exchange Header File Version 1.0\n[Common Infos]\nDataFile=sample.eeg\nMarkerFile=sample.vmrk\nDataFormat=BINARY\nDataOrientation=MULTIPLEXED\nNumberOfChannels=2\nSamplingInterval=4000\n\n[Binary Infos]\nBinaryFormat=INT_16\n\n[Channel Infos]\nCh1=Fp1,,0.1,uV\nCh2=O1,,0.1,uV\n`}
function brainMarkers(){return`Brain Vision Data Exchange Marker File, Version 1.0\n[Common Infos]\nDataFile=sample.eeg\n[Marker Infos]\nMk1=New Segment,,1,1,0\nMk2=Stimulus,S  1,251,1,0\n`}
function brainData(){const {fs,sec,d}=sample(),buf=new ArrayBuffer(fs*sec*2*2),v=new DataView(buf);let off=0;for(let i=0;i<fs*sec;i++)for(const id of['Fp1','O1']){v.setInt16(off,Math.round(clamp(d[id][i],-200,200)*10),true);off+=2}return new Blob([buf],{type:'application/octet-stream'})}
function buildFormats(){const m=document.createElement('section');m.id='mformats';m.className='module';m.innerHTML=head('Formaty plików EEG','Rejestratory EEG zapisują próbki i metadane w różnych formatach. Nazwy kanałów, jednostki, częstotliwość próbkowania i markery mogą znajdować się w jednym pliku albo w kilku plikach powiązanych ze sobą.','FORMATY PLIKÓW EEG')+`${formatSection('EDF / EDF+','.edf','EDF przechowuje nagłówek badania, opisy kanałów oraz rekordy próbek w jednym pliku. EDF+ dodatkowo definiuje mechanizm adnotacji.','recording.edf\n├─ nagłówek badania\n├─ nagłówki kanałów\n└─ rekordy danych','patient: X Synthetic\nchannels: 19\nfs: 250 Hz\nFp1: ...')}${formatSection('BDF / BDF+','.bdf','BDF wywodzi się z EDF i jest stosowany m.in. przez BioSemi. Typowo używa 24-bitowych próbek.','recording.bdf\n├─ nagłówek\n├─ opisy kanałów\n└─ próbki 24-bit','channel: Cz\nfs: 512 Hz\ndigital range: 24 bit')}${formatSection('BrainVision','.eeg + .vhdr + .vmrk','BrainVision rozdziela próbki, metadane i markery na trzy współpracujące pliki.','recording.eeg  → próbki binarne\nrecording.vhdr → metadane\nrecording.vmrk → zdarzenia','[Common Infos]\nDataFile=recording.eeg\nMarkerFile=recording.vmrk\nSamplingInterval=4000')}${formatSection('Formaty producentów','.eeg i inne','Rozszerzenie .eeg nie oznacza jednego uniwersalnego standardu. Interpretacja może zależeć od producenta oraz jego dokumentacji.','recording.eeg\n+ opcjonalny nagłówek\n+ opcjonalny plik zdarzeń','00 7F 21 ...\n→ bez specyfikacji nie wiadomo, które bajty oznaczają próbki lub markery','Samo rozszerzenie pliku nie wystarcza do bezpiecznej interpretacji danych.')}<div class="panel"><h2><span class="dot"></span>Przykładowe pliki</h2><div class="row"><button class="btn primary" id="dlEdf">EDF</button><button class="btn" id="dlTsv">TSV</button><button class="btn" id="dlEeg">BrainVision .eeg</button><button class="btn" id="dlVhdr">.vhdr</button><button class="btn" id="dlVmrk">.vmrk</button></div></div><div class="panel history-note"><h2><span class="dot"></span>Dlaczego standaryzacja jest ważna?</h2><p>Przez lata producenci aparatury tworzyli własne formaty i konwencje. Wymiana danych między laboratoriami bywała przez to bardzo uciążliwa: trzeba było ręcznie dopasowywać kanały, markery, jednostki, kolejność próbek i metadane albo pisać konwertery dla konkretnego systemu. Otwarte formaty i standardy organizacji danych znacząco ograniczyły ten problem.</p></div>`;$('#main').appendChild(m);$('#dlEdf',m).onclick=()=>save('sample.edf',edfBlob());$('#dlTsv',m).onclick=()=>saveText('sample.tsv',tsv());$('#dlEeg',m).onclick=()=>save('sample.eeg',brainData());$('#dlVhdr',m).onclick=()=>saveText('sample.vhdr',brainHeader());$('#dlVmrk',m).onclick=()=>saveText('sample.vmrk',brainMarkers())}
function buildBids(){const m=document.createElement('section');m.id='mbids';m.className='module';const meta={TaskName:'rest',SamplingFrequency:250,PowerLineFrequency:50,EEGReference:'average',EEGChannelCount:19,RecordingType:'continuous',SoftwareFilters:'n/a'};m.innerHTML=head('BIDS — organizacja zbioru danych EEG','BIDS (Brain Imaging Data Structure) nie jest formatem sygnału. Definiuje nazwy plików, strukturę folderów i metadane, aby zbiór był czytelny, walidowalny i łatwiejszy do ponownego wykorzystania.','BIDS')+`<div class="grid g2"><div><div class="panel"><h2><span class="dot"></span>Przykładowa struktura</h2><pre class="bids-tree">dataset/\n├── dataset_description.json\n├── participants.tsv\n└── sub-01/\n    └── eeg/\n        ├── sub-01_task-rest_eeg.edf\n        ├── sub-01_task-rest_eeg.json\n        ├── sub-01_task-rest_channels.tsv\n        ├── sub-01_task-rest_events.tsv\n        └── sub-01_task-rest_electrodes.tsv</pre></div><div class="panel"><h2><span class="dot"></span>Nazewnictwo</h2><div class="readout"><b>sub-01</b> — uczestnik · <b>task-rest</b> — zadanie · <b>run-01</b> — opcjonalne powtórzenie · <b>_eeg</b> — typ danych.</div></div></div><div><div class="panel"><h2><span class="dot"></span>Sidecar JSON</h2><pre class="format-tree" id="bidsJson"></pre></div><div class="panel"><h2><span class="dot"></span>Pobierz przykłady</h2><div class="row"><button class="btn primary" id="dlDesc">dataset_description.json</button><button class="btn" id="dlParticipants">participants.tsv</button><button class="btn" id="dlSidecar">*_eeg.json</button></div></div><div class="module-note">BIDS organizuje zbiór danych; sam sygnał pozostaje zapisany w obsługiwanym formacie EEG, np. EDF lub BrainVision.</div></div></div>`;$('#main').appendChild(m);$('#bidsJson',m).textContent=JSON.stringify(meta,null,2);$('#dlDesc',m).onclick=()=>saveText('dataset_description.json',JSON.stringify({Name:'EEG-Lab synthetic dataset',DatasetType:'raw'},null,2));$('#dlParticipants',m).onclick=()=>saveText('participants.tsv','participant_id\tage\nsub-01\t25\n');$('#dlSidecar',m).onclick=()=>saveText('sub-01_task-rest_eeg.json',JSON.stringify(meta,null,2))}
window.addEventListener('load',()=>{buildFormats();buildBids()},{once:true});
