const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const fmtClock=d=>`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}:${String(d.getSeconds()).padStart(2,'0')}.${String(d.getMilliseconds()).padStart(3,'0')}`;

function enhanceStroop(){
 const m=$('#mstroop');if(!m||m.dataset.enhancedStroop)return;m.dataset.enhancedStroop='1';
 m.innerHTML=`<div class="head"><div><div class="eyebrow">EKSPERYMENT · STROOP</div><h1>Test Stroopa</h1><p>Nazwij kolor czcionki, ignorując znaczenie słowa. Eksperyment obejmuje maksymalnie 25 prób; każda odpowiedź jest zapisywana z czasem prezentacji bodźca i czasem reakcji.</p></div></div><div class="grid g2"><div><div class="panel"><h2><span class="dot"></span>Próba</h2><div class="stroop-stage"><div class="stroop-word" id="stroopWord">GOTOWY</div></div><div class="stroop-actions"><button class="btn" data-color="red">Czerwony</button><button class="btn" data-color="green">Zielony</button><button class="btn" data-color="blue">Niebieski</button><button class="btn" data-color="yellow">Żółty</button></div><div id="stroopFeedback" class="stroop-feedback"></div></div><div class="panel"><h2><span class="dot"></span>Parametry</h2><div class="field"><label>Liczba prób <output id="stroopCountOut">25</output></label><input id="stroopCount" type="range" min="5" max="25" step="1" value="25"></div><div class="row"><button class="btn primary" id="stroopStart">Rozpocznij eksperyment</button><button class="btn" id="stroopReset">Wyzeruj wyniki</button></div></div></div><div><div class="panel"><h2><span class="dot"></span>Wyniki</h2><div class="stroop-metrics"><div class="metric"><div class="k">PRÓBY</div><div class="v" id="stroopN">0</div></div><div class="metric"><div class="k">POPRAWNE</div><div class="v" id="stroopOk">0</div></div><div class="metric"><div class="k">ŚR. CZAS</div><div class="v" id="stroopRt">—</div></div><div class="metric"><div class="k">INTERFERENCJA</div><div class="v" id="stroopInt">—</div></div></div></div><div class="panel"><h2><span class="dot"></span>Próby</h2><div class="tablewrap stroop-log-wrap"><table><thead><tr><th>#</th><th>czas</th><th>słowo</th><th>kolor</th><th>typ</th><th>RT</th><th>wynik</th></tr></thead><tbody id="stroopLog"></tbody></table></div></div></div></div>`;
 const names={red:'CZERWONY',green:'ZIELONY',blue:'NIEBIESKI',yellow:'ŻÓŁTY'},colors={red:'#d33b32',green:'#168a55',blue:'#2563c7',yellow:'#d59a00'},keys=Object.keys(names);
 let current=null,start=0,running=false,limit=25,rows=[],stats={n:0,ok:0,con:[],inc:[]};
 const render=()=>{const all=[...stats.con,...stats.inc];$('#stroopN',m).textContent=stats.n;$('#stroopOk',m).textContent=stats.ok;$('#stroopRt',m).textContent=all.length?Math.round(all.reduce((a,b)=>a+b,0)/all.length)+' ms':'—';if(stats.con.length&&stats.inc.length){const a=stats.con.reduce((x,y)=>x+y,0)/stats.con.length,b=stats.inc.reduce((x,y)=>x+y,0)/stats.inc.length;$('#stroopInt',m).textContent=Math.round(b-a)+' ms'}else $('#stroopInt',m).textContent='—';$('#stroopLog',m).innerHTML=rows.map(r=>`<tr><td>${r.i}</td><td class="mono">${r.ts}</td><td>${r.word}</td><td>${r.ink}</td><td>${r.type}</td><td>${r.rt} ms</td><td>${r.good?'✓':'✕'}</td></tr>`).join('')};
 function finish(){running=false;current=null;$('#stroopWord',m).textContent='KONIEC';$('#stroopWord',m).style.color='';$('#stroopFeedback',m).textContent=`Zakończono ${stats.n} prób.`;$('#stroopStart',m).disabled=false}
 function trial(){if(!running)return;if(stats.n>=limit){finish();return}const ink=keys[Math.floor(Math.random()*4)],congruent=Math.random()<.5,word=congruent?ink:keys.filter(k=>k!==ink)[Math.floor(Math.random()*3)],shown=new Date();current={ink,word,congruent,ts:fmtClock(shown)};$('#stroopWord',m).textContent=names[word];$('#stroopWord',m).style.color=colors[ink];$('#stroopFeedback',m).textContent=`Próba ${stats.n+1}/${limit}`;start=performance.now()}
 $$('[data-color]',m).forEach(b=>b.onclick=()=>{if(!running||!current)return;const rt=Math.round(performance.now()-start),good=b.dataset.color===current.ink;stats.n++;if(good){stats.ok++;(current.congruent?stats.con:stats.inc).push(rt)}rows.push({i:stats.n,ts:current.ts,word:names[current.word],ink:names[current.ink],type:current.congruent?'zgodna':'niezgodna',rt,good});const f=$('#stroopFeedback',m);f.textContent=good?`Poprawnie · ${rt} ms`:`Błędnie · poprawna odpowiedź: ${names[current.ink].toLowerCase()}`;f.className='stroop-feedback '+(good?'ok':'bad');current=null;render();setTimeout(trial,420)});
 $('#stroopCount',m).oninput=e=>$('#stroopCountOut',m).textContent=e.target.value;
 $('#stroopStart',m).onclick=()=>{if(running)return;limit=Math.min(25,+$('#stroopCount',m).value||25);rows=[];stats={n:0,ok:0,con:[],inc:[]};running=true;$('#stroopStart',m).disabled=true;render();trial()};
 $('#stroopReset',m).onclick=()=>{running=false;current=null;rows=[];stats={n:0,ok:0,con:[],inc:[]};$('#stroopWord',m).textContent='GOTOWY';$('#stroopWord',m).style.color='';$('#stroopFeedback',m).textContent='';$('#stroopStart',m).disabled=false;render()};render();
}
window.addEventListener('load',()=>setTimeout(enhanceStroop,350),{once:true});