const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const GROUPS=[
 {name:'Sygnał',desc:'EEG, pasma i częstotliwość',items:[['m1x','Sygnał EEG i pasma'],['mfft','FFT'],['mlobes','Płat–funkcja–pasmo']]},
 {name:'Pomiar',desc:'elektrody i rejestracja',items:[['m2x','Montaż'],['msimlive2','SimLive'],['mphys2','EMG · EKG · GSR'],['meye2','Eye Tracking']]},
 {name:'Eksperyment',desc:'paradygmat i zdarzenia',items:[['m3','Paradygmat oddball']]},
 {name:'Przetwarzanie',desc:'czyszczenie i przygotowanie',items:[['m5','PreProcessing'],['mica','ICA'],['mpostx','PostProcessing']]},
 {name:'Analiza',desc:'qEEG, topografia i interpretacja',items:[['mqeeg','qEEG'],['mheat','qEEG HeatMap'],['m7','Źródła EEG'],['mclinical','EEG klinicznie'],['mquiz','Sprawdź się']]},
 {name:'Zapis',desc:'formaty i organizacja danych',items:[['mformats','Formaty plików'],['mbids','BIDS']]}
];
let handlers=new Map(),openGroup=0;
function groupedNav(){const nav=$('#nav');if(!nav||nav.dataset.grouped==='1')return;$$('button[data-go]',nav).forEach(b=>handlers.set(b.dataset.go,b.onclick));nav.dataset.grouped='1';nav.innerHTML='';const home=document.createElement('button');home.className='nav-home';home.dataset.home='1';home.innerHTML='<span class="n">⌂</span><span><div class="t">Start</div><div class="d">workflow i zasady</div></span>';home.onclick=()=>navigate('m0');nav.appendChild(home);GROUPS.forEach((g,gi)=>{const box=document.createElement('section');box.className='nav-group';box.dataset.group=String(gi);const head=document.createElement('button');head.className='nav-group-head';head.innerHTML=`<span class="n">${gi+1}</span><span><div class="t">${g.name}</div><div class="d">${g.desc}</div></span><i>⌄</i>`;const body=document.createElement('div');body.className='nav-group-items';g.items.forEach(([id,label])=>{const b=document.createElement('button');b.className='nav-sub';b.dataset.go=id;b.textContent=label;b.onclick=e=>{e.stopPropagation();openGroup=gi;navigate(id);renderGroups()};body.appendChild(b)});head.onclick=()=>{openGroup=openGroup===gi?-1:gi;renderGroups()};box.append(head,body);nav.appendChild(box)});renderGroups();navigate('m0')}
function navigate(id){const fn=handlers.get(id);if(typeof fn==='function'){fn();return}$$('.module').forEach(m=>m.classList.toggle('active',m.id===id));window.dispatchEvent(new CustomEvent('eeg:module',{detail:id}));window.scrollTo({top:0,behavior:'smooth'})}
function renderGroups(){const nav=$('#nav');$$('.nav-group',nav).forEach((g,i)=>g.classList.toggle('open',i===openGroup));const active=$('.module.active')?.id;$$('.nav-sub',nav).forEach(b=>b.classList.toggle('active',b.dataset.go===active));$('.nav-home',nav)?.classList.toggle('active',active==='m0')}
function oddballVisual(){const m=$('#m3');if(!m||m.dataset.visualOddball)return;m.dataset.visualOddball='1';const stim=$('#stim',m),run=$('#runexp',m);if(!stim||!run)return;stim.classList.add('oddball-stage');stim.innerHTML='<div class="oddball-fix">+</div>';const original=run.onclick;run.onclick=async()=>{if(run.disabled)return;run.disabled=true;const p=+( $('#ptarget',m)?.value||20)/100,isi=+($('#isi',m)?.value||900),jit=+($('#jitter',m)?.value||150),n=Math.min(+($('#ntrials',m)?.value||60),18);const label=document.createElement('div');label.className='oddball-live-label';stim.appendChild(label);for(let i=0;i<n;i++){const target=Math.random()<p;stim.innerHTML=`<div class="oddball-stim ${target?'target':'standard'}">${target?'●':'○'}</div><div class="oddball-live-label">${target?'TARGET · S2':'STANDARD · S1'}</div>`;await wait(Math.min(300,Math.max(160,isi*.28)));stim.innerHTML='<div class="oddball-fix">+</div><div class="oddball-live-label">ISI</div>';await wait(Math.min(520,Math.max(180,isi+rand(-jit,jit)-Math.min(300,isi*.28))))}original?.call(run);run.disabled=false;setTimeout(()=>{if(stim.textContent.trim()==='✓')stim.innerHTML='<div class="oddball-done">✓</div><div class="oddball-live-label">symulacja zakończona</div>'},0)}}
const wait=ms=>new Promise(r=>setTimeout(r,ms));const rand=(a,b)=>a+Math.random()*(b-a);
function eyePolish(){const m=$('#meye2');if(!m||m.dataset.eyePolish)return;m.dataset.eyePolish='1';const seg=$('[data-eye-mode]',m)?.closest('.segmented');if(seg){seg.classList.add('eye-mode-box');const lab=document.createElement('span');lab.className='eye-mode-label';lab.textContent='TRYB POMIARU';seg.prepend(lab)}const panel=$('.eye-screen-panel',m);if(panel&&!$('#heatLegend',m)){const l=document.createElement('div');l.id='heatLegend';l.className='heat-legend-v4';l.innerHTML='<span>mniej fiksacji</span><i></i><span>więcej fiksacji</span>';panel.appendChild(l)}}
function init(){setTimeout(()=>{groupedNav();oddballVisual();eyePolish();new MutationObserver(renderGroups).observe($('#main'),{subtree:true,attributes:true,attributeFilter:['class']})},950)}
window.addEventListener('load',init,{once:true});
window.addEventListener('eeg:module',()=>setTimeout(renderGroups,0));